### PR TITLE
Add Docker Healthcheck

### LINKED ISSUE #5760: No CURL or WGET in official image to enable health-check
**Describe the bug**
There is a health-check api in jellyfin. However, it seems we can't check the status with official docker image.

**System (please complete the following information):**
 - Virtualization: Docker
 - Jellyfin Version: Docker latest image, 20210322

**Expected behavior**
Add curl or wget package to official docker image.

### PR DESCRIPTION
**Pull request by MarcelCoding**
**Changes**
Added Docker Healthcheck to ensure jellyfin is always available. (e.g. This enables reverse proxies (traefik) to remove jellyfin from the routes if it is overloaded.)

**Issues**
Fixed #5760 

PS: squash the pr, if the signature should be correct :) I did it in a codespace.

### CODE REVIEW

**Comment by cvium** [comment]
> 
> 
> This also may not work if the server the server has `RequireHttps` enabled

@crobibero  Won't it also break if the server isn't listening on localhost?

**Comment by crobibero** [comment]
> > This also may not work if the server the server has `RequireHttps` enabled
> 
> @crobibero Won't it also break if the server isn't listening on localhost?

Yeah that would also not work… maybe we should just have the health check url default to local host:8096 but allow it to be completely overridden using an ENV variable

**Comment by MarcelCoding** [comment]
How about the `JELLYFIN_PublishedServerUrl` env var?

**Comment by MarcelCoding** [comment]
I personally use a reverse proxy but without https between jellyfin and the proxy. But I could test it.

**Comment by crobibero** [comment]
I believe that’s how most people have Jellyfin set up. Additionally, with 10.8 (unstable) there is an automatic redirect to remove the baseUrl when getting health status

**Comment by MarcelCoding** [comment]
Als long a ceritificate w

**Comment by MarcelCoding** [comment]
I also would like to add the option `-L` to curl that it follows redirects, just in case someone misses something in the configuration.

**Comment by crobibero** [comment]
xxx/health -> xxx/baseurl/health
Implementation here: https://github.com/jellyfin/jellyfin/blob/master/Jellyfin.Server/Middleware/BaseUrlRedirectionMiddleware.cs

**Pull request merged**
