### PR TITLE
[SyncPlay] Remove (unused) SessionId route parameter

### PR DESCRIPTION
**Pull request by crobibero**
This also makes `ListGroups` a `GET` request.

### CODE REVIEW

**Comment by rigtorp** [comment]
Why break the API? You can just add new endpoints NewGroup2, JoinGroup2 etc.

**Comment by Bond-009** [comment]
1. It's cleaner
2. This hasn't been released in a stable build yet, only nightly

**Comment by rigtorp** [comment]
Ok, fair enough on 2). 

1) is a bad reason. I always fights against this with my employees. It always costs money in bugs only to please some once OCD.

**Comment by JustAMan** [comment]
@crobibero where's relevant web PR? they must go in pair

**Comment by crobibero** [comment]
> 
> 
> @crobibero where's relevant web PR? they must go in pair

https://github.com/jellyfin/jellyfin-web/pull/1475
https://github.com/jellyfin/jellyfin-apiclient-javascript/pull/54

**Pull request merged**
