### PR TITLE
Changed string.Length == 0 to string.IsNullOrEmpty in case of null

### PR DESCRIPTION
**Pull request by ikomhoog**
**Changes**
I changed Length == 0 to string.IsNullOrEmpty to account for null values

**Issues**
https://github.com/jellyfin/jellyfin/issues/5408

### CODE REVIEW

**Review by ferferga — APPROVED** [review]

**Review by thornbill — APPROVED** [review]

**Review by nielsvanvelzen — APPROVED** [review]

**Comment by ikomhoog** [comment]
this change didn't make it into the current latest 10.7.0 build, now the dashboard is not working anymore in Release.

Issues:
#5408
#5429
#5425

**Comment by ferferga** [comment]
@ikomhoog Yes: https://github.com/jellyfin/jellyfin/commit/63868eca40d88a0fea5e055d0997a0dd57e8181e

The issue is completely unrelated to this

**Comment by ikomhoog** [comment]
Okay, so it's already being worked on.

**Comment by ferferga** [comment]
@ikomhoog It's not an issue on our end. The config files for web changed and, at install time, users are prompted to replace the config with the version included in our package, and they rejected that. That's the origin of the issues.

**Comment by ikomhoog** [comment]
Thanks for the explanation.

**Pull request merged**
