### PR TITLE
Minor improvements to password reset

### PR DESCRIPTION
**Pull request by dkanada**

### CODE REVIEW

**Comment by dkanada** [comment]
@MrTimscampi the bot is telling me to stop adding TODO comments :laughing: if I wanted to do it now I already would have done it.

**Comment by crobibero** [comment]
What do I need to do to test the changes?

**Comment by dkanada** [comment]
At the moment, wait for my pull request to show up in web as well. This was mainly to get code reviews on the server changes since it's usually a tad more busy. The PR will expose the reset code in the activity log on the dashboard so admins don't have to open a file on the host machine for the reset.

I was also planning on adding it to the notifications, but I think I actually want to migrate the actvitity log to use the notification service on the backend as a nice improvement first.

**Comment by dkanada** [comment]
In general, this doesn't improve usability that much, because it still requires the admin to manually check the dashboard for the reset, at which point they could just change the user password manually. It is a step towards notifications as a useful service though, and I split my PRs up extremely small usually.

**Comment by dkanada** [comment]
@crobibero the web changes were added. Another benefit here is that users can reset their password without the admin knowing what it was, which I suppose has some benefit.

**Comment by dkanada** [comment]
closing to rebase and submit later

**Pull request closed without merging**
