### PR TITLE
Remove unused PowerManagement

### PR DESCRIPTION
**Pull request by Bond-009**
It isn't up to the application to prevent the system from going to sleep

### CODE REVIEW

**Comment by nvllsvm** [comment]
@Bond-009 It certain cases, it should be. For example, many video players like mpv disable screensavers and thus prevents machines from going to sleep. Jellyfin could prevent the machine from sleeping if a live TV recording was scheduled for a particular time.

**Comment by nvllsvm** [comment]
@JustAMan - I'll leave this up to you.

**Comment by Bond-009** [comment]
Force pushed to restart CI

**Comment by anthonylavado** [comment]
Good for me, as the others approved

**Pull request merged**
