### PR TITLE
Add FullNowPlayingQueue property to sessions endpoint

### PR DESCRIPTION
**Pull request by ferferga**
Needed for https://github.com/jellyfin/jellyfin-vue/pull/1040 and should be backwards compatible with any client.

(Not tested)

[openapi.json.txt](https://github.com/jellyfin/jellyfin/files/6489925/openapi.json.txt)

### CODE REVIEW

**Comment by nielsvanvelzen** [comment]
> should be backwards compatible with any client.

Why is this? Does BaseItemDto have all the fields QueueItem had?

**Comment by ferferga** [comment]
QueueItem is the array of items that belong to the currently playing queue that's being played in a remote session (another JF client, Chromecast...) which is called by clients that are controlling those sessions.

QueueItem only had two fields, ``Id`` and ``PlaylistItemId``, which are also present in BaseItemDto. This would only be breaking in case a client require those fields in an specific order (as now the full BaseItem will be returned).

Deprecating this avoids the need for clients to make another request for the full item to fetch images, names, etc... Which is one of the longstanding limitations Web client has with Chromecast queue.

Needs testing though of course as this is completely untested. Also, I'm not sure if some of the clients POST QueueItem-based objects to server and maybe those can trip everything in server.

**Comment by MrTimscampi** [comment]
We shouldn't modify the current API, since we don't know how/if any third party client uses it.

Imo, the proper way to do this would be to mimick the `NowPlayingItem` and `FullNowPlayingItem` fields that are already present.

Maybe have something like `NowPlayingQueue` which would keep the current type and add `FullNowPlayingQueue`, which would return BaseItemDto?

**Comment by nielsvanvelzen** [comment]
Adding a new endpoint that uses BaseItemDto makes more sense yes. Although I _expect_ no issues major issues with this change it might still break something.

**Comment by ferferga** [comment]
I like the new field idea proposed by @MrTimscampi, do you think this might break stuff @nielsvanvelzen ?

I think we added fields to endpoints in the past without a major hassle (as soon as the originals were untouched)

**Comment by nielsvanvelzen** [comment]
Adding new fields to the output should not be a problem, older SDK version will just ignore those. Changing a type or removing a field is a problem since an older SDK version doesn't know what to do when a type is different or missing and throws an exception.
New fields in input (post body/query parameter) should have a default because they won't be send by older SDK versions.

**Review by nielsvanvelzen — APPROVED** [review]
API changes should be fine

**Review by joshuaboniface — APPROVED** [review]
~~Looks good to me and relatively straightforward, but a review from @jellyfin/server would be appreciated before merging.~~

NVM the two reviewers are from server :rofl:

**Pull request merged**
