### PR TITLE
Properly set content type

### PR DESCRIPTION
**Pull request by Bond-009**

### CODE REVIEW

**Comment by cvium** [comment]
A quick search for `AppendCharsetToMimeType` yields no results, so no plugins were harmed in the process as far as I can tell.

**Comment by joshuaboniface** [comment]
Wait should we not be targeting this against the release branch to do a 10.3.7 and fix our stable release?

Clearly a crapton of stuff was broken by that HTTP PR. If this is the genuine fix we should do 10.3.7 with it (and rebuild any affected plugins) to get it back on track.

**Comment by joshuaboniface** [comment]
@cvium I take it that means that if we apply this as a 10.3.7, we don't need any of the per-plugin fixes, correct? Or will the ABI change still require rebuilding all the plugins?

**Comment by cvium** [comment]
The former

**Comment by joshuaboniface** [comment]
Closing as this was superseded by #1537.

**Pull request closed without merging**
