### PR TITLE
Improve and unharden systemd units for LXC and Fedora

### LINKED ISSUE #3182: Jellyfin doesn't exit gracefully with exit code 143
**Describe the bug**
Jellyfin doesn't exit gracefully when it is stopped with systemd.

**System (please complete the following information):**
 - OS: Fedora 32 with kernel 5.6.13-300
 - Virtualization: no
 - Jellyfin Version: 10.5.5

**To Reproduce**

1. Build rpm package from official src rpm. rpmbuild --rebuild jellyfin-10.5.5-1.fc31.src.rpm
2. Install the rpm package and related dependency.
3. Start jelly from systemd and stop it.
4. jellyfin.service exits with code 143 and its status shows failed.

**Expected behavior**

jellyfin.service can exit gracefully.

**Logs**

systemd[1]: Stopping Jellyfin is a free software media system that puts you in control of managing and streaming your media....
jellyfin[826]: [10:28:24] [INF] [2] Main: Received a SIGTERM signal, shutting down
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing CoreAppHost
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing ActivityLogWebSocketListener
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing SessionInfoWebSocketListener
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing ScheduledTasksWebSocketListener
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing SessionWebSocketListener
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing EmbyTV
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing ApiEntryPoint
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing ServerEntryPoint
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing EntryPoint
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing DeviceAccessEntryPoint
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing LibraryMonitorStartup
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing ExternalPortForwarding
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing LibraryChangedNotifier
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing RecordingNotifier
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing ServerEventNotifier
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing StartupWizard
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing UdpServerEntryPoint
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing UserDataChangeNotifier
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing DeviceManagerEntryPoint
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing CollectionManagerEntryPoint
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing ActivityLogEntryPoint
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing DlnaEntryPoint
jellyfin[826]: [10:28:24] [INF] [2] Dlna: Disposing SsdpDevicePublisher
jellyfin[826]: [10:28:24] [INF] [2] Dlna: Disposing PlayToManager
jellyfin[826]: [10:28:24] [INF] [2] Dlna: Disposing DeviceDiscovery
jellyfin[826]: [10:28:24] [INF] [2] Dlna: Disposing SsdpCommunicationsServer
jellyfin[826]: [10:28:24] [INF] [2] Dlna: SsdpCommunicationsServer disposing _BroadcastListenSocket
jellyfin[826]: [10:28:24] [INF] [2] Dlna: SsdpCommunicationsServer Disposing 2 sendSockets
jellyfin[826]: [10:28:24] [INF] [2] Dlna: SsdpCommunicationsServer disposing sendSocket from 0.0.0.0
jellyfin[826]: [10:28:24] [INF] [2] Dlna: SsdpCommunicationsServer disposing sendSocket from 192.168.50.3
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing NotificationEntryPoint
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing EntryPoint
systemd[1]: jellyfin.service: Main process exited, code=exited, status=143/n/a
systemd[1]: jellyfin.service: Failed with result 'exit-code'.
systemd[1]: Stopped Jellyfin is a free software media system that puts you in control of managing and streaming your media..
systemd[1]: jellyfin.service: Consumed 1min 8.641s CPU time.

**Additional context**
I'm not sure whether the application exits with code 0 or 'SuccessExitStatus=143' is added to the systemd unit file is the correct way to fix it.

### LINKED ISSUE #6984: [Issue]: 10.8-alpha3 and unstable: Service does not start on LXC anymore
### Please describe your bug

Since https://github.com/jellyfin/jellyfin/pull/6953 Jellyfin will not start on LXC anymore and exits with `(code=exited, status=226/NAMESPACE)`

This is most likely caused by permission issues on the ressources which systemd tries to modify based on the additional hardening.

I checked each of the new options and adding an override at `/etc/systemd/system/jellyfin.service.d/override.conf` with the following content fixes the startup:
```
RestrictNamespaces=false
ProtectControlGroups=false
ProtectKernelLogs=false
ProtectKernelModules=false
ProtectKernelTunables=false
PrivateTmp=false
```

If there is any other way to properly make this work on LXC without disabling those settings that would be optimal. Otherwise we should consider reverting those changes because they can break existing installs on LXC.

### Jellyfin Version

10.8-alpha3

### Environment

```markdown
- OS: Debian 11
- Virtualization: LXC privileged on proxmox VE 7.1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by joshuaboniface**
**Changes**
1. Adjusts the hardening parameters of the systemd unit based on the feedback in #6984. As mentioned there, the fact that we run as an unprivileged user should prevent most of these from being problematic, and this ensures we have unified configuration between LXC and other installs.
2. Ports the various changes to the Debian service unit (this hardening, plus a few other formatting tweaks) into the Fedora/CentOS unit, as well as port-back two other options (the Group= and WorkingDirectory=) from the Fedora unit into the Debian unit. @brianjmurrell as our go-to Fedora guy, can you give these changes a quick once-over and let me know if they seem OK? I imagine they're fine but better to be sure!
3. Adds proper exit status handling for code 143 on stop.

**Issues**
Fixes #6984
Fixes #3182

### CODE REVIEW

**Review by crobibero — APPROVED** [review]
:shrug:

**Comment by crobibero** [comment]
From https://github.com/jellyfin/jellyfin/pull/7012
>  Remove `ProtectClock=true` in jellyfin.service

Probably applicable to this PR as well.

**Comment by nyanmisaka** [comment]
should fix #7033 I guess

**Comment by nnnlog** [comment]
I think the merge should be postponed until #7025 is resolved.

**Comment by joshuaboniface** [comment]
@nnnlog Should this continue to wait, or is it OK in testing?

**Comment by nnnlog** [comment]
@joshuaboniface Sorry for late.
I got same result in latest version of jellyfin-ffmpeg. (https://github.com/jellyfin/jellyfin/issues/7025#issuecomment-1066000165)
Looks like have to wait.

**Comment by joshuaboniface** [comment]
OK I'm thinking that this one in particular shouldn't wait entirely for more removals. Those can be done later if we find more need to come out.

Requesting second review from @jellyfin/server

**Review by oddstr13 — APPROVED** [review]
Looks good, but as I mentioned in chat, it could really do with a comment about the usage of the user variable in the defaults file.

```bash
# This variable is currently used by upstart and init.d
# It is not, and can not be respected by systemd
```

https://github.com/jellyfin/jellyfin/blob/6a3da3a031260b01409f6b03ddfe12c31a51b068/debian/conf/jellyfin#L49

**Pull request merged**
