### PR TITLE
WIP - Removing dpkg dependency on non Debian based build servers

### LINKED ISSUE #5529: build.sh fails on Fedora because dpkg is missing
Building current master fails on Fedora.

```
$ ./build.sh -t native -p linux.amd64
which: no dpkg in (/usr/lib64/ccache:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/heylix/.dotnet/tools:/home/heylix/.local/bin:/home/heylix/bin)
Cross-building is not supported for native builds, use 'docker' builds on amd64 for cross-building.
```

Same with the fedora target.

### PR DESCRIPTION
**Pull request by Harnish**
Move from using dpkg to determine the architecture to using uname which is more widely used.  

**Changes**
switch from dpkg to uname in build.sh
moved all the amd64 files in deployment to x86_64

**Issues**
Fixes #5529

### CODE REVIEW

**Comment by Harnish** [comment]
I need to make sure I didn't break anything with ARM* archictures.

**Comment by Harnish** [comment]
This will also change native build command to use .x86_64 instead of the .amd64

**Review by joshuaboniface — CHANGES_REQUESTED** [review]
The ARM ones would need to be renamed too (assuming that those change, not 100% sure).

**Comment by Bond-009** [comment]
@Harnish Any updates?

**Comment by Bond-009** [comment]
Closing, 6 months inactivity

**Pull request closed without merging**
