### PR TITLE
Ignore .zfs folder

### PR DESCRIPTION
**Pull request by Bond-009**
Maybe helps with #10215 ?

### CODE REVIEW

**Review by crobibero — APPROVED** [review]

**Review by Shadowghost — APPROVED** [review]
I've been using ZFS for ages and didn't even know this exists...

**Comment by systemcrash** [comment]
I think there's a tunable. 

`zfs set snapdir={hidden|visible} /mnt/zfspool`

**Comment by cvium** [comment]
Should we not just ignore all hidden folders (parent folders do not count)?

**Comment by Shadowghost** [comment]
Valid point. IMHO it would make sense.

**Comment by Bond-009** [comment]
I'm sure some people keep their media in hidden folders (maybe the nsfw kind)
We should probably not show hidden dirs on the add media library page if this is really desired.

**Review by barronpm — APPROVED** [review]

**Comment by JPVenson** [comment]
> I'm sure some people keep their media in hidden folders (maybe the nsfw kind) We should probably not show hidden dirs on the add media library page if this is really desired.

i think this would be a good compromise. Not showing them but if the user pastes the path directly still allow them.

**Pull request merged**
