### PR TITLE
Convert CreatePlaylist to use query params instead of body

### PR DESCRIPTION
**Pull request by crobibero**
Fixes https://github.com/jellyfin/jellyfin/issues/4760

Note- the client still needs to add a `Content-Type` header.

### CODE REVIEW

**Comment by Extarys** [comment]
FWIW the issue also happens with Gelli.

Thanks for the quick fix :rocket:

**Review by oddstr13 — APPROVED** [review]
I think I would have preferred body overriding query, but either should be fine as long as we're consistent about it.

Is it possible to mark the query params as deprecated for the OpenAPI spec in some way?

**Comment by oddstr13** [comment]
CodeQL errors should probably get a in-depth review. @jellyfin/server

**Review by BaronGreenback — APPROVED** [review]

**Comment by cvium** [comment]
> 
> 
> CodeQL errors should probably get a in-depth review. @jellyfin/server

Not a problem I think. It's just a filename.

**Pull request merged**
