### PR TITLE
Added audiobook list resolver test cases.

### PR DESCRIPTION
**Pull request by dbchessher**
**Changes**
Added test cases for the audiobook list resolver class to check that names, extensions, and edge cases are validated against.

**Issues**
N/A

### CODE REVIEW

**Review by Bond-009 — APPROVED** [review]

**Comment by Bond-009** [comment]
`Resolve_WithAlternativeFiles_ShouldIncludeAlternativesInAudioBookInfo` fails

**Comment by Shadowghost** [comment]
@dbchessher would be nice if you can fix the failing test so we can move on with this.

**Review by gaurovgiri — APPROVED** [review]
Looks good to me

**Comment by fogolin** [comment]
Hi there @dbchessher, did you get any time to review this failing test?

**Comment by Bond-009** [comment]
Closing this as this has been inactive for over a year.

**Pull request closed without merging**
