### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by Bond-009**
Unsure about the z440.atl.core updates, I can drop them if needed.

### CODE REVIEW

**Review by nielsvanvelzen — APPROVED** [review]

**Review by Shadowghost — APPROVED** [review]

**Comment by mooninite** [comment]
Is there a technical reason to bump the SDK req? Is there something in Jellyfin that now requires the bleeding edge stable SDK that was released only a few days ago?

I realize it is easy enough for you to bump and build on your infrastructure, but those that package Jellyfin on other Linux distributions don't have that extreme flexibility.

Fedora's dotnet 8.0 package is currently at runtime 8.0.10 / SDK 8.0.111. I'm requesting it be updated but it will be days / weeks for that to finalize.

If there is no technical requirement please refrain from bumping the SDK req in the future.

**Comment by mooninite** [comment]
I have learned the 4xx series of SDK is a problem for those that build from source. Fedora can only ship the 1xx series SDK and it currently builds and runs Jellyfin. Can you follow the 1xx series SDK instead? Or go back to 8.0.0 until there is a technical requirement for a different version.

**Comment by Bond-009** [comment]
@mooninite Sorry, my mistake, this change shouldn't have hit the release branch. Cody already fixed it for the next point release.

**Comment by mooninite** [comment]
@Bond-009 no problem, thank you!

**Pull request merged**
