### PR TITLE
Remove opf extension for book types

### LINKED ISSUE #3766: OPF files being imported as a book in Jellyfin 10.6.1
When I create a book library and have Jellyfin 10.6.1 scan my books directory it is importing the metadata.opf files as if they are books. It never did this before. This is on a brand new library and new scan of the books directory. If you go in to the "book" it will let you try and download the metadata.opf file like it is a book you can download and read. It should be reading these opf files as the metadata they are, instead of thinking they are books.

Screenshot (46)

### PR DESCRIPTION
**Pull request by Artiume**
**Changes**

**Issues**

Fixes #3766
Fixes jellyfin/jellyfin-plugin-bookshelf#22

### CODE REVIEW

**Comment by Extarys** [comment]
image
Can't wait for my books to not be doubled.

**Comment by oddstr13** [comment]
Link to [conversation on Matrix](https://matrix.to/#/!YOoxJKhsHoXZiIHyBG:matrix.org/$6GSjzdK0TkhpUBoH_KMIzBfw1P3N43yRxLZiklloZMw?via=bonifacelabs.ca&via=matrix.org&via=t2bot.io)

**Comment by Extarys** [comment]
This shouldn't be merge just yet then in favor of including `opf` ebooks while excluding `content.opf` and `metadata.opf`.

**Review by barronpm — APPROVED** [review]

**Comment by joshuaboniface** [comment]
Merging, we can correct further in rc2.

**Comment by joshuaboniface** [comment]
@Extarys If there isn't, would you mind making an issue about that so we don't lose track?

**Pull request merged**
