### PR TITLE
Add missing properties to typescript axios generator

### PR DESCRIPTION
**Pull request by Camc314**
**Changes**
Adds missing additional properties to typescript axios apiclient generator
For more info see [here](https://github.com/OpenAPITools/openapi-generator/issues/5008)

### CODE REVIEW

**Review by crobibero — APPROVED** [review]

**Comment by crobibero** [comment]
Build will still fail because of the variables used

**Review by crobibero — APPROVED** [review]

**Review by joshuaboniface — APPROVED** [review]

**Comment by joshuaboniface** [comment]
@Camc314 Do these apply to both stable and unstable builds? If so this is fine. If it's just unstable though, they should go in the "additionalParameters" variable.

**Comment by crobibero** [comment]
These apply to both stable & unstable

**Comment by Camc314** [comment]
Applies to both since we're using `withSeparateModelsAndApi` the api dir and models dir needs to be specified

**Pull request merged**
