### PR TITLE
Test Template for unraid - should work

### PR DESCRIPTION
**Pull request by drakus72**
Add into the Docker tab
https://github.com/jellyfin/jellyfin/unRaid/docker-templates
save
click add container and choose jellyfin

### CODE REVIEW

**Comment by joshuaboniface** [comment]
I don't use unRaid, but it looks good to me. Are you able to write up documentation for how to use it in the README?

**Comment by drakus72** [comment]
Yes. I will add a readme.md in a few minutes

**Comment by joshuaboniface** [comment]
Thanks, I'll add a section in the main README as well!

**Comment by drakus72** [comment]
I will try to keep it updated as well, There are a few more options I am going to add, just need a little more testing on those yet.

Plus need to add an icon once one is designed.

**Comment by Terror-Gene** [comment]
attempting to use this didn't work. after following the link it seems broken (404)

broken link: https://github.com/jellyfin/jellyfin/unRaid/docker-templates

using this worked: https://github.com/jellyfin/jellyfin/tree/master/unRaid/docker-templates

BUT.. it then filled the templates with a bunch of crap...
capture
(& more)

any ideas?

**Comment by drakus72** [comment]
Thank you will update instructions soon

**Comment by drakus72** [comment]
> BUT.. it then filled the templates with a bunch of crap...

> 
> any ideas?

No idea why that is happening unless you have other repositories in there. It should only pull Jellyfin repository to set that up and nothing else.

**Comment by Terror-Gene** [comment]
Strange. I only had the emby template in there as well at that time. But I just tested without any other template & all that stuff only appears when I use the Jellyfin template.

**Comment by drakus72** [comment]
Very weird. I will look into it more, it shouldn't be showing anything for it isn't pulling from anything else.

**Comment by d2dyno** [comment]
I can confirm, random templates are pulled in when using that url.

**Comment by Terror-Gene** [comment]
That didn’t work. When using that link I get no templates.
When using https://github.com/jellyfin/jellyfin/tree/master/unRaid/docker-templates/jellyfin.xml I get the same results as before (a bunch of stuff, including jellyfin).

For reference, here is embys template repository link & that only gives me emby & emby beta templates.
https://github.com/MediaBrowser/Emby.Build/tree/master/unraid-templates/emby

**Pull request merged**
