### PR TITLE
Fix systemd not breaking whitespace in env vars

### PR DESCRIPTION
**Pull request by strugee**
**Changes**

`${}` includes the environment variable as one word; `$` breaks words by whitespace. So before this specifying e.g. `JELLYFIN_ADDITIONAL_OPTS="--published-server-url https://example.com/"` would result in an error about `--published-server-url https://example.com/` not being a recognized option.

**Issues**

:man_shrugging:

### CODE REVIEW

**Comment by Shadowghost** [comment]
Since this is a valid bugfix, can you please target the 10.8 release branch? Thanks for finding and fixing this.

**Review by Bond-009 — APPROVED** [review]

**Comment by strugee** [comment]
@Shadowghost sure, do you want me to edit this PR or send a followup backport against stable?

**Comment by crobibero** [comment]
@strugee just editing this PR is fine

**Comment by strugee** [comment]
Done!

**Review by joshuaboniface — APPROVED** [review]

**Pull request merged**
