### PR TITLE
Add hearing impaired subtitle stream indicator

### LINKED ISSUE #4291: Identify external HI/CC/SDH subtitles
As discussed on #jellyfin-dev:matrix.org, I'm working to have a common naming convention for external hearing-impaired / close captioned / deaf hearing subtitles. Here's what is the proposed naming:

1. Movie.en.hi.srt
2. Movie.en.cc.srt
3. Movie.en.sdh.srt

All of them should be recognized as English subtitles and having the tag identified in Jellyfin UI would be nice.

Kodi already support them. Plex have implemented it in their new Movie Agent. I' ve been talking with Luke from Emby and he agreed to implement it in Emby.

It would be nice to have Jellyfin join the club. :-)

### PR DESCRIPTION
**Pull request by 1337joe**
This is my first time touching the database contents, definitely let me know if anything there looks questionable.

**Changes**
- Add a flag to media stream to indicate the stream is for hearing impaired users
  - Flag source: ffprobe `hearing_impaired` disposition, "sdh"/"hi"/"cc" in external stream file name
  - Flag use: Add localized "Hearing Impaired" indicator when selecting subtitle stream

**Issues**
Fixes #4291

### CODE REVIEW

**Review by cvium — APPROVED** [review]

**Review by Bond-009 — APPROVED** [review]

**Comment by kooolarpan** [comment]
Finally, it's done. 👍

**Comment by systemcrash** [comment]
Shouldn't this update the docs also?

**Comment by cvium** [comment]
The docs are in a different repository, but yes the docs should probably be updated

**Comment by 1337joe** [comment]
Coming in jellyfin/jellyfin-docs/pull/715

**Comment by sollermun** [comment]
This fix does not seem to work when the name of the files contains quality information, e.g. Movie Name (2020) WEBRip-1080p.en.hi.srt.

Jellyfin recognizes the subtitle as "en - Hindi - SUBRIP - External"

**Comment by Javex** [comment]
@sollermun what version are you running? I came here because I had a similar issue and after some searching found out that the latest release (`10.8.10`) does not include the feature yet. I then tested the issue against the current `master` and there it worked as described. If you're running `10.8.x` instead of the latest nightly/unstable build, that might be the reason and we'll have to wait for `10.9` to be released.

**Comment by mikewesten** [comment]
I think it's too sensitive. Things like **Movie.Year.Subs for Chinese Audio.eng.srt** are being picked up and displayed as Hearing Impaired instead of the previously useful display of "Subs for Chinese Audio". Is it meant to pull the letters "HI" even when sandwiched between strings of other letters? Changing it to something like **Movie.Year.Subs for C-h-i-n-e-s-e Audio.eng.srt** will get it to display in the selector as "Subs for C-h-i-n-e-s-e Audio" instead of "Hearing Impaired". Hmm.

**Comment by thornbill** [comment]
@mikewesten please open an issue instead of commenting on an old PR

**Pull request merged**
