### PR TITLE
Fix Async handling for DLNA control requests

### LINKED ISSUE #2164: DLNA: No folders or files listed when browsing
**Describe the bug**
When attempting to browse Jellyfin content (via VLC/DLNA), no folders or media items are listed.

**To Reproduce**

1. Open VLC
2. Click on `Universal Plug'n'Play`
3. Double click Jellyfin instance
4. No files or folders are displayed underneath Jellyfin

**Expected behavior**

List of libraries is displayed and can be expanded to view media items.

**Logs**

```
[14:59:43] [DBG] No matching device profile found. Connection=close, Accept=*/*, Host=192.168.1.141:8096
[14:59:47] [DBG] No matching device profile found. Content-Type=text/xml; charset="utf-8", Host=192.168.1.141:8096, User-Agent=6.2.9200 2/, UPnP/1.0, Portable SDK for UPnP devices/1.6.19, Content-Length=440, SOAPACTION="urn:schemas-upnp-org:service:ContentDirectory:1#Browse"
```

**Screenshots**

image

**System (please complete the following information):**
 - OS: Docker
 - Browser: DLNA - VLC
 - Jellyfin Version: 10.5-dev bc7cbfb21aced3ad72ddd98183ad457e50b48dc8
 - Installed Plugins: None
 - Reverse proxy: None

**Additional context**
Browsing and playing recorded media works fine on 10.4.3.
Related: #1181 #2132 #2134

### PR DESCRIPTION
**Pull request by PrplHaz4**
Based on @Bond-009 changes here - see this for logs and discussion: https://github.com/jellyfin/jellyfin/pull/2297

**Changes**

- Use Async methods in `BaseControlHandler.cs`

**Issues**

- Fixes #2164

### CODE REVIEW

**Comment by PrplHaz4** [comment]
> .ConfigureAwait(false)

Sorry @Bond-009 - way outta my league here...I will attempt to muddle through it but may take a while.

**Comment by Bond-009** [comment]
Np, I can do it if you want

**Comment by PrplHaz4** [comment]
Go for it. I can't even get it to compile.

**Comment by PrplHaz4** [comment]
@Bond-009 Not sure why I'm still screwing around with this - got it to compile - did I go up the stack far enough with this one? https://github.com/jellyfin/jellyfin/pull/2316/commits/f8d50d49730afdf82e0fa767f439bf83c8910b3d

**Comment by PrplHaz4** [comment]
Closing.  This was fixed by an actual developer here: https://github.com/jellyfin/jellyfin/pull/2297

**Pull request closed without merging**
