### PR TITLE
Fine tune DB settings

### PR DESCRIPTION
**Pull request by Bond-009**
I will be running this on my own server for a while to make sure it's fine

### CODE REVIEW

**Comment by darthShadow** [comment]
Have you seen any significant difference from changing the locking_mode to exclusive?

In my experience with other sqlite apps, the difference has been negligible enough when compared to the drawback of other processes not being able to use the DB simultaneously.

---

Some other optimizations that may be worth changing from the defaults:

* `page_size` default to `4096` (https://www.sqlite.org/pragma.html#pragma_page_size)
Changing this will require a `VACCUM` before the `journal_mode` is set to `WAL`
```
at the next [VACUUM](https://www.sqlite.org/lang_vacuum.html) command that is run on the same database connection while not in [WAL mode](https://www.sqlite.org/wal.html)
```

* `cache_size` default to atleast `-65536` (64 MB) (https://www.sqlite.org/pragma.html#pragma_cache_size). The default of `-2000` (2 MB) is very small to be of much use.

* `temp_store` to `2` (`MEMORY`) (https://www.sqlite.org/pragma.html#pragma_temp_store)

* `synchronous` to `NORMAL` (https://www.sqlite.org/pragma.html#pragma_synchronous)
```
[WAL mode](https://www.sqlite.org/wal.html) is safe from corruption with synchronous=NORMAL, and probably DELETE mode is safe too on modern filesystems. WAL mode is always consistent with synchronous=NORMAL, but WAL mode does lose durability. A transaction committed in WAL mode with synchronous=NORMAL might roll back following a power loss or system crash.
```

**Comment by darthShadow** [comment]
> page_size should already be 4096?

The `page_size` used to default to `1024` for a long time. Even Plex defaults to `1024` for a few OS-es even now.

I figured it was worth enforcing a larger value OOTB but anyone who wants to can just as easily change it themselves, since it's not a connection-specific parameter, unlike the others.

> The locking mode already was exclusive (for the main db, now it's just applied to all of them)

Ah, alright. Not sure if it would be worth it to change to `NORMAL` so other processes on the system can access the DB simultaneously?

**Comment by darthShadow** [comment]
Looks like you just changed it to `NORMAL` 😄

**Comment by darthShadow** [comment]
There is another setting (`mmap_size`) that can provide significant benefits, especially when the OS has enough memory available, but it should probably be configurable by the user rather than enforced in the code.

https://www.sqlite.org/mmap.html

https://www.sqlite.org/pragma.html#pragma_mmap_size

**Comment by brettpetch** [comment]
Hey @Bond-009, thanks for looking at this. @cvium has pointed out that WAL mode was previously reverted due to large sizes, I wonder if flushing WAL to the main db should happen as part of the db optimization task if this were to be pushed into production?

https://github.com/jellyfin/jellyfin/issues/1655

**Comment by Metuant** [comment]
Is it possible to expose these settings to the admin (the way Emby/Plex do) vs hardcoding values?

**Comment by darthShadow** [comment]
If you are open to modifications in the Optimize DB task too, perhaps the task could be split up into a daily and biweekly task with the following breakup:

#### Daily

* `PRAGMA wal_checkpoint(RESTART);` (https://www.sqlite.org/pragma.html#pragma_wal_checkpoint)

* `PRAGMA quick_check(1);` (https://www.sqlite.org/pragma.html#pragma_quick_check). The `1` indicates that it should quit immediately on the first error rather than the default of `100`.

* `PRAGMA analysis_limit=1024; PRAGMA optimize; REINDEX;` (https://www.sqlite.org/pragma.html#pragma_analysis_limit & https://www.sqlite.org/pragma.html#pragma_optimize). The non-zero analysis limit will ensure that it runs quickly enough to not cause any lockups.

#### Bi-weekly

* `VACUUM;` (This can take some time so moved to bi-weekly rather than daily)

* `PRAGMA integrity_check(1);` (https://www.sqlite.org/pragma.html#pragma_integrity_check). The `1` indicates that it should quit immediately on the first error rather than the default of `100`.

* `PRAGMA foreign_key_check;` (https://www.sqlite.org/pragma.html#pragma_foreign_key_check)

* `PRAGMA analysis_limit=0; PRAGMA optimize; REINDEX;` (https://www.sqlite.org/pragma.html#pragma_analysis_limit & https://www.sqlite.org/pragma.html#pragma_optimize). The zero analysis limit ensures that it checks all rows rather than only `1024` rows from the daily run.

**Comment by brettpetch** [comment]
> If you are open to modifications in the Optimize DB task too, perhaps the task could be split up into a daily and biweekly task with the following breakup:
> #### Daily
> 
>     * `PRAGMA wal_checkpoint(RESTART);` (https://www.sqlite.org/pragma.html#pragma_wal_checkpoint)
> 
>     * `PRAGMA quick_check(1);` (https://www.sqlite.org/pragma.html#pragma_quick_check). The `1` indicates that it should quit immediately on the first error rather than the default of `100`.
> 
>     * `PRAGMA analysis_limit=1024; PRAGMA optimize; REINDEX;` (https://www.sqlite.org/pragma.html#pragma_analysis_limit & https://www.sqlite.org/pragma.html#pragma_optimize). The non-zero analysis limit will ensure that it runs quickly enough to not cause any lockups.
> 
> 
> #### Bi-weekly
> 
>     * `VACUUM;` (This can take some time so moved to bi-weekly rather than daily)
> 
>     * `PRAGMA integrity_check(1);` (https://www.sqlite.org/pragma.html#pragma_integrity_check). The `1` indicates that it should quit immediately on the first error rather than the default of `100`.
> 
>     * `PRAGMA foreign_key_check;` (https://www.sqlite.org/pragma.html#pragma_foreign_key_check)
> 
>     * `PRAGMA analysis_limit=0; PRAGMA optimize; REINDEX;` (https://www.sqlite.org/pragma.html#pragma_analysis_limit & https://www.sqlite.org/pragma.html#pragma_optimize). The zero analysis limit ensures that it checks all rows rather than only `1024` rows from the daily run.

I agree here as well. If implemented here it'd likely make most sense. 

https://github.com/jellyfin/jellyfin/tree/master/Emby.Server.Implementations/ScheduledTasks/Tasks/OptimizeDatabaseTask.cs#L63-L100

**Comment by Bond-009** [comment]
Making things configurable and changing the scheduled tasks can wait for another PR IMO

**Comment by brettpetch** [comment]
Tried building off the branch on a fresh install.

```
[2023-01-10 22:14:19.362 -05:00] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Applying migration '"AddPeopleQueryIndex"'
[2023-01-10 22:14:19.362 -05:00] [INF] [1] Jellyfin.Server.Migrations.Routines.AddPeopleQueryIndex: Creating index idx_TypedBaseItemsUserDataKeyType
[2023-01-10 22:14:19.363 -05:00] [ERR] [1] Jellyfin.Server.Migrations.MigrationRunner: Could not apply migration '"AddPeopleQueryIndex"'
Busy: SQLitePCL.pretty.SQLiteException: database is locked
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.SQLiteDatabaseConnection.PrepareStatement(String sql, String& tail)
   at SQLitePCL.pretty.DatabaseConnection.PrepareStatement(IDatabaseConnection This, String sql)
   at SQLitePCL.pretty.DatabaseConnection.Execute(IDatabaseConnection This, String sql)
   at Jellyfin.Server.Migrations.Routines.AddPeopleQueryIndex.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
[2023-01-10 22:14:19.367 -05:00] [FTL] [1] Main: Error while starting server.
Busy: SQLitePCL.pretty.SQLiteException: database is locked
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.SQLiteDatabaseConnection.PrepareStatement(String sql, String& tail)
   at SQLitePCL.pretty.DatabaseConnection.PrepareStatement(IDatabaseConnection This, String sql)
   at SQLitePCL.pretty.DatabaseConnection.Execute(IDatabaseConnection This, String sql)
   at Jellyfin.Server.Migrations.Routines.AddPeopleQueryIndex.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[2023-01-10 22:14:19.367 -05:00] [INF] [1] Main: Running query planner optimizations in the database... This might take a while
[2023-01-10 22:14:19.377 -05:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "CoreAppHost"
[2023-01-10 22:14:19.378 -05:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "MusicBrainzAlbumProvider"
[2023-01-10 22:14:19.378 -05:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "EmbyTV"
[2023-01-10 22:14:19.379 -05:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "SchedulesDirect"
[2023-01-10 22:14:19.379 -05:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "MusicBrainzArtistProvider"
[2023-01-10 22:14:19.380 -05:00] [INF] [2] Main: Received a SIGTERM signal, shutting down
```

**Comment by Bond-009** [comment]
It works for me and should be fine to go into master for further testing

**Review by crobibero — APPROVED** [review]

**Review by barronpm — APPROVED** [review]

**Review by crobibero — APPROVED** [review]

**Comment by dannymichel** [comment]
If there were awards for PRs, this would win the top PR reward of jellyfin history. It's like a completely new app with this PR

**Comment by VigibotDev** [comment]
I get 100% I/O on jbd2/nvme0n1p2 (Samsung PRO SSD) when Jellyfin rescan to delete a lot of music file.
I tryed to re enable WAL to make some benchmark

jbd2 is the filesystem journaling quickly make a lot of I/O when Jellyfin use library.db....

(root|/var/lib/jellyfin/data) sudo -u jellyfin sqlite3 library.db 'PRAGMA journal_mode=WAL;'
wal

But on restart Jellyfin overwrite the journal_mode :

(root|/var/lib/jellyfin/data) sudo -u jellyfin sqlite3 library.db 'PRAGMA journal_mode;'
delete

Can you give a some tuning in system.xml for sysadmins ?
A way to consume more ram (i have 64GB on this server) for better performance ? I must move my database to a ramfs (lol) or a non journaling fs ?

I temporarily disable write barrier on the partition and I make in few minutes that make hours, and I re enable it to keep safe...

**Pull request merged**
