### PR TITLE
Add index for DateCreated on ActivityLogs

### PR DESCRIPTION
**Pull request by cvium**
**Changes**
ActivityLogs is mostly queried with a greater than DateCreated clause. An index should fix any performance issues.

Query:
```SQL
EXPLAIN QUERY PLAN
SELECT "a"."Id", "a"."DateCreated", "a"."ItemId", "a"."LogSeverity", "a"."Name", "a"."Overview", "a"."RowVersion", "a"."ShortOverview", "a"."Type", "a"."UserId"
FROM "ActivityLogs" AS "a"
WHERE DateCreated >= date('2022-01-01')
  AND (("a"."UserId" <> '00000000-0000-0000-0000-000000000000') = true)
ORDER BY "a"."DateCreated" DESC
LIMIT 7 OFFSET 0;
```

Query Plan before:
```
SCAN TABLE ActivityLogs AS a
USE TEMP B-TREE FOR ORDER BY
```

Query Plan after:
```
SEARCH TABLE ActivityLogs AS a USING INDEX IX_ActivityLogs_DateCreated (DateCreated>?)
```

I tested it with some dummy data. Roughly 700k rows. Without the index it was ~800ms and with the index ~13ms.

**Issues**
Might fix some of the issues with slow dashboard

### CODE REVIEW

**Review by crobibero — APPROVED** [review]

**Review by Bond-009 — APPROVED** [review]
Why are the `#nullable disable` needed?

**Comment by cvium** [comment]
> Why are the `#nullable disable` needed?

It's auto generated by `dotnet ef`

**Comment by nielsvanvelzen** [comment]
```
Error: /home/runner/work/jellyfin/jellyfin/Jellyfin.Server.Implementations/Migrations/20221022080052_AddIndexActivityLogsDateCreated.cs(7,26): error CS1591: Missing XML comment for publicly visible type or member 'AddIndexActivityLogsDateCreated' [/home/runner/work/jellyfin/jellyfin/Jellyfin.Server.Implementations/Jellyfin.Server.Implementations.csproj]
Error: /home/runner/work/jellyfin/jellyfin/Jellyfin.Server.Implementations/Migrations/20221022080052_AddIndexActivityLogsDateCreated.cs(9,33): error CS1591: Missing XML comment for publicly visible type or member 'AddIndexActivityLogsDateCreated.Up(MigrationBuilder)' [/home/runner/work/jellyfin/jellyfin/Jellyfin.Server.Implementations/Jellyfin.Server.Implementations.csproj]
Error: /home/runner/work/jellyfin/jellyfin/Jellyfin.Server.Implementations/Migrations/20221022080052_AddIndexActivityLogsDateCreated.cs(18,33): error CS1591: Missing XML comment for publicly visible type or member 'AddIndexActivityLogsDateCreated.Down(MigrationBuilder)' [/home/runner/work/jellyfin/jellyfin/Jellyfin.Server.Implementations/Jellyfin.Server.Implementations.csproj]
Error: /home/runner/work/jellyfin/jellyfin/Jellyfin.Server.Implementations/Migrations/20221022080052_AddIndexActivityLogsDateCreated.Designer.cs(17,33): error CS1591: Missing XML comment for publicly visible type or member 'AddIndexActivityLogsDateCreated.BuildTargetModel(ModelBuilder)' [/home/runner/work/jellyfin/jellyfin/Jellyfin.Server.Implementations/Jellyfin.Server.Implementations.csproj]
```

**Comment by cvium** [comment]
This seems relevant https://github.com/dotnet/efcore/issues/25624

**Review by joshuaboniface — APPROVED** [review]
No idea why I'm a codeowner but I trust y'all.

**Pull request merged**
