### PR TITLE
Fix potential NullReferenceException

### LINKED ISSUE #871: Typo means null values aren't handled properly
**Description**
A missing character in MediaBrowser.Model/Dlna/StreamBuilder.cs on line 300 has the potential to cause a NullReferenceException to be thrown, as I have found while working on a plugin. A pull request seems like overkill for this, so posting as an issue.

```
int? inputAudioChannels = audioStream?.Channels;
int? inputAudioBitrate = audioStream?.BitDepth;
int? inputAudioSampleRate = audioStream?.SampleRate;
int? inputAudioBitDepth = audioStream.BitDepth;
```

it seems the last line should be `int? inputAudioBitDepth = audioStream?.BitDepth;`

**To Reproduce**
1. Use development version of jellyfin-plugin-tunein with jellyfin
2. Find and open a station that uses the .pls playlist format
3. Doesn't play, check logs
4. See NullReferenceException error

**Expected behavior**
null value should be handled gracefully, similar to above lines of code

**Logs**
Stack trace from log:
```
[2019-02-12 00:05:10.657 +00:00] [INF] FILE : 2 - http://live-radio02.mediahubaustralia.com/3LRW/mp3/
[2019-02-12 00:05:10.658 +00:00] [INF] FILE : 2 - http://live-radio02.mediahubaustralia.com/3LRW/mp3/
[2019-02-12 00:05:10.775 +00:00] [INF] User policy for "testing". EnableAudioPlaybackTranscoding: True
[2019-02-12 00:05:10.792 +00:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "http://live-radio02.mediahubaustralia.com/3LRW/aac/"
[2019-02-12 00:05:10.802 +00:00] [ERR] Error processing request
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Model.Dlna.StreamBuilder.BuildAudioItem(MediaSourceInfo item, AudioOptions options) in /repo/MediaBrowser.Model/Dlna/StreamBuilder.cs:line 299
   at MediaBrowser.Model.Dlna.StreamBuilder.BuildAudioItem(AudioOptions options) in /repo/MediaBrowser.Model/Dlna/StreamBuilder.cs:line 47
   at MediaBrowser.Api.Playback.MediaInfoService.SetDeviceSpecificData(BaseItem item, MediaSourceInfo mediaSource, DeviceProfile profile, AuthorizationInfo auth, Nullable`1 maxBitrate, Int64 startTimeTicks, String mediaSourceId, Nullable`1 audioStreamIndex, Nullable`1 subtitleStreamIndex, Nullable`1 maxAudioChannels, String playSessionId, Guid userId, Boolean enableDirectPlay, Boolean forceDirectPlayRemoteMediaSource, Boolean enableDirectStream, Boolean enableTranscoding, Boolean allowVideoStreamCopy, Boolean allowAudioStreamCopy) in /repo/MediaBrowser.Api/Playback/MediaInfoService.cs:line 497
   at MediaBrowser.Api.Playback.MediaInfoService.SetDeviceSpecificData(Guid itemId, PlaybackInfoResponse result, DeviceProfile profile, AuthorizationInfo auth, Nullable`1 maxBitrate, Int64 startTimeTicks, String mediaSourceId, Nullable`1 audioStreamIndex, Nullable`1 subtitleStreamIndex, Nullable`1 maxAudioChannels, Guid userId, Boolean enableDirectPlay, Boolean forceDirectPlayRemoteMediaSource, Boolean enableDirectStream, Boolean enableTranscoding, Boolean allowVideoStreamCopy, Boolean allowAudioStreamCopy) in /repo/MediaBrowser.Api/Playback/MediaInfoService.cs:line 335
   at MediaBrowser.Api.Playback.MediaInfoService.GetPlaybackInfo(GetPostedPlaybackInfo request) in /repo/MediaBrowser.Api/Playback/MediaInfoService.cs:line 197
   at MediaBrowser.Api.Playback.UniversalAudioService.GetUniversalStream(GetUniversalAudioStream request, Boolean isHeadRequest) in /repo/MediaBrowser.Api/Playback/UniversalAudioService.cs:line 254
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task) in /repo/Emby.Server.Implementations/Services/ServiceExec.cs:line 110
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/Services/ServiceHandler.cs:line 95
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 608
```

**Screenshots**
N/A

**System (please complete the following information):**
 - OS: Docker container (boot2docker)
 - Browser: Chrome
 - Jellyfin Version: built from master branch, commit eb4b705

**Additional context**

### PR DESCRIPTION
**Pull request by WillWill56**
**Changes**
Added in a missing null-conditional operator (?) to prevent a NullReferenceException from being thrown.

**Issues**
Fixes #871

### CODE REVIEW

**Comment by WillWill56** [comment]
Oh whoops, how should I do that?

Yeah, seems like working on a buggy plugin is the main reason I found this bug, will probably have to fix something related to this in the tunein plugin very soon.

**Comment by JustAMan** [comment]
> Oh whoops, how should I do that?

https://jellyfin.readthedocs.io/en/latest/contributor-docs/contributing-code/#contributorsmd

**Comment by WillWill56** [comment]
Guess I missed that. Include the change in this pull request?

**Comment by JustAMan** [comment]
Either in this one or in another about HttpClient, whatever suits you more.

**Pull request merged**
