### PR TITLE
Master 10.0.0

### PR DESCRIPTION
**Pull request by joshuaboniface**
Integrates the latest changes from `dev` into `master`. Release tagged 10.0.0. Debian build 10.0.0-1.

#### Pull Requests

#283 #285 #286 #307 #330 #332 #334 #336 #338 #343 
#344 #348 #349 #353 #354 #356 #357 #358 #360 #361 
#362 #364 #365 #371 #372 #374 #373 #378 #381 #382 
#383 #384 #385 #386 #389 #390 #391 #392 #393 #394 
#396 #399 #407 #409 #411 #427 #428 #430 #434 #435 
#436 #437 #438 #440 #441 #444 #447 #450 #456 #457 
#460 #461 #462 #466 #467 #468 #469 #471 #472 #473

### CODE REVIEW

**Comment by hawken93** [comment]
Just want to add that f4132bb1bed961ef7754a7507837e5cb890f0dc6 has the consequence of requiring modules to be recompiled (If they have any logging). If this needs to go in documentation, I think this would be the time :)

**Comment by joshuaboniface** [comment]
@hawken93 Which modules?

**Comment by joshuaboniface** [comment]
Hrm, OK, we'll need some build instructions written up for those, since I'm not sure if we have any facilities to recompile them. @Bond-009 Maybe we can hotfix to keep it compatible for now?

**Comment by joshuaboniface** [comment]
Testing so far looks good - no obvious regressions or issues (with #440 and #444 applied) from web and Chromecast.

**Comment by JustAMan** [comment]
### Changelog based on referenced pull requests

* Rebranding completed - new colors, new logo, fixed links.
* Extensive code cleanup, should probably have some minor performance improvements. Also lots of warnings got fixed.
* Switched to Serilog for logging, now logs should be more readable and less of a bottleneck (they're written asyncronously now). Logging is now configurable and goes to proper `/var/log/jellyfin` for Debian packages.
* Removed lots of remaining phoning home (includes check for update and for news) which cluttered logs with errors. Reduced verbosity of default ffmpeg logging.
* Fixed support for clients requesting AAC to be downsampled to stereo from 5.1, needed to support some Chromecast use cases.
* Fixed XmlTv access error, removed Premiere nag in XmlTv access.
* Re-enabled UDP auto-discovery of Jellyfin server by clients that support that on LAN; added proper license for the project used for this auto-discovery.
* Fixed library access and device list access by a non-admin user if admin user previously didn't visit the pages.
* Stopped downloading fonts during runtime.
* Default theme is set to dark for admin pages and first setup.
* Fixed some DLNA casting issues.
* Docker images now bundle `ffmpeg 4.0.3` and are made smaller and faster to rebuild.
* Dropped ImageMagick and Drawing.Net in favor of leaving only Skia for image processing. **Note**: so far no Skia dotnet bindings exist for ARM.
* Language files were cleaned of unused strings; Danish translation was improved.
* SMB support in application was removed - Jellyfin won't load files over SMB protocol, one should properly mount a share using OS mechanism instead.
* Removed Connect in UI as it requires centralized service which Jellyfin doesn't intend to implement.
* Debian source tarballs are made smaller.
* Documentation moved to https://jellyfin.readthedocs.io/en/latest/

**Pull request merged**
