### PR TITLE
It60 2019 marina

### PR DESCRIPTION
**Pull request by marinacvijetic**
**Changes**

**Issues**

### CODE REVIEW

**Comment by crobibero** [comment]
What is this PR trying to accomplish?

**Comment by marinacvijetic** [comment]
> What is this PR trying to accomplish?

Hi, this changes are required for SonarCloud issues, I work on this project as a student

**Comment by joshuaboniface** [comment]
@marinacvijetic This PR is not acceptable. It does not follow any of our contribution guidelines and is not clear and useful. Please refrain from making any more such PRs, and please inform others in your group(s) not to do so either (i.e. anyone working on the URIS-2022 fork).

**Comment by marinacvijetic** [comment]
@joshuaboniface i made this pull request by mistake, i'm beginner, just learning how to use github.

**Pull request closed without merging**
