### PR TITLE
Do HEAD request to get content type instead of checking for extension

### PR DESCRIPTION
**Pull request by Bond-009**
Possible fix for  #8756

### CODE REVIEW

**Review by crobibero — APPROVED** [review]

**Comment by ajb142** [comment]
could a log point similar to below be added to help catch non successful response codes:
```
// Response stream is disposed manually.
var response = await _httpClientFactory.CreateClient(NamedClient.Default)
    .GetAsync(url, HttpCompletionOption.ResponseHeadersRead, CancellationToken.None)
    .ConfigureAwait(false);

if (!response.IsSuccessStatusCode)
{
    Logger.LogError("Error opening {StreamType} Live stream from {Url}. Status code {StatusCode}", typeName, url, response.StatusCode);
}
```
I think there are still error cases that users will be able to fix themselves, such as auth issues.

**Comment by Bond-009** [comment]
Maybe this doesn't fix it 100% but it does look like progress from a FileNotFoundException

**Comment by AxelTheGerman** [comment]
Yes and no, somehow this new "Zero bytes" is not just for recordings but also Live TV - which did work before 😖 

But hoping this is a step in the right direction of fixing both ❤️ thank you @Bond-009

**Comment by AxelTheGerman** [comment]
Just to try doing my part on this - 2 thoughts

### 1. HEAD request

If we **only** do a HEAD request, it makes sense that we get "Zero bytes copied" - we still need to make a proper GET request after determining the content type right?

### 2. Content-Type for HEAD request

I did a HEAD request via cURL to my provider and it still seems wrong, not sure how redirect/head/content-type are supposed to behave together.

<details>
<summary>Making a GET request without following redirect returns `text/html`</summary>

```
$ curl -v https://server.com/123/abc/456
*   Trying 172.64.80.1:443...
* Connected to server.com (172.64.80.1) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=*.server.com
*  start date: Oct 24 01:11:06 2022 GMT
*  expire date: Jan 22 02:08:34 2023 GMT
*  subjectAltName: host "server.com" matched cert's "server.com"
*  issuer: C=US; O=Google Trust Services LLC; CN=GTS CA 1P5
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* h2h3 [:method: GET]
* h2h3 [:path: /123/abc/456]
* h2h3 [:scheme: https]
* h2h3 [:authority: server.com]
* h2h3 [user-agent: curl/7.84.0]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x13b811e00)
> GET /123/abc/456 HTTP/2
> Host: server.com
> user-agent: curl/7.84.0
> accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
< HTTP/2 302 
< date: Tue, 06 Dec 2022 14:20:28 GMT
< content-type: text/html; charset=UTF-8
< location: http://169.150.236.74:80/auth/fH1MZqMv8sMs_x3UuACEKld4r7GQSFTLGuDm4RKrzJIrT8a-MPAl67aXnmbS8GBJ5ptPRaTkXjF1e0KnX1epvcHXaP_DRyz6LKiMldzacD1HOVHZJM_Ei7kqWbpke1EnHAdk96DDXHb5ymBtXJWENH8xqpryudnA8-mG4PFzecddNNKLyDoWBdpDmRzAvQGcIlXilOswPnyK7AI3HAsHJKyHdELzcumALLO2O-m_7yf9wISdtXZb9KMeoXYFGD3MpzvXZD_3-TwRvAbNsgNYIl8rrH3iFivpzAEuRm5tAO8OomlqAuDy_w_U7GMrv3CaVEbK8Lue9H-dmb0sSbcj2p8ebrHF11_94YLAe8BZoMUd5E7rOrTe7-o7rafQzJyGZxHY-KQID4Zym4MLlnfmlM5XfwBmeoz4pTZIHsQAnJGcPq4Efb4fv_it9RBwgMxRQWvlrv86Dlb0Xmnm1gjKm3C5uHdr5YIb44ug4-8cAPifToWovENnbsHvkSkQWHBooviANzVtCGVcDQr5164XXh8HQdNbUvC5z5aYbxWOTn_e18hOwNE6dPExBWlwhMif7mS3ypLksGbH0sImljB7YkR3Zf9fuYnZ5hbL4_TmkhVoiTs8lqxnXkeso-V49AOX-Pp8fXpFupDAbtnPKvEMEhh32ze5cd0bs3Vnn2r-bNoYRP5KStrTQrt3TfX2xIbIrh9YT12d4POJepVX7g8Dvw
< cache-control: no-store, no-cache, must-revalidate
< access-control-allow-origin: *
< cf-cache-status: DYNAMIC
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=4eFRznC%2F9vJeqtlI4yaPN4h8MmNBaJ6Y2UnMmTQkJSI8xT6dsaqkkVRKPvyc0taoN5folU7jethOY4YxKMfNbO4jfsZ5OAGVzkzNdLXOHpx2AIvwYwjbkZmBv8SqjNjIUqqZ"}],"group":"cf-nel","max_age":604800}
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< server: cloudflare
< cf-ray: 7755a99639c3a22f-YYZ
< alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
< 
* Connection #0 to host server.com left intact
```

</details>

<details>
<summary>Making a GET request WITH following redirect returns `text/html` and then `video/mp2t`</summary>

```
$ curl -v -L https://server.com/123/abc/456
*   Trying 172.64.80.1:443...
* Connected to server.com (172.64.80.1) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=*.server.com
*  start date: Oct 24 01:11:06 2022 GMT
*  expire date: Jan 22 02:08:34 2023 GMT
*  subjectAltName: host "server.com" matched cert's "server.com"
*  issuer: C=US; O=Google Trust Services LLC; CN=GTS CA 1P5
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* h2h3 [:method: GET]
* h2h3 [:path: /123/abc/456]
* h2h3 [:scheme: https]
* h2h3 [:authority: server.com]
* h2h3 [user-agent: curl/7.84.0]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x14d813400)
> GET /123/abc/456 HTTP/2
> Host: server.com
> user-agent: curl/7.84.0
> accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
< HTTP/2 302 
< date: Tue, 06 Dec 2022 14:22:18 GMT
< content-type: text/html; charset=UTF-8
< location: http://169.150.236.74:80/auth/fH1MZqMv8sMs_x3UuACEKld4r7GQSFTLGuDm4RKrzJIrT8a-MPAl67aXnmbS8GBJ5ptPRaTkXjF1e0KnX1epvcHXaP_DRyz6LKiMldzacD1HOVHZJM_Ei7kqWbpke1EnHAdk96DDXHb5ymBtXJWENH8xqpryudnA8-mG4PFzecddNNKLyDoWBdpDmRzAvQGcIlXilOswPnyK7AI3HAsHJKyHdELzcumALLO2O-m_7yf9wISdtXZb9KMeoXYFGD3MpzvXZD_3-TwRvAbNsgNYIl8rrH3iFivpzAEuRm5tAO8OomlqAuDy_w_U7GMrv3CaVEbK8Lue9H-dmb0sSbcj2p8ebrHF11_94YLAe8BZoMUd5E7rOrTe7-o7rafQzJyGZxHY-KQID4Zym4MLlnfmlM5XfwBmeoz4pTZIHsQAnJGcPq4Efb4fv_it9RBwgMxRQWvlrv86Dlb0Xmnm1gjKm3C5uHdr5YIb44ug4-8cAPicF5mqmvA3u5FkrQKAqKioFlRFkP2I_d5VlkTXOGhOf1js1ozMaPDmfTcPZSk7imeN5oRWHXQ7K5mMnmriiQCTBOlDfbpTkrcR_DJZZ0AorzLbL7ef1MAps4F4ODUrRiSKJP-qOI87D_0LddO9F9BrncwmJbRpE69yrBr_6b1JJAjcdIHqlZTcdiNs2yjwr11-U7srwba1skpYedKkyPiAscc41PhDp333HF8CilK6ow
< cache-control: no-store, no-cache, must-revalidate
< access-control-allow-origin: *
< cf-cache-status: DYNAMIC
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=E7B9ok2YGqGZnbcZWx2CdkXSS8mjOA5pyadazwTtTZN29zi9GUn9BnS7NZ0dbqQdEXiJgaRMnmxkOb2dobMgvyekGbEbCbIdf82FBvKxqiRwBOqL%2BuR9QcGDsZ02%2BeG9jhPx"}],"group":"cf-nel","max_age":604800}
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< server: cloudflare
< cf-ray: 7755ac471f085413-YYZ
< alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
< 
* Connection #0 to host server.com left intact
* Clear auth, redirects to port from 443 to 80
* Issue another request to this URL: 'http://169.150.236.74:80/auth/fH1MZqMv8sMs_x3UuACEKld4r7GQSFTLGuDm4RKrzJIrT8a-MPAl67aXnmbS8GBJ5ptPRaTkXjF1e0KnX1epvcHXaP_DRyz6LKiMldzacD1HOVHZJM_Ei7kqWbpke1EnHAdk96DDXHb5ymBtXJWENH8xqpryudnA8-mG4PFzecddNNKLyDoWBdpDmRzAvQGcIlXilOswPnyK7AI3HAsHJKyHdELzcumALLO2O-m_7yf9wISdtXZb9KMeoXYFGD3MpzvXZD_3-TwRvAbNsgNYIl8rrH3iFivpzAEuRm5tAO8OomlqAuDy_w_U7GMrv3CaVEbK8Lue9H-dmb0sSbcj2p8ebrHF11_94YLAe8BZoMUd5E7rOrTe7-o7rafQzJyGZxHY-KQID4Zym4MLlnfmlM5XfwBmeoz4pTZIHsQAnJGcPq4Efb4fv_it9RBwgMxRQWvlrv86Dlb0Xmnm1gjKm3C5uHdr5YIb44ug4-8cAPicF5mqmvA3u5FkrQKAqKioFlRFkP2I_d5VlkTXOGhOf1js1ozMaPDmfTcPZSk7imeN5oRWHXQ7K5mMnmriiQCTBOlDfbpTkrcR_DJZZ0AorzLbL7ef1MAps4F4ODUrRiSKJP-qOI87D_0LddO9F9BrncwmJbRpE69yrBr_6b1JJAjcdIHqlZTcdiNs2yjwr11-U7srwba1skpYedKkyPiAscc41PhDp333HF8CilK6ow'
*   Trying 169.150.236.74:80...
* Connected to 169.150.236.74 (169.150.236.74) port 80 (#1)
> GET /auth/fH1MZqMv8sMs_x3UuACEKld4r7GQSFTLGuDm4RKrzJIrT8a-MPAl67aXnmbS8GBJ5ptPRaTkXjF1e0KnX1epvcHXaP_DRyz6LKiMldzacD1HOVHZJM_Ei7kqWbpke1EnHAdk96DDXHb5ymBtXJWENH8xqpryudnA8-mG4PFzecddNNKLyDoWBdpDmRzAvQGcIlXilOswPnyK7AI3HAsHJKyHdELzcumALLO2O-m_7yf9wISdtXZb9KMeoXYFGD3MpzvXZD_3-TwRvAbNsgNYIl8rrH3iFivpzAEuRm5tAO8OomlqAuDy_w_U7GMrv3CaVEbK8Lue9H-dmb0sSbcj2p8ebrHF11_94YLAe8BZoMUd5E7rOrTe7-o7rafQzJyGZxHY-KQID4Zym4MLlnfmlM5XfwBmeoz4pTZIHsQAnJGcPq4Efb4fv_it9RBwgMxRQWvlrv86Dlb0Xmnm1gjKm3C5uHdr5YIb44ug4-8cAPicF5mqmvA3u5FkrQKAqKioFlRFkP2I_d5VlkTXOGhOf1js1ozMaPDmfTcPZSk7imeN5oRWHXQ7K5mMnmriiQCTBOlDfbpTkrcR_DJZZ0AorzLbL7ef1MAps4F4ODUrRiSKJP-qOI87D_0LddO9F9BrncwmJbRpE69yrBr_6b1JJAjcdIHqlZTcdiNs2yjwr11-U7srwba1skpYedKkyPiAscc41PhDp333HF8CilK6ow HTTP/1.1
> Host: 169.150.236.74
> User-Agent: curl/7.84.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: nginx
< Date: Tue, 06 Dec 2022 14:22:18 GMT
< Content-Type: video/mp2t
< Connection: close
< Access-Control-Allow-Origin: *
< 
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
* Failure writing output to destination
* Closing connection 1
```

</details>


<details>
<summary>Making a HEAD request returns `application/octet-stream`</summary>

I assume this might be because without the redirect, the server doesn't know the content type yet?

```
$ curl -v --head https://server.com/123/abc/456
*   Trying 172.64.80.1:443...
* Connected to server.com (172.64.80.1) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=*.server.com
*  start date: Oct 24 01:11:06 2022 GMT
*  expire date: Jan 22 02:08:34 2023 GMT
*  subjectAltName: host "server.com" matched cert's "server.com"
*  issuer: C=US; O=Google Trust Services LLC; CN=GTS CA 1P5
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* h2h3 [:method: HEAD]
* h2h3 [:path: /123/abc/456]
* h2h3 [:scheme: https]
* h2h3 [:authority: server.com]
* h2h3 [user-agent: curl/7.84.0]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x12600c600)
> HEAD /123/abc/456 HTTP/2
> Host: server.com
> user-agent: curl/7.84.0
> accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
< HTTP/2 200 
HTTP/2 200 
< date: Tue, 06 Dec 2022 14:23:38 GMT
date: Tue, 06 Dec 2022 14:23:38 GMT
< content-type: application/octet-stream
content-type: application/octet-stream
< content-length: 0
content-length: 0
< cf-cache-status: DYNAMIC
cf-cache-status: DYNAMIC
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=7Kqrwy%2FKV2ol2JzXPJYBncmvvFooQ%2FSo81fYXhDiDacwXGkyb%2FxGVGo32EnnqbBjxDEkthanjUTI75PIF799tTFyB7ZTBxaaLVRd0cFhzhzq57S4ZeSme%2B4SOjN0eXwexeWS"}],"group":"cf-nel","max_age":604800}
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=7Kqrwy%2FKV2ol2JzXPJYBncmvvFooQ%2FSo81fYXhDiDacwXGkyb%2FxGVGo32EnnqbBjxDEkthanjUTI75PIF799tTFyB7ZTBxaaLVRd0cFhzhzq57S4ZeSme%2B4SOjN0eXwexeWS"}],"group":"cf-nel","max_age":604800}
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< server: cloudflare
server: cloudflare
< cf-ray: 7755ae3b9e2ac42c-EWR
cf-ray: 7755ae3b9e2ac42c-EWR
< alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400

< 
* Connection #0 to host server.com left intact
```

</details>

It looks like my provider is simply running Cloudflare (HTTPS) in front of their streaming (HTTP) to protect from DDOS and implement their authentication somehow.

I doubt they'll "fix" the HTTPS->HTTP redirect.

If there's anything else I can do to support this issue or the project in general, please do let me know!

**Comment by AxelTheGerman** [comment]
And re following redirect, there is a - https://github.com/jellyfin/jellyfin/issues/8756#issuecomment-1336185217 - in the original issue about dotnet not following HTTPS->HTTP redirects by design (which makes sense in most cases). Unfortunately there is no flag to allow it and we'd have to check the location header ourselves and make a second request 😞

**Comment by Bond-009** [comment]
> If we only do a HEAD request, it makes sense that we get "Zero bytes copied" - we still need to make a proper GET request after determining the content type right?

Yes, that's what this does, the head request is only for getting the content type.

> I did a HEAD request via cURL to my provider and it still seems wrong

You should also follow redirects with your head request

> Unfortunately there is no flag to allow it and we'd have to check the location header ourselves and make a second request 

Yeah, it seems like we'll have to do it manually

**Review by Shadowghost — APPROVED** [review]

**Pull request merged**
