### PR TITLE
Fix unit test RecordingHelperTests.GetRecordingName_Success.

### PR DESCRIPTION
**Pull request by Dixin**
**Changes**
The string representation of the date should be local.

### CODE REVIEW

**Review by Bond-009 — CHANGES_REQUESTED** [review]
IMO a better solution would be setting `DateTimeKind` to `Local` for `OriginalAirDate` in the test data

**Comment by Dixin** [comment]
> IMO a better solution would be setting `DateTimeKind` to `Local` for `OriginalAirDate` in the test data

Thanks. IMO it is better to have non-local date in the test data, and verify the result and see if the test data has been successfully converted to local date.

**Comment by Bond-009** [comment]
I would make that a separate test instead of cramming it in this one, the parsing, converting and formatting isn't really the cleanest solution

**Comment by Dixin** [comment]
> I would make that a separate test instead of cramming it in this one, the parsing, converting and formatting isn't really the cleanest solution

I updated the code to have a DateTime instance and only calls ToLocalTime(), which is the same as RecordingHelper.GetRecordingName().

**Comment by Bond-009** [comment]
#6900

**Pull request closed without merging**
