### PR TITLE
Use the "legacy" AuthenticationException in AuthService

### LINKED ISSUE #3290: AuthenticationException Returning 500
**Describe the bug**
According to a user post on the Yatse forums, they are unable to use Yatse to log in to Jellyfin 10.6 Nightlies. It appears the app is receiving a 500 for an authentication error, instead of a 401.

**System (please complete the following information):**
 - OS: uncertain, likely Windows
 - Virtualization: unknown
 - Clients: Yatse
 - Jellyfin Version: master as of June 9th
 - Reverse Proxy: unknown, likely none
 - Base URL: unknown
 - Networking: Presumed local IP

**To Reproduce**
See Yatse post: https://community.yatse.tv/t/yatse-cant-connect-to-jellyfin-nightly-built-from-source/2719?u=anthonylavado

**Expected behavior**
Jellyfin should return a 401 for an authentication exception.

**Additional context**
It looks like we already return 401 for authentication issues? 

https://github.com/jellyfin/jellyfin/blame/998d5674a2bf82c6f83b566a2acfd8aadad59ab9/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs#L198-L212

### PR DESCRIPTION
**Pull request by cvium**
**Changes**
Changed the import to the "legacy" Emby AuthenticationException instead of the System one.

**Issues**
Fixes #3290

### CODE REVIEW

**Comment by crobibero** [comment]
Probably should also add `case System.Security.Authentication.AuthenticationException _: return 401;` to `HttpListenerHost L204`

**Comment by cvium** [comment]
I don't think it makes sense to use both. If the plan is to migrate to ASP.NET, then we shouldn't use the old AuthenticationException and the old RequestHandler.

**Comment by crobibero** [comment]
The exception commented at the yatse error specifically had `System.Security.Authentication.AuthenticationException`

**Comment by crobibero** [comment]
Sorry I hit the wrong button as usual

**Pull request merged**
