### PR TITLE
Fix warnings for MediaBrowser.Controller/Providers directory

### PR DESCRIPTION
**Pull request by richlander**
Supports #2149

### CODE REVIEW

**Comment by richlander** [comment]
Please re-start the devops pipeline. It looks like it failed due to downloading the .NET SDK (404).

**Comment by richlander** [comment]
Still failing due to the same 404. I've asked my team what is up.

**Comment by richlander** [comment]
Looks like there is an outage on the .NET SDK download server. Ouch!!! Folks are looking at resolving it.

**Comment by richlander** [comment]
Odd question. Is the DevOps account for this project in a particular region? We're trying to root cause this outage and wondering if it is region-specific.

**Comment by anthonylavado** [comment]
> Odd question. Is the DevOps account for this project in a particular region? We're trying to root cause this outage and wondering if it is region-specific.

The original team member that set it up for us is in Europe, and so it is in Europe as well.

**Comment by nielsvanvelzen** [comment]
I've asked in our team chat and it should be in (West?) Europe.

**Comment by richlander** [comment]
Can you re-try the pipeline again? Our CDN provider just tried downloading from London and got a 200 response.

**Comment by richlander** [comment]
Sorry for this back and forth. Can you try again? Our provider made another change. In any case, this is helping.

**Review by crobibero — APPROVED** [review]

**Comment by richlander** [comment]
FYI: No resolution on the .NET SDK 404s. The CDN folks are still investigating. I hope it is resolved soon.

**Review by Bond-009 — APPROVED** [review]

**Pull request merged**
