### PR TITLE
add new projects to the solution file and fix docker build step

### PR DESCRIPTION
**Pull request by dkanada**
I think this version is working, ran the build on docker and it passed. It seems like targeting several frameworks is somewhat broken in certain dev environments, so I removed Mono as a target framework and moved both libraries to the ThirdParty folder.

### CODE REVIEW

**Comment by BnMcG** [comment]
This seems to bring the whole taglib-sharp repository into Jellyfin, rather than including via a submodule. In my opinion, this solution would require work to maintain than just forking taglib-sharp into the Jellyfin organisation, and looks like it will significantly increase the size of the (already large) Jellyfin repo (it looks like there are AVI files and other binaries as part of the taglib-sharp repo).

**Comment by dkanada** [comment]
Forking taglib-sharp is also an option, I just wanted to get a solution finished so there could be a discussion about it. If someone adds a fork and removes the mono target I can remove that commit.

**Comment by JustAMan** [comment]
I think @nvllsvm wanted to look into that problem with taglib...

**Comment by nvllsvm** [comment]
We are not forking a third-party repository directly into the Jellyfin repository. If we **need** a fork, we should have a separate repository and include a reference in here as a submodule.

**Comment by dkanada** [comment]
I agree, we shouldn't do that. I was just trying to show one possible solution, I could have removed that commit since we can at least fix ImageMagickSharp right now. That should also be moved to a submodule probably though.

**Pull request closed without merging**
