### PR TITLE
Fix #7147: Don't return subtitles in mismatched format

### LINKED ISSUE #7147: [Issue]: API returns subtitles when requesting invalid formats
### Please describe your bug

http://localhost:8096/Videos/{itemid}/{mediasourceid}/Subtitles/{subtitleindex}/Stream.{format}

If API request for subtitles is made with valid options, except for format, JF currently returns the requested subtitle stream as Stream.{format}. Invalid {format} would be a format that JF can't convert to, or one that the subtitle file is not already in.

Example:
external subtitle format on disk. `Movie.en.srt`
subtitle stream request `Stream.notaformat`
currently returns a file named `Stream.notaformat` with contents of `Movie.en.srt`

This could cause issues because one format could be requested, and the return file could be a different format.
Example:
external subtitle format on disk. `Movie.en.srt`
subtitle stream request `Stream.ssa` - There is currently not a SSA subtitle writer in JF
would return a file named `Stream.ssa` with contents in SRT format.

Proposed solution:
Don't return result if can't convert, or return matching existing file.

### Jellyfin Version

10.7.7

### if other:

and 10.8.0

### Environment

```markdown
- OS: Windows
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

_No response_

### FFmpeg logs

_No response_

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by SenorSmartyPants**
**Changes**
Don't return subtitles of one format in a file with the wrong extension.

**Issues**
Fixes #7147

### CODE REVIEW

**Comment by crobibero** [comment]
I haven't tested this, but my assumption is that an exception is thrown down the line and the api returns a 500 status?

**Comment by SenorSmartyPants** [comment]
No API error that I could make happen. A subtitle file is returned with whatever extension you feed in, provided other inputs are valid.

**Comment by SenorSmartyPants** [comment]
> assumption is that an exception is thrown down the line and the api returns a 500 status?

If you're asking me what the behavior is after my fix, It returns a 400 bad request.

**Review by crobibero — APPROVED** [review]

**Review by cvium — APPROVED** [review]
This could do with a test in `SubtitleEncoderTests`

**Comment by SenorSmartyPants** [comment]
> This could do with a test in `SubtitleEncoderTests`

I haven't done xunit tests before, and I'm not quite sure how to set up a test for this. This is as far as I got. I don't know how to add test mediastreams to a video.

```
        internal static TheoryData<BaseItem, string, int, string, long, long, bool, CancellationToken> GetReadableFile_Invalid_TestData()
        {
            var data = new TheoryData<BaseItem, string, int, string, long, long, bool, CancellationToken>();

            // BaseItem item, string mediaSourceId, int subtitleStreamIndex, string outputFormat, long startTimeTicks, long endTimeTicks, bool preserveOriginalTimestamps, CancellationToken cancellationToken
            // xyz format is not a subtitle format

            data.Add(
                new Video()
                {
                    Id = new System.Guid("f0dcdead45730b8ea584b5548e92b239")
                    // add subtitle stream, how?
                },
                "f0dcdead45730b8ea584b5548e92b239",
                0,
                "xyz",
                0,
                0,
                false,
                new CancellationToken(false));

            return data;
        }

        [Theory]
        [MemberData(nameof(GetReadableFile_Invalid_TestData))]
        internal async Task GetReadableFile_Invalid_Failure(BaseItem item, string mediaSourceId, int subtitleStreamIndex, string outputFormat, long startTimeTicks, long endTimeTicks, bool preserveOriginalTimestamps, CancellationToken cancellationToken)
        {
            var fixture = new Fixture().Customize(new AutoMoqCustomization { ConfigureMembers = true });
            var subtitleEncoder = (ISubtitleEncoder)fixture.Create<SubtitleEncoder>();
            var result = await subtitleEncoder.GetSubtitles(item, mediaSourceId, subtitleStreamIndex, outputFormat, startTimeTicks, endTimeTicks, preserveOriginalTimestamps, cancellationToken).ConfigureAwait(false);
/*
            Assert.Equal(subtitleInfo.Path, result.Path);
            Assert.Equal(subtitleInfo.Protocol, result.Protocol);
            Assert.Equal(subtitleInfo.Format, result.Format);
            Assert.Equal(subtitleInfo.IsExternal, result.IsExternal); */
        }
```

**Review by Bond-009 — APPROVED** [review]

**Pull request merged**
