### PR TITLE
Fix multiple FLAC HTTP Live Streaming issues

### LINKED ISSUE #10066: HLS playback of flac fails
I will fix this issue, this is just for documentation purposes.

**Media Info of the file**
I am trying to play a flac file via HLS. The stream url is:
`http://10.42.0.8:8096/Audio/3198271856ada5b30715a35643a3fb97/master.m3u8?audioCodec=flac&apiKey=...&segmentContainer=mp4&playSessionId=123456&mediaSourceId=3198271856ada5b30715a35643a3fb97`

Jellyfin generates following master playlist:
```m3u8
#EXTM3U
#EXT-X-STREAM-INF:BANDWIDTH=1044269,AVERAGE-BANDWIDTH=1044269,CODECS="flac"
main.m3u8?audioCodec=flac&apiKey=...&segmentContainer=mp4&playSessionId=123456&mediaSourceId=3198271856ada5b30715a35643a3fb97
```

Playback in VLC fails. See the FFmpeg log below. As you can see, ffmpeg expects `-strict -2` to support flac in mp4 containters. By replacing `audioCodec=flac` with `static=true` it can be tricked into doing what we want. VLC then is able to play the file.

On iOS however, playback still fails. Plucking the URL into mediastreamvalidator (Apple HLS Tools) shows:
```
--------------------------------------------------------------------------------
MUST fix issues
--------------------------------------------------------------------------------

Error: Unrecognized codec
--> Detail:  Codec: flac
```

Checking [Apples documentation on HLS](https://developer.apple.com/documentation/http-live-streaming/hls-authoring-specification-for-apple-devices-appendixes#Values-for-the-CODECS-attribute) reveals that iOS expects "fLaC" instead of "flac".

**FFmpeg Logs**
```
ffmpeg version 5.1.3-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libsvtav1 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, flac, from 'file:/mnt/Media/Music/....flac':
  Metadata:
    ...
  Duration: 00:01:34.97, start: 0.000000, bitrate: 1044 kb/s
  Stream #0:0: Audio: flac, 44100 Hz, stereo, s16
    Side data:
      replaygain: track gain - -8.440000, track peak - 0.000023, album gain - -9.420000, album peak - 0.000023, 
Stream mapping:
  Stream #0:0 -> #0:0 (flac (native) -> flac (native))
Press [q] to stop, [?] for help
[hls @ 0x562f08321cc0] Opening '/cache/transcodes/e1fa3dee63e48f3af9228c2e2799d3e1-1.mp4' for writing
[mp4 @ 0x562f08370640] flac in MP4 support is experimental, add '-strict -2' if you want to use it.
Could not write header for output file #0 (incorrect codec parameters ?): Experimental feature
Error initializing output stream 0:0 -- 
Conversion failed!
```

**Server System (please complete the following information):**
 - OS: Docker on Debian
 - Jellyfin Version: 10.8.10 & master
 - Reverse proxy: no
 
**Client System (please complete the following information):**
 - Device: MacBook Pro
 - OS: macOS
 - Client: VLC & Apple AVFoundation AVPlayer

### PR DESCRIPTION
**Pull request by lonebyte**
**Changes**
- [Fix the fLaC/flac HLS issue also for audio-only](https://github.com/jellyfin/jellyfin/commit/e9f23c61c937b230b1d3bd7865a083aeb3d51657)
- [Correct the HLS Opus codec string](https://github.com/jellyfin/jellyfin/commit/19fb061381dd107d5e0236cf9d8b59b2e2318130)
- [Allow flac inside mp4 for all HLS audio streams](https://github.com/jellyfin/jellyfin/commit/79cff704ff4e00895a8d2b97ecbbea3e2f5f56fc)

See the commit messages themselves for more details.

One discussion point is, whether the codec string capitalization hack is actually required. If I understand correctly, it was added to support ShakaPlayer with https://github.com/jellyfin/jellyfin/pull/8546. Maybe it should be fixed there, as the documentation is pretty clear about the codec field:
1. https://datatracker.ietf.org/doc/html/rfc8216#section-4.3.4.2
2. https://datatracker.ietf.org/doc/html/rfc6381#section-3.3
3. https://mp4ra.org/#/codecs

**Issues**
Fixes #10066

### CODE REVIEW

**Comment by nyanmisaka** [comment]
Before doing that, we'd better fix ShakaPlayer first. This will break [ShakaPlayer](https://shaka-player-demo.appspot.com/demo/) because only Apple AVPlayer can fallback to the 2nd entry of the HLS playlist.

Check out these places if you have time:
- https://github.com/shaka-project/shaka-player/blob/ace3e37241dc04f26e35a9d69639b083551e356d/lib/util/manifest_parser_utils.js#L187
- https://github.com/shaka-project/shaka-player/blob/ace3e37241dc04f26e35a9d69639b083551e356d/lib/util/stream_utils.js#L449-L457
- https://github.com/shaka-project/shaka-player/blob/ace3e37241dc04f26e35a9d69639b083551e356d/lib/util/stream_utils.js#L470-L480
- https://github.com/shaka-project/shaka-player/blob/ace3e37241dc04f26e35a9d69639b083551e356d/lib/util/stream_utils.js#L854-L864
- https://github.com/shaka-project/shaka-player/blob/ace3e37241dc04f26e35a9d69639b083551e356d/lib/media/media_source_engine.js#L224

**Comment by lonebyte** [comment]
@nyanmisaka This was quite the rabbit hole 😅. I provided a fix to ShakaPlayer: https://github.com/shaka-project/shaka-player/pull/5454

**Review by nyanmisaka — APPROVED** [review]
LGTM. Thank you for the contribution.

**Comment by lonebyte** [comment]
Don't merge this yet, I want to remove the workaround. Should I wait for a release of Shaka player that includes the fix? Or can I already remove it now?

**Review by Shadowghost — APPROVED** [review]

**Comment by nyanmisaka** [comment]
@lonebyte You can remove the workaround now and change the title to only fix the `-strict -2`.
I also send a patch to fix the capitalization issue for Hls.js, hopefully it will be merged soon.
See (https://github.com/jellyfin/jellyfin-web/pull/4762)

**Review by Bond-009 — APPROVED** [review]

**Review by nyanmisaka — CHANGES_REQUESTED** [review]

**Review by nyanmisaka — APPROVED** [review]

**Review by Bond-009 — APPROVED** [review]

**Comment by lonebyte** [comment]
Sorry, completely forgot about your change request. Thanks for taking over!

**Pull request merged**
