### PR TITLE
Remove ISocket abstraction layer

### PR DESCRIPTION
**Pull request by Bond-009**
Removed a layer from this lasagna

Testing in prod ATM....

### CODE REVIEW

**Comment by dkanada** [comment]
You should squash this or fix your commit messages :laughing: some of them are a bit lacking.

**Comment by Bond-009** [comment]
I'll get it working first :p
My TV doesn't want to play nice

**Comment by JustAMan** [comment]
@Bond-009 what makes it a draft?

**Comment by Bond-009** [comment]
Last time I tested this my DLNA broke

**Comment by BaronGreenback** [comment]
@Bond-009 Is this PR still live? I'm testing the rather large network change - which touches some of these files. Would seems stupid to have to test twice.

Is it worth me merging with this?

**Comment by BaronGreenback** [comment]
No longer required with network PR

**Pull request closed without merging**
