### PR TITLE
Fix backdrop image fetching to prioritize non-language images

### PR DESCRIPTION
**Pull request by bradbeattie**
# Context
#8946 accidentally introduced a side effect of all backdrop images preferring the explicit language of the library. The purpose of backdrop images should actually deprioritize language.

We could additionally modify `OrderByLanguageDescending`, but how this gets used with both manual image searches and during metadata refresh makes it a little slippery to refactor properly. The proposed solution here is fairly simple and gets us the behaviour we're looking for.

# Changes
Image sorting prioritizes non-language images for backdrop metadata refreshes.

### CODE REVIEW

**Comment by bradbeattie** [comment]
Hmmm. This PR works for explicitly searching for an image, but not for replacing metadata + images...

**Comment by bradbeattie** [comment]
Mixed feelings about the implementation approach, but happy with the resultant behaviour.

**Review by Shadowghost — APPROVED** [review]

**Comment by crobibero** [comment]
I think a better change for this is to update `DownloadMultiImages`:

```diff
- foreach (var image in images.Where(i => i.Type == imageType))
+ foreach (var image in images.OrderBy(i => string.IsNullOrWhiteSpace(i.Language)).Where(i => i.Type == imageType))
```

**Comment by bradbeattie** [comment]
> I think a better change for this is to update `DownloadMultiImages`:
> 
> ```diff
> - foreach (var image in images.Where(i => i.Type == imageType))
> + foreach (var image in images.OrderBy(i => string.IsNullOrWhiteSpace(i.Language)).Where(i => i.Type == imageType))
> ```

My concern with that change is that it binds `DownloadMultiImages` to specifically favour non-language images. True, it's only used for that purpose at the moment, but if `imageType` is an option, best to leave the sorting to calling function.

**Comment by crobibero** [comment]
Ok, I would still change the sort method to what I suggested

**Comment by bradbeattie** [comment]
Ah! So the intent behind `listWithNoLangFirst` is to say "I'll observe whatever ordering is defined in `OrderByLanguageDescending`, but otherwise prefer non-language images first". Because https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.Model/Extensions/EnumerableExtensions.cs#L19 might have complexity unknown to `listWithNoLangFirst`.

I'm unclear if C# ordering with `.OrderBy(i => string.IsNullOrWhiteSpace(i.Language))` will preserve the ordering of elements in its list that are equal in the lambda evaluation, but otherwise unique.

**Review by Bond-009 — APPROVED** [review]

**Pull request merged**
