### PR TITLE
Fix H264 preset option not working

### PR DESCRIPTION
**Pull request by nyanmisaka**
**Changes**
Fix H264 preset option not working in jellyfin-web.

**Issues**
Fixed: https://github.com/jellyfin/jellyfin-web/issues/539

### CODE REVIEW

**Comment by telans** [comment]
I'm not sure if the devs like commit squashing, but perhaps it should be done here?

**Comment by nyanmisaka** [comment]
> I'm not sure if the devs like commit squashing, but perhaps it should be done here?

Thanks for reminding.  I will commit in a better way in the future.

**Comment by dkanada** [comment]
Hmmm I suppose in that case we should drop this pull request and make the change in the web client.

**Comment by nyanmisaka** [comment]
> Hmmm I suppose in that case we should drop this pull request and make the change in the web client.

The relevant files in jellyfin-web are as follows: 
https://github.com/jellyfin/jellyfin-web/blob/master/src/encodingsettings.html
https://github.com/jellyfin/jellyfin-web/blob/master/src/controllers/encodingsettings.js

**Pull request closed without merging**
