### PR TITLE
Add newlines after closing braces (SA1513/SA1516)

### PR DESCRIPTION
**Pull request by telans**
**Changes**
Fixes SA1513/SA1516. Just used regex across all *.cs files.
Merge conflicts here we go 🚀

- -1947 warnings

Match:
`([\s]+\})\n( +)(?!catch|else|case|finally)([a-zA-Z_])([\/ \w]+)`

Replace:
```
$1

$2$3$4
```

**Issues**
#2149

### CODE REVIEW

**Comment by crobibero** [comment]
`finally` blocks don't need to be proceeded by a newline

**Comment by telans** [comment]
Oh yep you're right, thought I tested that. `warning SA1510: 'finally' statement should not be preceded by a blank line`

Fixed that and also caught SA1516

Down 1947 warnings now

**Comment by crobibero** [comment]
Looks like you caught some `do...while` loops

**Comment by telans** [comment]
rebased

**Pull request merged**
