### PR TITLE
Extras: Clean filename and process NFOs

### PR DESCRIPTION
**Pull request by SenorSmartyPants**
**Changes**

- Filenames are cleaned using CleanStrings regex
- new regex to remove extra suffixes
- NFOs for extras are now read

A file named `Interview with director-interview.mkv` will now be named `Interview with director` in JF.

NFO files named the same as extra file will be read for metadata.

### CODE REVIEW

**Review by Shadowghost — APPROVED** [review]

**Comment by SenorSmartyPants** [comment]
Any feedback on the unit test I changed? I'm not aware of which issues that might be related to, or if my change will affect them.

**Review by daullmer — APPROVED** [review]

**Comment by 1337joe** [comment]
> Any feedback on the unit test I changed? I'm not aware of which issues that might be related to, or if my change will affect them.

I added that test when I did some work on `ProviderManager` to ensure that behavior didn't change during my refactor. The check itself is from Emby, I just made the comment more relevant.

I've never used NFOs so I can't attest to the necessity of that check. I expect that if you're changing the behavior you've done some testing with various NFO and naming arrangements.

**Review by crobibero — COMMENTED** [review]
I think some tests for the new naming would be helpful, without doing much checking I think you can plug directly into `FindExtrasTests`

**Comment by SenorSmartyPants** [comment]
@crobibero Added one test of cleaning 3 extra names.

**Review by crobibero — APPROVED** [review]

**Pull request merged**
