### PR TITLE
Fix ArgumentNullException in DLNA streams

### PR DESCRIPTION
**Pull request by cvium**
Fixes the crash in https://gist.github.com/LeoVerto/98f6fd9f2a187e60a0a458c9f50bb507

Not sure if it's enough.

### CODE REVIEW

**Comment by LeoVerto** [comment]
This has resolved a bug for me where starting streams on DLNA renderers would fail with [this error](https://gist.github.com/LeoVerto/98f6fd9f2a187e60a0a458c9f50bb507).

**Comment by sparky8251** [comment]
Just want to add, it looks like we have encountered issues where Android TV apps work with Emby server but not Jellyfin server and its been tracked down to Jellyfin having ffmpeg 3.x and Emby having ffmpeg 4.x.

Both servers start the exact same transcode command, but only the 4.x ffmpeg (emby) produces a playable stream.

Can anyone confirm if the DLNA playback issues are resolved by setting their ffmpeg binary to one copied from Emby?

**Comment by bfayers** [comment]
> Can anyone confirm if the DLNA playback issues are resolved by setting their ffmpeg binary to one copied from Emby?

DLNA is not fixed by ffmpeg 4.x, however In combination with this pull it might.

**Comment by bfayers** [comment]
> > Can anyone confirm if the DLNA playback issues are resolved by setting their ffmpeg binary to one copied from Emby?
> 
> DLNA is not fixed by ffmpeg 4.x, however In combination with this pull it might.

Using this pull request definitely fixes DLNA, especially in combination with ffmpeg 4.1.x

**Pull request merged**
