### PR TITLE
Clean up and rename obsolete deployment platforms

### PR DESCRIPTION
**Pull request by joshuaboniface**
**Changes**

General housekeeping of the build infrastructure after several successful releases using it in practice.

1. Remove Linux tar builds that are superseded by `linux-x64` (`debian-x64`, `ubuntu-x64`).
1. Rename `osx-x64` to `macos` to use their new name, and since there's no other possible choices of arch.
1. Rename `framework` to `portable` to better reflect its proper function and output name.
1. Rename `win-generic` (scripts) to `windows` to better reflect its function (`generic` implies no arch).

**Issues**
N/A

### CODE REVIEW

**Comment by Matt07211** [comment]
What does point 1 mean for me? I currently build on my Solus Machine and have been using the linux-x64 Option to build

**Comment by joshuaboniface** [comment]
Correct there, it drops `debian-x64` and `ubuntu-x64`, since `linux-x64` basically does the same thing and I can't really imagine there are major differences there. Maybe some libraries? I'm not too sure. @EraYaN might be able to comment since he originally added them, but I haven't built these for any release officially yet, so I'm not sure how useful they are.

**Comment by EraYaN** [comment]
Well these folder names were originally based on the dotnet RIDs: https://docs.microsoft.com/en-us/dotnet/core/rid-catalog

Hence `osx-x64` for example.

Source: https://github.com/dotnet/corefx/tree/master/pkg/Microsoft.NETCore.Platforms

These are mostly important for the native builds in nuget dependencies. So at least make sure you build the correct RID for the packages (deb, rpm etc).

`linux-x64` is not some magic catch all.

**Comment by joshuaboniface** [comment]
@EraYaN Yea that makes sense, but what i mean was more we already have "real" packages for Debian and Ubuntu, so the tar archives are mostly unnecessary and `linux-x64` should work the same way (just not specifically targeted to the distros). At least that's my understanding of how those RIDs work. If we ever do find we need them specifically and `linux-x64` won't work, I guess we could always re-add based on the others.

**Pull request merged**
