### PR TITLE
Added user permission check for LyricsApi endpoints

### PR DESCRIPTION
**Pull request by JPVenson**
**Changes**
- Added permission checks for Lyrics api methods

### CODE REVIEW

**Review by Shadowghost — APPROVED** [review]

**Comment by cvium** [comment]
Why is all this not just part of the auth policy?

**Comment by JPVenson** [comment]
@cvium because we are a few weeks away from the release and i am already working on a generalized method to handle that. In the meantime this and #11167 should be fixed anyway.

**Comment by cvium** [comment]
You are duplicating the auth stuff from DefaultAuthorizationHandler. The only check you need is the IsVisible check, the rest is already handled.

**Comment by JPVenson** [comment]
@cvium ok yes fair point

**Comment by crobibero** [comment]
https://github.com/jellyfin/jellyfin/pull/11171

**Pull request closed without merging**
