### PR TITLE
Make first stream default if none is set

### PR DESCRIPTION
**Pull request by gaudat**
Refer to #8164.

### CODE REVIEW

**Comment by gaudat** [comment]
Logic seems not working on my side. Converting to draft while I fix it.

**Comment by gaudat** [comment]
8957d5c passes unit tests with the "default" field in test data set to 0. Let me know if you want to add an extra test case for this situation. As I do not know how frequent this happens.

**Comment by gaudat** [comment]
Tested working: deb arm64 on RPi 3B+. Reqiures a full library rescan to work as ffprobe is only run on scan. 

Alternatively we can put the logic in `StreamBuilder.cs`.

**Comment by cvium** [comment]
> Alternatively we can put the logic in StreamBuilder.BuildAudioItem or StreamBuilder.BuildVideoItem.

If it's not too complex I think it might be preferable

**Comment by gaudat** [comment]
With current master I cannot reproduce the reason SecondaryAudioNotSupported . Maybe this has been fixed between the old version I had and the latest version.

Closing this now.

**Pull request closed without merging**
