### PR TITLE
Add BaseUrl postinst migration for Debuntu

### PR DESCRIPTION
**Pull request by joshuaboniface**
**Changes**
Adds a Debian postinst migration to remove the previous erroneous BaseUrl value from system.xml.

**Issues**
Related to #1863

### CODE REVIEW

**Comment by joshuaboniface** [comment]
CC @z3ntu @brianjmurrell @Wuerfelbecher @nvllsvm @anthonylavado @dkanada @EraYaN

We should probably add a similar migration, or warning of some kind, regarding this for every packaging platform, if at all possible. The default that 10.4.0 configured will trigger every JF instance to move its BaseUrl to `/jellyfin` in 10.4.1. This would be OK from a usability perspective given the mitigations within #1863, but might be confusing to a lot of users.

**Comment by brianjmurrell** [comment]
What exactly is the implication of this and #1863?  Does it mean that Jellyfin is now at http://jf-server:8096/jellyfin/web/index.html instead of http://jf-server:8096/web/index.html?

**Comment by z3ntu** [comment]
What's this `/etc/jellyfin/system.xml` file? It doesn't exist on my machine and there's also no `system.xml` packaged with jellyfin 10.4.0

**Comment by dkanada** [comment]
@zentu that file is the configuration file that Jellyfin creates for server settings.

@joshuaboniface is there any way to update the modified base URL behavior so that we don't require migrations for every platform? Another option would be performing the migration within Jellyfin instead.

**Comment by dkanada** [comment]
The file might exist at `/var/lib/jellyfin` on Arch installations. I don't believe we should be relying on platform specific migrations though. It's the same reason I'm not keen on separating the web client out in the manner you suggested. We would obviously always provide a jellyfin-web release in our Debuntu repository but that would still cause headaches for all other releases.

**Comment by joshuaboniface** [comment]
Because the vast majority of users *didn't* set it themselves, and will have their baseurl suddenly change functionality, since the old one didn't do much.

Either we do it in code, which is going to be gross and I'm sure would get identical comments, or we do it in a one-line sed when installing the package. I don't care either way, but it needs to be addressed.

**Comment by JustAMan** [comment]
Can we make it a checked migration thing, so it only ever applies to migration from 10.4.0?
I have no doubt this won't be the very last migration thing we do...

**Comment by z3ntu** [comment]
Users can also upgrade directly from before 10.4.0 to 10.4.1 so this can't be fixed to version numbers.

**Comment by JustAMan** [comment]
Maybe we better handle it as a documentation entry in release notes?

**Comment by z3ntu** [comment]
I do think that we should have migrations in place, and as far as I understand it, the "jellyfin" base URL didn't have the intended effect and was default so the config should be modified to keep the same behavior (by removing the baseurl attribute if it was set to "jellyfin").

And many many users are not reading release notes and would be caught off guard.

Of course, if something would appear at / (when jellyfin is at /jellyfin), which would tell the user what was changed and how to do the change manually, that would be fine too. But just giving the user a 404 after upgrading is a bad way to go

**Comment by JustAMan** [comment]
In this case, migrations should be versioned, like "if migrating from version X, do Y".
Let me reinstate my worry - let's assume a user runs a nightly where baseURL is fixed, and they set the prefix to exactly this (or updated their reverse proxy and use this prefix). Changing the config blindly isn't a good idea in this case, right?

Another option might be to hardcode `/jellyfin` as a list of valid prefixes alongside with `/emby` and `/mediabrowser` (though it's a hack, not a proper solution IMHO).

That said, I don't think there's _any_ one-size-fits-all solution to this problem...

**Comment by joshuaboniface** [comment]
@JustAMan I get the concern, it would be a pain for them to set it again only to have the next upgrade remove it. I don't think there is an easy solution here.

I suppose we could just leave it and accept the change, or put it in a release note somehow. My hope with this was to just do the removal for them and let them sort it out again later on the off-chance that `/jellyfin` is actually the base URL they want.

**Comment by joshuaboniface** [comment]
Closing this PR out in favour of a release note. This sucks but can be easily fixed.

**Comment by z3ntu** [comment]
How about a post-install message that this should be changed when upgrading from before 10.4.1?

**Comment by dkanada** [comment]
I still think we could just add an automatic conversion in the code for a single release, then remove it in the next release. The number of people already using it who might be inconvenienced by the removal is a lot less than the number of people who will have to manually remove the base path if they want to use the root path again (everyone) so it seems worth it.

**Comment by joshuaboniface** [comment]
@z3ntu It would have to be a release note, otherwise we're changing actual code.

@dkanada Well I agree, but this needs to be coordinated across anything. The way the new one works, everything should "just work" at the new base URL for web users and some clients (I hope). I don't have a clean suggestion for a solution to this, plus the fact we have to get *everyone* on board.

**Comment by joshuaboniface** [comment]
Worth noting as well that I've written the following release note on this change:

* [all] The way the base URL was configured in 10.4.0 did not work properly. This has been fixed in this release. However, this fix results in a potentially breaking change. The original implementation added `/jellyfin` as the default base URL, but due to the changes in #1863, this will now be taken as an absolute base URL for the instance. This means that **all Jellyfin instances upgraded from 10.4.0 to 10.4.1 will now default to the path http://myserver:8096/jellyfin/** instead of the expected path http://myserver:8096/. Clients including Android and AndroidTV *require* this base URL to match with the entered URL (i.e. the `/jellyfin` component must be present in the configured URL). **The workaround to this is to remove the base URL value immediately after installing 10.4.1 if you're upgrading from 10.4.0.**

To do this in the WebUI:
1. Don't try to use Jellyfin at the new base URL; head straight to the admin dashboard. The default `/` URL should redirect you automatically to the new base URL.
1. Go to "Networking" on the left sidebar, under the "Advanced" menu heading.
1. Scroll down to "Base URL:".
1. Remove the text from this field (`/jellyfin`) and click "Save".
1. Restart the server.
1. Close any active sessions; they will no longer be valid. You may also need to clear your cache history for the site if the redirect was saved.
1. Visit Jellyfin at your original URL again.

To do this manually via the CLI:
1. Stop the Jellyfin process.
1. Find and open `server.xml` in the Jellyfin configuration directory.
1. Find the entry `<BaseUrl>`.
1. Replace the entire line, i.e. `<BaseUrl>/jellyfin</BaseUrl>`, with `<BaseUrl/>`.
1. Start the Jellyfin process.

**Pull request closed without merging**
