### PR TITLE
Make MusicBrainz base url configurable

### PR DESCRIPTION
**Pull request by Bond-009**
We should really overhaul the current configuration code.

### CODE REVIEW

**Comment by joshuaboniface** [comment]
Does this make it configurable via the UI?

**Comment by Bond-009** [comment]
@joshuaboniface no, this is just a temp solution. (You can set it as an env var)

**Comment by joshuaboniface** [comment]
OK, just wanted to verify. What's the actual envvar name?

**Comment by Bond-009** [comment]
@joshuaboniface It should be `JELLYFIN_MusicBrainz:BaseUrl`

**Comment by ploughpuff** [comment]
This change is causing exception which PR #1095 is addressing.

```
System.NullReferenceException
HResult=0x80004003
Message=Object reference not set to an instance of an object.
Source=MediaBrowser.Providers
StackTrace:
at MediaBrowser.Providers.Music.MusicBrainzArtistProvider.<GetSearchResults>d__2.MoveNext() in C:\git_repos\jellyfin\MediaBrowser.Providers\Music\MusicBrainzArtistProvider.cs:line 52
```

**Pull request merged**
