### PR TITLE
Add PlayListsFolder to BaseItemKind

### PR DESCRIPTION
**Pull request by BaronGreenback**
Solves the enum parse error that I've been receiving.

### CODE REVIEW

**Review by crobibero — APPROVED** [review]

**Review by Ullmie02 — APPROVED** [review]

**Comment by cvium** [comment]
But what about https://github.com/jellyfin/jellyfin/pull/5228?

**Comment by dkanada** [comment]
ping @BaronGreenback

**Comment by BaronGreenback** [comment]
Sorry, life got in the way - i'll take a look at 5228 tonight.

**Comment by BaronGreenback** [comment]
Closing as 5228 fixes this problem.

**Pull request closed without merging**
