### PR TITLE
Remove redundant class AssemblyInfo

### PR DESCRIPTION
**Pull request by Bond-009**

### CODE REVIEW

**Comment by cvium** [comment]
fyi, https://github.com/search?q=org%3Ajellyfin+iassemblyinfo&type=Code

**Comment by Bond-009** [comment]
@cvium only 2 plugins ;)

**Comment by JustAMan** [comment]
> @cvium only 2 plugins ;)

IMHO you should fix those plugins first and only after this code is really unused drop it.

**Comment by cvium** [comment]
> > @cvium only 2 plugins ;)
> 
> IMHO you should fix those plugins first and only after this code is really unused drop it.

Only the iptv one has been ported, but that one is also important I think

**Comment by cvium** [comment]
No, but most of them are broken anyway

**Comment by joshuaboniface** [comment]
IPTV wasn't :(

**Pull request merged**
