### PR TITLE
Version bump to 3.5.2-6

### PR DESCRIPTION
**Pull request by joshuaboniface**
Bump Debian version in preparation for master release.

### CODE REVIEW

**Comment by joshuaboniface** [comment]
There were just too many to pick one! I'll find something to single out.

**Comment by brianjmurrell** [comment]
Can we use this as an opportunity to please stop using a `-` in the version?  It is going to foul up RPM packaging, which is [already being done for Fedora and EL7](https://copr.fedorainfracloud.org/coprs/wuerfelbecher/jellyfin/builds/).

As you can see, @Wuerfelbecher already has 3.5.2 packages and is being forced to using `git<sha1>` to differentiate the different 3.5.2 releases -- which is not even going to work because it means that  `<sha1>`s have to be "orderable" which they are not.  So sooner or later we are going to end up with RPM packages that don't upgrade each other because a superior package is going to look inferior due to the `<sha1>`s not ordering as they need to.

**Comment by anthonylavado** [comment]
@jellyfin/core Maybe we use this opportunity to bump as per SemVer? I guess we’re really at least on a 3.5.3 at this point, and I don’t know that we need to keep the same version for compatibility anymore. We’ve already lost the two big mobile apps, and even in my bump testing, the version didn’t really affect anything.

When the Android app still worked, setting my Jf install to `3.6.0.0` still loaded and it still worked fine.

**Comment by joshuaboniface** [comment]
Do we want to just make this 10.0.0?

**Comment by joshuaboniface** [comment]
As a side note, how *does* RH do build bumps? The dash is Debian versioning for (new build but same version) used for bugfixes.

**Comment by Wuerfelbecher** [comment]
> As a side note, how _does_ RH do build bumps? The dash is Debian versioning for (new build but same version) used for bugfixes.

In RPM the **-3**.fc29  separates upstream version from the release of the package that's why you cannot have a dash in the version since RPM uses the package release to overrule the version.

**Pull request closed without merging**
