### PR TITLE
Fix depencies issues for fedora 37

### PR DESCRIPTION
**Pull request by yodatak**
A try to fix issues #8587

### CODE REVIEW

**Review by joshuaboniface — APPROVED** [review]
Looks good - tried to target the release branch but that didn't work - we'll just have to leave this until 10.9.0.

**Comment by jlost** [comment]
Should I take this PR to mean Jellyfin doesn't work on Fedora 37 yet?

**Comment by mihawk90** [comment]
> Should I take this PR to mean Jellyfin doesn't work on Fedora 37 yet?

Jellyfin itself should™ "just work"™, the problem here is the package. Theoretically you can just extract the contents of the package and run it that way.
Note: I don't advise this as it can cause conflicts when the package eventually becomes available, but it is an option for experienced users.

**Comment by Shadowghost** [comment]
The issue this was meant to fix was fixed in upstream firewalld.

**Pull request closed without merging**
