### PR TITLE
Allow pulling missing Track Number or other data from MusicBrainz

### PR DESCRIPTION
**Pull request by scottpk**
Add option to pull in missing track info from MusicBrainz

**Changes**
Add code that pulls info from MusicBrainz when missing
Add a configuration option to enable/disable this behavior

**Issues**
Relates to #4991 Jellyfin doesn't read track numbers from Vinyl records correctly e.g. A1, A2 & B1 etc (user's vinyl software did not fill in the track number)

### CODE REVIEW

**Comment by scottpk** [comment]
Hello - this is the first time contributing to this project, please let me know if there are any changes I should make. I noticed that your instructions mentioned a DEV branch but I don't see that...

**Comment by Shadowghost** [comment]
`master` is our dev branch.
FYI: The MusicBrainz plugin is currently being rewritten in #7603 
It's likely that your changes won't be looked at until that PR is merged because it inherently changes how the plugin does some things.

**Comment by CluelessTechnologist** [comment]
> `master` is our dev branch. FYI: The MusicBrainz plugin is currently being rewritten in #7603 It's likely that your changes won't be looked at until that PR is merged because it inherently changes how the plugin does some things.

#7603 has been merged now. Can we have someone look over this PR now?

**Comment by scottpk** [comment]
Apologies, is this something I need to do? I see a message about merge conflicts but I'm not sure if I have access to resolve them

**Comment by crobibero** [comment]
@scottpk Yes, you need to merge Jellyfin's `master` branch into this branch.

**Comment by scottpk** [comment]
I have not forgotten about this, I'm just having some trouble translating to MetaBrainz' calls, seems like MetaBrainz is not behaving as I would expect. Do they have documentation that tells what HTTP request is made for which call? I tried to see in Fiddler but maybe I've got something set up wrong because I didn't see the request.

**Pull request closed without merging**
