### PR TITLE
Adds User Ratings

### PR DESCRIPTION
**Pull request by TheItalianGame**
**Changes**
Adds user rating functionality to the server portion of jellyfin
Specifically you can add a user rating sort by a user rating and filter by a user rating.

Currently working on it from the client side.

### CODE REVIEW

**Comment by TheItalianGame** [comment]
I had to force push because the author was missing.

**Comment by TheItalianGame** [comment]
API Changes.

Created two new routes:

`POST` `/Users/{userId}/UserRating/{itemId}` to update the rating and
`DELETE` `/Users/{userId}/UserRating/{itemId}` to remove the rating

Added query parameter to  `/Users/{userId}/Items` and `Users/{userId}/Items` called minUserRating to filter by user ratings.

In addition the `sortBy` parameter of the query routes now accepts the value `UserRating`

**Comment by cmsimike** [comment]
*note* I am not associated with this project, just a user.
Thank you for this! I use UserRating very heavily in my previous Kodi library so this would be a great addition.

I recently migrated my metadata from Kodi to Jellyfin (through a custom end point meant to insert the data directly)

I dug through the API and found the `UserData` object on `Item`s which already contains a `Rating` property
image


I had assumed this was a user rating field already, so I populated my rating data in here. What's the difference between `Rating` and your new `UserRating`?

**Comment by TheItalianGame** [comment]
I wasn't sure what that field was and neither was anyone else. It seems like many years ago there was plan to implement user ratings but it never went anywhere.


If the pr is approved I will open another that removes that column.

**Comment by nielsvanvelzen** [comment]
I think it would be better to re-use the existing rating column/api member. From what I can see it's unused in the server, except for the likes boolean (which stores a 10 in rating for like and a 1 for dislike). We've deprecated the likes/dislikes (no client uses it) so it should be safe to use the rating column.

**Comment by TheItalianGame** [comment]
Alright I'll do that.

I'd prefer if you delete this pr and I'll open another one when I change the column.

**Comment by Bond-009** [comment]
Closing as requested

**Pull request closed without merging**
