### PR TITLE
Add new EF Core data model

### PR DESCRIPTION
**Pull request by EraYaN**
**Changes**
For now it adds a project with an [Entity Framework Visual Editor](https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner) based entity model. Note this only contains some of the media types and some of the fields, those are easy to add later.

My main philosophy for this is to keep the database structure as restrictive as possible, as this forces good "data-hygiene" as it were. So no JSON blobs, no generic tables that are key-value stores (if we want that we should use Redis or something) etc.

**Images History**
<details>
<summary>Old Revisions</summary>
2019-06-01 (b82a749)
diagram_2019-06-01_001

2019-06-01 (17f4034)
diagram_2019-06-01_002

2019-07-06 (8e7d876)
diagram_2019-07-06_001

2019-07-07 (b59cd27)
diagram_2019-07-07_001

2019-09-04 (16c4058)
diagram_2019-09-04_003

</details>

2019-09-14 (95658e2)
diagram_2019-09-14_001

TODO LIST:
- [ ]  Add user related permissions and preference from existing database schema (so far, only xml based ones have been added)
- [ ]  Add user linked tracking of watch status and resume points for media in a media agnostic way (aka, allow for resuming audiobooks and comics as well as movies and tv shows)
- [ ] Implement storage of system wide settings. Avoid "node" specific settings like bound IP, ports, hw accel, etc while migrating settings like default UI culture, metadata language, etc
- [ ] Implement storage of multiple languages for metadata (including images). This would allow admins to define server wide fetch languages allowing for better internationalization support. The admin could say they want 3 languages and then users can decide which order they want these languages to be when displaying metadata.
- [ ] Implement user definable fallback that can have multiple steps for UI and metadata language. Currently, US English is the only fallback if you chose a language other than it. Ideally, users should be able to fall back through a list of languages of their choosing (with US English being the final fallback as it is now)
- [ ] Implement a generic grouping and collections system that will allow users and admins to group media in arbitrary ways. As an example, you could group Futurama into 3 parts, pre-movies, movies, and post movies then group these together such that if you watch the last episode of pre-movies "up next" appears shows the first movie. But... Ordering must not be required. Maybe a user just wants to group the 300 Scooby-Doo movies into one "folder." This should effectively take over the role of playlists since it serves the same purpose but is more flexible

### CODE REVIEW

**Comment by dkanada** [comment]
Are we going to try to fit music tags like artist and composer into PersonRole or just label them as attributes in MusicMetadata? The same question goes for book authors.

Another thing we should plan ahead for is better support for alternative media types. I haven't looked into it much but audiobooks are audio files but require metadata for books which is an odd situation. I have no clue what kind of information podcasts would need and no clue what file structure is best for music videos.

**Comment by dkanada** [comment]
Are we going to try to fit music tags like artist and composer into PersonRole or just label them as attributes in MusicMetadata? Books have the same problem with authors. There are also a lot of unanswered questions about how to handle alternative media types. We should really add a separate library type for items like audiobooks rather than treat them as music files when adding libraries, which is what I think happens right now.

1.) Should audiobooks inherit from books or music? They require the same information as books but are treated as audio files in the web client.
2.) What file structure should music videos have? Should we treat them as individual songs or do most people group them by artist and album? We might be able to inherit SongMetadata here since they are so similar.
3.) Is there any benefit to keeping a library type for music videos rather than use home photos and videos for that library?
4.) If we are targeting books should we also eventually try to convert them as well? Does the server support an interface to implement transcoding for a specific media type? The web client could definitely handle books so converting them on demand would be useful.

**Comment by EraYaN** [comment]
I thought about adding the artist and such as people, since that will give us easy and fast artist filtering (and maybe some metadata) and something to base an artist page of off. But in reality given the stupid amount of ways people put multiple artists in the artist field, not sure if this would be feasible. Is there a good database of artists that can be used as a metadata provider? Our best bet might be both, use a text artist field, and parse that into Persons and all unknowns just ignored.

AudioBooks should probably just be a "book", but instead of that the Release contains only one File that is an epub/pdf, it contains an mp3 (AND an epub?) for example. So Book and AudioBooks might be the same for the database but one has an audio file linked to it.

For me personally music videos are concert blurays/dvds (with chapters for every song/ment/vcr etc). So "Album" and "Artist" as important pieces of info. I would love if we could at least browse by artist. I added all metadata in the Kodi nfo format. So with artist, publisher, year, album, track etc.
So probably for me they would/should be handled the same as music CD ISOs or single file gapless albums.

So yes MusicVideos/Concerts are very different from just random (home) videos.

Converting ebooks can get very hairy and should probably be a manual process mostly. Since you need to check for the formatting or that it didn't miss large sections. We might add such things, but maybe we can also just restrict our supported file types to image based comics (non-rar, zip/gz only) and all html/txt/rtf based formats. And maybe even PDF.

**Comment by dkanada** [comment]
The current system includes unique pages for both artists and album artists. I'm starting to think they might already be treated the same way as actors. If you go to an artist's page there is a specific section for albums where they are featured in a single song. This looks extremely close to the way actors are showcased in the interface.

We also need to account for seasons as a discrete item because I know we need to track banner images for the series view. They might get their own description, I'm not quite sure.

**Comment by cvium** [comment]
How does this affect crossplatform development?

**Comment by dkanada** [comment]
I was treating this as an opportunity to work on the database schema but I agree. This doesn't seem very good for people who use anything other than Visual Studio. If we do end up using EF Core we should just commit the code this tool generates with the final design and work on it manually from that point.

**Comment by EraYaN** [comment]
Yes, in the end we should commit the generated code. But for now, probably easier to start with a designer, since then a design like this can be done in an hour or so.

**Comment by dkanada** [comment]
Here are two more issues I mentioned in chat last night.

1.) Should genres be tracked as attributes on movies, shows, books, and albums or should they get their own table?
2.) Seasons might need their own table to track images but we need to account for shows that use the date aired and shows that use absolute ordering.

**Comment by EraYaN** [comment]
I need some more input on how to handle `MusicAlbums` and `MusicVideos`. For example single file rips, double song tracks (multis), concerts vs single track music videos or even video albums.

So really Right now this is the layout:
Screenshot

So `Tracks` and `MusicVideos` are playable (relation to `Releases`).
I could add the same `Tracks` relation to `MusicVideos` and the extra `Releases` relation to `MusicAlbum`, or remove the `Releases` relation from `MusicVideos` and "merge" it into Music with the Release in the track dictating whenever it is a video. And we could add an offset or chapter number to the track entity so multiple `Tracks` can point to the same `Release` but still start playing at the right time stamp. Or just let them behave the same as multi episodes and let them start at the beginning.

I do like the idea of using chapter markers and time offsets (from say cue files). But I'm, not quite sure what the best way forwards is. This is practically the opposite from `multiversion`, `multidisc` or `multiformat` in the database. It's the other way around, and how to store it, do we store it with the relation (so in the parent table), or do we make an entity `ReleaseSection` or something similar.

**Comment by philippk80** [comment]
I have some questions and some points to discuss. Nothing meant as offense. I just want to collaborate to a good database design. To switch to this new structure will be time consuming and after that every change can hurt if we miss something here. 😄 

1. What is the nullable string "Role" on "PersonRole" meant for?
2. I would like to see remix artists for dance music. So maybe there should be another "PersonRoleType" -> "RemixArtist" or an TrackMetadata relation "RemixArtists" to "PersonRole" with "RoleType" -> "Artist"
3. What counts as "Release"? Is a remix of a song a release of a "Track" or a own "Track"? If a remix is a release then we have the problem that a release has own metadata. Maybe we should link "TrackMetadata" to "Release" instead of "Track". I think the requirement to have special metadata for some releases could be useful in other cases than remix-artists
4. How is "Track" linked with the library? Is it linked directly to "LibraryItem" or must there be an "Album" to link a "Track" to the library? I wouldn't presume an "Album" for a "Track". There are enough songs without albums. 😄
5. I love the idea to link a musicvideo directly to a release as mediaitem. Because in practical it's the same song. I'm not completely happy with the implementation. I think we should save the real mediatype as specific column so we don't have to extract the extension from path each time we choose the best mediafile to play. 
I understand the idea for MediaFileKind to ensure simplicity but I think we're limiting/disturb ourselves with that. Everytime a new mediafile would be imported we have to update all others with which is the main kind and which is not and so on... I think we should relay here on mediatype and bitrate or something like that and encapsulate the logic for choosing the "main" mediafile with a stored procedure or on the api layer (http/rest or what is used). Each device has different preferences and so a different "main" mediafile.
We should have the possibility to deliver device specific parameters on this api request.

Finally I don't understand how you track the order of multiple "AdditionalPart". Maybe I understood it wrong and you meant with that the MediaFileStream but I thought the MediaFileStream is for multiple streams of the exact same file source.  

PS: Let me know if I can support here in some way. I'm working fulltime on database/application development and would start to collaborate here. I would love to see Jellyfin as my mediacenter solution. But at this point two or three features are missing for me.

**Comment by EraYaN** [comment]
1. For a free form (user facing) name of a Role, think "Tony Stark" for an Avengers movie. So you get <blank> as <Role>
2. Remix artists are not an ID3 tag, so I doubt we would support it natively. Most music databases will include the remix artist in the title.
3. Think of "Release" in the sense of the scene, so every different version of some movie (the same one) is a different release, think a dvd rip vs a bluray rip, or the Directors Cut vs the Editors Cut.
4. Those arrows with the "Closed" heads, are inheritance. And yes all track will have albums, that is how the music industry has worked for ever, so will this.
5. I don't think I follow. There are not that many MediaFileKinds, so an enum seems sufficient. And the "real media type" what do you mean by that? Just the container type? That frankly does not matter to the system. We would never use the extension to determine the streams or file type, that is why we run ffprobe on all files.
And as for importing files and having to update some MediaFileKinds, that is fair no? Upon import we will have to grab the correct Release and all it's child objects anyway, to properly put files in it's place. (And we can have features for auto `Main` upgrade and the like if we so desire) And besides most new imports will be new releases anyway (a remix is a new release).
And no I think a fixed logic to get the main file is not the right way, since then we can't give people control over which file is "Main" and so on.
AdditionalParts are ordered `cd1` `cd2` etc. So the same ordering rules as Kodi maintains (and to an extent Emby.

Also keep in mind that a lot of fields are still missing from most entities. Same as with everything for users, settings and other system data like that.

**Comment by philippk80** [comment]
2. It is. TPE4 is described as [#TPE4 Interpreted, remixed, or otherwise modified by] (source: http://id3.org/id3v2.3.0) The thing about holding the data is to link the remixes to the artist page of the remixer. This wouldn't be possible if we only track the original song artist.
3. So for music I would prefer a remix is a release of a song. This allows to query multiple versions of a song.
4. So then a track is a LibraryItem too. Thats how it's on the graphic. That would support tracks without albums. That the music industry is working like that is true for a lot of genres, but not for all. In times of CD's and Vinyls this was true but now there are a lot of tracks without a release of an album.
5. Sorry for the bad explanation. With "real media type" is then the result of ffprobe meant. In my opinion the MediaFileKind makes no sense because it depends. Like you said. One device or user prefers this one and the other that one. So an API with parameters like display-resolution or bandwith settings, user settings (just to name a few) would be better to retrieve the "Main" Mediafile. I mean that the server would pick the right option for the settings the client delivers. This could be anything...maybe a stream that will be transcoded for the client on the fly and don't physically exists. The client isn't interested in which files are physically there. The client just want's to play with his preferred settings.
That means they are ordered by name?

**Comment by oddstr13** [comment]
I think it would make sense to bind person to media item, using a (person id, media id, relation type enum) table. This way we can get all media associated with a person, all persons associated with a media item, and filter on the type of the relation. Be it author, photographer, artist, director or main role actor.

It may even make sense to extend person to also cover things like publisher & production companies in this context?

**Comment by philippk80** [comment]
> I think it would make sense to bind person to media item, using a (person id, media id, relation type enum) table. This way we can get all media associated with a person, all persons associated with a media item, and filter on the type of the relation. Be it author, photographer, artist, director or main role actor.

What do you mean with mediaitem? "MediaFile" or for example "Track"? It's important that we sue the same words, otherwise we run into communication problems

**Comment by EraYaN** [comment]
2.   Right the correct thing to say was probably that most music players on phones do not support or show this tag.
3.   Mmm, I guess we can do this if the tag is properly used, though for me the Release type was for multiversion (think 720p/1080p) and the like because there is not metadata attached. The Directors cut vs Editors cut was a wrong comment.
4.    Aah yes, correct. Hadn't thought about it, it would be purely the code limiting this. Upon scanning one would have to match an empty string for the album to not create an album entity.
5.   Well there can be two AC3 files for example and the ffprobe result does not dictate what the file is, the filename probably does (for example "Commentary" or something like that. And xmp files are sidecars, so are most subtitle files. So it does make sense because you need to store it, so people can shuffle the roles of files by themselves.
And on the API part, the client shoukld decide what available streams he wants, so the API gives you all possible streams (video, audio, subtitles) and the client picks one, instead of the other way around. It's much more fool proof, especially since the client knows better what it can play. That's why the DLNA stuff needs profiles.
And yes ordered (string sort) on name, but we might want to store the index as an int.

**Comment by oddstr13** [comment]
> > I think it would make sense to bind person to media item, using a (person id, media id, relation type enum) table. This way we can get all media associated with a person, all persons associated with a media item, and filter on the type of the relation. Be it author, photographer, artist, director or main role actor.
> 
> What do you mean with mediaitem? "MediaFile" or for example "Track"? It's important that we sue the same words, otherwise we run into communication problems

I used media item in the most generic way, to represent any type of media that Jellyfin would orgnize. Track, album, movie, series, episode, photo, book, comic. I haven't looked in detail at the propposed db schema recently, but I guess it might be LibraryItem

**Comment by philippk80** [comment]
> 1. Right the correct thing to say was probably that most music players on phones do not support or show this tag.

But I think the goal of a project like Jellyfin is not to delivery only the same as others. Jellyfin targets own clients for all plattforms. So this shouldn't be an argument. 😄  
> 2. Mmm, I guess we can do this if the tag is properly used, though for me the Release type was for multiversion (think 720p/1080p) and the like because there is not metadata attached. The Directors cut vs Editors cut was a wrong comment.
> 3. Aah yes, correct. Hadn't thought about it, it would be purely the code limiting this. Upon scanning one would have to match an empty string for the album to not create an album entity.

Yes. Or replace string.empty with one predefined various artists album. 
> 4. Well there can be two AC3 files for example and the ffprobe result does not dictate what the file is, the filename probably does (for example "Commentary" or something like that. And xmp files are sidecars, so are most subtitle files. So it does make sense because you need to store it, so people can shuffle the roles of files by themselves.
>    And on the API part, the client shoukld decide what available streams he wants, so the API gives you all possible streams (video, audio, subtitles) and the client picks one, instead of the other way around. It's much more fool proof, especially since the client knows better what it can play. That's why the DLNA stuff needs profiles.

But wouldn't the commentary be a release of a movie?
I think we talk about the same things but we structure it with two different ways.

Let met describe my thinking from the movie side (this was my understanding as I saw your graph first):

- Release -> Directors Cut or EditorsCut or Commentary (alle different types of media relating to the movie)
- MediaFile -> Bluray-Rip 720p of Directors Cut,Bluray-Rip 1080p of Directors Cut ...
- MediaFileStream -> Path or URL to file (http://mirror1.bla.org/directorscut.extension; http://mirror2.bla.org/directorscut.extension)

I think this is a point where its a challenge to fit music and movies in the same structure

>    And yes ordered (string sort) on name, but we might want to store the index as an int.
I would appreciate the index as reference for ordering. 😄

**Comment by philippk80** [comment]
> I used media item in the most generic way, to represent any type of media that Jellyfin would orgnize. Track, album, movie, series, episode, photo, book, comic. I haven't looked in detail at the propposed db schema recently, but I guess it might be LibraryItem

This is case. Not exactly like you said but with the inheritance it should result in the same.

**Comment by EraYaN** [comment]
>  Release -> Directors Cut or EditorsCut or Commentary (alle different types of media relating to the movie)
    MediaFile -> Bluray-Rip 720p of Directors Cut,Bluray-Rip 1080p of Directors Cut ...
    MediaFileStream -> Path or URL to file (http://mirror1.bla.org/directorscut.extension; http://mirror2.bla.org/directorscut.extension)

The problem here is that I would move most of these one layer up. The MediaFile's are most for multiple parts and external (commentary for example) audio tracks. And MediaFileStream are just for storing the result of ffprobe on the MediaFile, so they do not have a path. This way we can have multiversion, multidisc en the streams will handle multilanguage.

So for example:

```
Release -> BluRay rip 1080p
    MediaFile ->Movie - BluRay rip 1080p.mkv (Main)
        MediaFileStream -> 0: video avc 10MBps
                        -> 1: audio aac English 128 kbps
                        -> 2: subtitle srt utf-8 English
                        -> 3: subtitle srt utf-8 German
    MediaFile -> Movie - BluRay rip 1080p.en.srt (AdditionalStream)
        MediaFileStream -> 0: subtitle srt utf-8 English
    MediaFile -> Movie - BluRay rip 1080p.en.dts (AdditionalStream)
        MediaFileStream -> 1: audio DTS5.1 English 1.5MBps
```

And the API would present to you:
video streams: 1080p AVC 10 Mbps
audio streams: English - AAC, English - DTS
subtitles: English, German, English [External]

And the client would just pass the correct IDs to the server for what it wants to see, if it can't deal with any of the streams, it requests the codecs/containers it wants (or supports) and then the server can transcode as needed.

**Comment by oddstr13** [comment]
6

> > I used media item in the most generic way, to represent any type of media that Jellyfin would orgnize. Track, album, movie, series, episode, photo, book, comic. I haven't looked in detail at the propposed db schema recently, but I guess it might be LibraryItem
> 
> This is case. Not exactly like you said but with the inheritance it should result in the same.

My suggestion was based on how the ManyToMany field works in the Django ORM. I have no experience with the db abstraction in question

**Comment by philippk80** [comment]
>     MediaFile -> Movie - BluRay rip 1080p.en.srt (AdditionalStream)
Okay I understand.
I think that will map to music too. 😄 
```
Release -> SongX
    MediaFile -> songx.flac (Main)
        MediaFileStream
                        -> 0: audio flac ...
    MediaFile -> songx.mp3 (AdditionalStream)
        MediaFileStream 
                        -> 0: audio mp3 320kbs
                       
Release -> SongX (blabla Remix)
    MediaFile -> songx (bla bla remix).flac (Main)
        MediaFileStream
                        -> 0: audio flac ...
    MediaFile -> songx (bla bla remix).mp3 (AdditionalStream)
        MediaFileStream 
                        -> 0: audio mp3 320kbs
```

**Comment by EraYaN** [comment]
> But how do you track directors/editors-cut then?
> You said your comment was wrong.
> Is this a whole new movie then?
> I think that would be okay... it would be better if you could map these guys together.
> But then we need a new mapping table "Original" or something like that and a "Movie"-object has to reference one OriginalID.

I wonder if metadata providers provide this info, but yes it would be a separate movie, since it will have been released at a different time, and thus have different metadata.

> Another improvement would be an external-identifier column for metadata.
> Then you could map movie metadata to metadataprovider imdb with it's imdb identifier.

That is the SourceID in the Metadata table, and since every kind of metadata also inherits from this, they all have that field.

**Comment by philippk80** [comment]
Oh.. overlooked that.
Then I agree with the design. 
Thanks for clarifying. 😄 

Then only the TPE4 as PersonRoleType is missing.
Great work!

**Comment by EraYaN** [comment]
Some further questions:

Do we want to be able to store "Ensembles/Bands" for music? Since a person can be both a soloist as well as be in a band and it might be cool if that artist page would show content from both. Not sure if there is a metadata provider that provides this though. Right now a "Band" would end up being a person with the "Artist" type.

Do we want Studios, Networks, Labels and Publishers to be their own entity? Right now these are text fields.

Should episode numbers exist in the episodemetadata entity or in the episode entity? If done in the episode entity, a absolute ordered episode would need to be a separate episode, while when in metadata it could be two metadatas for one episode, then adding an Enum column as to the ordering type (based on TheTVDb ordering types for example)

And the same question for Seasons (although I do not think seasons have different orderings, but different providers might use different season numbers) And how to define a Show without seasons? (like most anime on AniDB) A season with the number NULL? Or a flag?

**Comment by dinki** [comment]
Here's information for the live tv timers.  Two files are saved in /config/data/livetv

seriestimers.json

```
    {                                                                                                                                                    
        "ChannelId": "hdhr_15.2",                                                                                                                        
        "Days": [                                                                                                                                        
            "Sunday",                                                                                                                                    
            "Monday",                                                                                                                                    
            "Tuesday",                                                                                                                                   
            "Wednesday",                                                                                                                                 
            "Thursday",                                                                                                                                  
            "Friday",                                                                                                                                    
            "Saturday"                                                                                                                                   
        ],                                                                                                                                               
        "EndDate": "2019-07-10T03:00:00.0000000Z",                                                                                                       
        "Id": "0223c498688d4625bed4e8da1528946c",                                                                                                        
        "IsPostPaddingRequired": false,                                                                                                                  
        "IsPrePaddingRequired": false,                                                                                                                   
        "KeepUntil": "UntilDeleted",                                                                                                                     
        "KeepUpTo": 0,                                                                                                                                   
        "Name": "Bring the Funny",                                                                                                                       
        "Overview": "Judged by famous comics and comedic personalities, 40 undiscovered stand-up, variety and sketch comedy acts with dreams of becoming 
the next big comedy star perform as they compete for the biggest laughs and a $250,000 grand prize.",                                                    
        "PostPaddingSeconds": 0,                                                                                                                         
        "PrePaddingSeconds": 0,                                                                                                                          
        "Priority": 0,                                                                                                                                   
        "ProgramId": "EP031560990001T636983208600000000C61040_hdhr_15.2",                                                                                
        "RecordAnyChannel": false,                                                                                                                       
        "RecordAnyTime": true,                                                                                                                           
        "RecordNewOnly": true,                                                                                                                           
        "SeriesId": "EP03156099",                                                                                                                        
        "ServiceName": "Emby",                                                                                                                           
        "SkipEpisodesInLibrary": true,                                                                                                                   
        "StartDate": "2019-07-10T02:01:00.0000000Z"                                                                                                      
    }
```

timers.json

```
    {                                                                                                                                                    
        "ChannelId": "hdhr_24.3",                                                                                                                        
        "EndDate": "2018-12-12T16:00:00.0000000Z",                                                                                                       
        "EpisodeNumber": 2,                                                                                                                              
        "EpisodeTitle": "Sliding Lid Boxes",                                                                                                             
        "Genres": [],                                                                                                                                    
        "Id": "ab55c92a13f340d4acbb510bda7a989b",                                                                                                        
        "IsKids": false,                                                                                                                                 
        "IsManual": true,                                                                                                                                
        "IsMovie": false,                                                                                                                                
        "IsNews": false,                                                                                                                                 
        "IsPostPaddingRequired": false,                                                                                                                  
        "IsPrePaddingRequired": false,                                                                                                                   
        "IsProgramSeries": true,                                                                                                                         
        "IsRepeat": true,                                                                                                                                
        "IsSeries": true,                                                                                                                                
        "IsSports": false,                                                                                                                               
        "KeepUntil": "UntilDeleted",                                                                                                                     
        "Name": "The Woodwright's Shop",                                                                                                                 
        "OfficialRating": "G",                                                                                                                           
        "OriginalAirDate": "2016-09-24T00:00:00.0000000Z",                                                                                               
        "Overview": "Easy-to-make wooden gift boxes with mitered corners and lids that slide in grooves.",                                               
        "PostPaddingSeconds": 0,                                                                                                                         
        "PrePaddingSeconds": 0,                                                                                                                          
        "Priority": 0,                                                                                                                                   
        "ProductionYear": 2016,                                                                                                                          
        "ProgramId": "EP000048400438T636802254000000000C35847_hdhr_24.3",                                                                                
        "ProviderIds": {                                                                                                                                 
            "SeriesZap2It": "EP00004840"                                                                                                                 
        },                                                                                                                                               
        "RecordingPath": "/media/tv/jellyfin_dvr_tv/The Woodwright's Shop (1979)/Season 36/The Woodwright's Shop S36E02 Sliding Lid Boxes.ts",           
        "RetryCount": 0,                                                                                                                                 
        "SeasonNumber": 36,                                                                                                                              
        "SeriesId": "EP00004840",                                                                                                                        
        "SeriesProviderIds": {                                                                                                                           
            "Zap2It": "EP00004840"                                                                                                                       
        },                                                                                                                                               
        "StartDate": "2018-12-12T15:30:00.0000000Z",                                                                                                     
        "Status": "Completed",                                                                                                                           
        "Tags": [                                                                                                                                        
            "Repeat",                                                                                                                                    
            "Series"                                                                                                                                     
        ]                                                                                                                                                
     }
```

EPG data appears to be stored in 'library.db' in the 'TypedBaseItems' table.  Type is 'MediaBrowser.Controller.LiveTV.LiveTvProgram'

I'm not sure if anything else related to Live Tv is stored elsewhere but those are the two major ones.

**Comment by philippk80** [comment]
> Some further questions:
> 
> Do we want to be able to store "Ensembles/Bands" for music? Since a person can be both a soloist as well as be in a band and it might be cool if that artist page would show content from both. Not sure if there is a metadata provider that provides this though. Right now a "Band" would end up being a person with the "Artist" type

Discogs tracks this information... don't found something similar on musicbrainz

> 
> Do we want Studios, Networks, Labels and Publishers to be their own entity? Right now these are text fields.

For simplicity I would start with these text fields. Without a feature that consumes extra informations from that we don't have any benefit, but a lot of more work!

**Comment by EraYaN** [comment]
TheMovieDb for example does track a lot more info of studios for example, hence the entities.

**Comment by sparky8251** [comment]
I am working on continuing this effort and have started with user permissions and preferences with the aim of making a group system that we so sorely lack.


Screenshot_20191207_125230

So far this is the general idea. The plan is roughly as follows:

First, we force all users and groups to have provider mappings. They can have multiple mappings. This means you can have a user setup in JF and in LDAP at the same time. Obviously, the auth provider that is set on the user (not shown in the list of attributes yet) will determine how the user auths. This allows migration between providers without loss of watched status or need to setup permissions again.

Provider can put whatever secrets they need for finding the mapping in the secrets field, and they can output whatever they want into the data field. An example would be for groups. Secrets can store the search params needed to get the group in LDAP while data store all users that LDAP says have membership.

Groups for all providers are mapped to a corresponding JF group allowing for LDAP groups and SAML groups and OpenID groups to all have the same permissions in JF without frustration.

Permissions are boolean values, preferences are KV pairs. Only admins can set permissions (even on users) and only admins can set Admin Preferences.

This allows us to do group management of permissions while allowing for deny/allow to be set at the user level overriding the group. It also allows us to separate preferences between those users should not be able to set and those they can.

Any feedback is welcome. This is still a huge work in progress.

**Comment by Fmstrat** [comment]
@spark8215 I'm just now taking a look at this based on my finding of https://github.com/jellyfin/jellyfin/issues/481 above, so I do have a question.

Given the user structure created above, is there an opportunity to sudo federate some of these preferences, including media status such as watched status and resume points via a media id?

This is something I've noticed missing from most non-commercial media providers out there, and the lack of it limits administrators to a single-user to single-server structure.

For instance, what if the user preference, permission, and watched data was API driven from a central service/port within the application. This would, in the future, allow a master server to handle authentication and user tracking, and other servers to link to that master via the user API.

I ask not because it is a specific objective of this PR, but because a small shift here or there in the schema could make future multi-server support either easy or near impossible.

Thanks!

**Comment by sparky8251** [comment]
Hey there @Fmstrat!

I hear what you are saying but I think the following bits are important to consider as well:

1) None of JF is setup for multiserver, even the current plans for supporting postgres et al dont include multiserver support. Planning for a feature set we may never incorporate seems a little backwards considering...
2) Part of the reason we are specifically choosing to use an ORM like EF Core is because they support migrations. This means that this proposed schema is a best effort at fixing known bugs in the current schema and adding support for features we *know* we want to implement. If we get it wrong/things change, we can far more easily change the schema in the future to support it.

Not saying we will never support multiserver, but right now thats so far out its hard to feel any effort spent on it isn't worth the time and effort.

If you have a more concrete example of what the schema would look like with your proposed changes id be for it. 

I'd say mine already works the way you want at first glance... You can create users and setup their authentication outside of JF but the permissions are handled internal to JF since there is no consistent way to map them outside of JF across all auth types. The APIs for creating these groups and managing them will of course be usable with stuff like curl since clients will access it as well.

And since these perms are stored in the database, it would be accessible by any JF server reading the database (of which eventual support for postgres and such are planned).

Am I wrong?

**Comment by Fmstrat** [comment]
@sparky8215 Thanks, that all makes perfect sense to me! And yes, I know the feature doesn't have a lot of interest in the feature request page, but it's also a place I would be more than happy to jump into. 

Before providing any specific feedback I think I need a better understanding of how server settings are stored. Based on the model above, everything looks like a multi-server setup would be feasible as-is, but that's only if server settings are:
1. Kept independent from user and media and...
2. Have a column that identifies which server each particular setting is applied to (or are in separate databases)
This would allow a secondary server to turn off media scanning, but still have access to the library.

For instance, I don't see where flags for scanning the library are stored in the `Library` table above, so I assume they are somewhere else, but I'm not sure. Where could I look to learn more? Is there documentation out there or somewhere in the source I can start to get familiar with?

Thanks again!

**Comment by sparky8251** [comment]
For watch status, I don't think it's implemented in the schema yet. 

As for your mention of *server* settings, not all server settings will end up in the database. Settings that are "node" settings like transcode perms, bound IP/ports, etc will remain on disk as xml or some other format.

The only server settings that will make it into the database are ones that aren't "node" specific like default UI culture (which determines what users get for UI language by default) and library settings like metadata providers and metadata language and such.

**Comment by Fmstrat** [comment]
@sparky8251 That sounds perfect. The local setting structure would make things much easier. The only "gotcha" I can see happening is if the team decided to put settings such as "scan this library every 90 days" or "watch the folders for this library" settings into the schema (such as the `Library` table) instead of in the local settings. These are the key elements that in a single-server setup seem logical to place there, but in a multi-server setup are very much independent to the node. Thanks!

**Comment by EraYaN** [comment]
I still want as many settings as possible in nice text files, be it xml, yaml, toml, json what not. And if we ever doe multi server, I feel like it will be master-slave anyway, since master-master is much much harder to do. And then the slaves will just not scan any media and maybe even pull their settings from the master.
But the first thing to happen one anything multi node is farming out the transcoding and media serving to multiple nodes, it's much easier to do.

IMO putting settings in databases is dirty. Even user settings, but we might have to.

**Comment by Fmstrat** [comment]
@erayan I like your thinking. From what I have gathered spending a lot of time discussing and making third party apps for Plex for this feature is that for most users wanting it, having a shared watched status is the most important part. I.E. have home DNS point to the local server, public DNS point to the remote server with the same media library, and have watch status shared between the two. Full management and offloading transcoding would be an enterprise level nice-to-have.

Sounds like the team is really thinking through this structure, but I'm still happy to help contribute for this one.

P.S. My vote is YAML. Clean, easy to read and script out, and supports inline comments.

**Comment by uffcd** [comment]
> For watch status, I don't think it's implemented in the schema yet. It will be bound to user and library item, so if there was a multiserver it wouldnt matter if the file was at different locations on different nodes to begin with.

Would it be possible to track watched status for item+library? So that I dont get multiple entries for everything watched because there is the same movie in several libraries (f.ex. in Movies and Movies4K and Movies french)

**Comment by EraYaN** [comment]
Was this meant to be closed?

**Comment by dkanada** [comment]
Nope, I didn't realize this pull request was targeting a branch on the organization repository. I saw no commits on that branch and thought it was empty, so I closed it a bit ago.

**Comment by certuna** [comment]
I realise I might be resurrecting a corpse here, but:

>     2\. Remix artists are not an ID3 tag, so I doubt we would support it natively. Most music databases will include the remix artist in the title.

They are an [official id3v2.4](https://id3.org/id3v2.4.0-frames) frame: `TPE4 Interpreted, remixed, or otherwise modified by`

**Comment by EraYaN** [comment]
@certuna This will get lost here probably.

**Pull request closed without merging**
