### PR TITLE
Fix regression in integer divisions in latest movies category

### LINKED ISSUE #489: [web app] Wrong "latest movies" image format in home
When I open the Jellyfin home from the web browser, the movies in the "Latest" category have a weird look
jellyfin

This is what I get in Emby
emby

The issue seems to be that Jellyfin is creating a backdrop-format card, while requesting the Primary image for the movie.
I think this has something to do with [this line](https://github.com/jellyfin/jellyfin/blob/5a66cbd75a74b7676cd6b16af0b8651af70d23af/MediaBrowser.WebDashboard/dashboard-ui/bower_components/emby-webcomponents/homesections/homesections.js#L224) or the cardBuilder module, but I don't know exactly how this JS is executed, so I can't debug any further.

### PR DESCRIPTION
**Pull request by hawken93**
As discussed right now in the #jellyfin-dev chat, the GPL cleanup made a regression where double division turned into integer division

Fixes #489

### CODE REVIEW

**Comment by cvium** [comment]
For reference: As discussed, missing 2 more ;)

**Comment by cvium** [comment]
LGTM

**Comment by hawken93** [comment]
I believe this fixes #489 and #490

**Comment by hawken93** [comment]
Tested. Fixes #489

**Comment by bobberb** [comment]
Confirming fix of #489 from @hawken93 @sparky8251 fixes :D

**Comment by Bond-009** [comment]
#519 is the actual fix for #490, at most this PR makes that code not execute.

**Comment by hawken93** [comment]
> 
> 
> #519 is the actual fix for #490, at most this PR makes that code not execute.

ok then I will not claim fix for 490 here :)

**Pull request merged**
