### PR TITLE
Rename all projects to remove Emby and MediaBrowser naming

### PR DESCRIPTION
**Pull request by sparky8251**
**Changes**
Removed all instances of Emby and MediaBrowser in project names, sln files, and csproj files.
Project is building but will need to test built project and a full clone and with the web submodule being initialized (I had the submodule initialized beforehand).

Figure since this would best be done right after a major release and before we ramp up a dev cycle I'd propose it. Would be nice to be rid of the old naming schemes and truly separate ourselves from Emby.

### CODE REVIEW

**Comment by Bond-009** [comment]
IMO this should be done project by project. This is just to big to review.

**Comment by sparky8251** [comment]
A lot of the projects depend on each other being renamed to build at all.

I can try and break it up by commit for projects that can be standalone if that's any better? I can't see how its going to make it any easier however, the renaming of the folders (required to rename the projects) makes git think I deleted a file and added a new one.

**Comment by sparky8251** [comment]
Drone CI seems to be failing due to lint checks. `using`s are no longer alphabetical so it's failing. You check it out and build it and it will at least build.

**Comment by EraYaN** [comment]
All CI scripts will need to be adjusted too I believe. We might want to do this on the final master version and hold other PRs before continuing. This will also break all plugins.

It might not be very useful for now. Maybe concentrate all the breakage around the DB swap.

**Comment by sparky8251** [comment]
I should have already updated the CI scripts.

**Comment by sparky8251** [comment]
Well, the time for this has come and gone. At least until 10.4.0 lands. Too much dev work going on now that the 10.3.z is wrapping up.

**Comment by joshuaboniface** [comment]
I still think the idea has merit, but I think it's quite clear why Emby never renamed the MediaBrowser stuff - it's all very fragile and complex, hard to review (even by the person doing it), etc.

I think this should still be a long term goal, but let's approach it slowly and steadily, one module at a time, when they need to and can be.

**Pull request closed without merging**
