### PR TITLE
Update Docker Image

### PR DESCRIPTION
**Pull request by Artiume**
**Changes**

**Issues**

Was unable to build the docker image, was receiving

deb [arch=amd64] https://repo.jellyfin.org/debian  main
E: Malformed entry 1 in list file /etc/apt/sources.list.d/jellyfin.list (Component)
E: The list of sources could not be read.

I don't necessarily like the change as we can't explicitly specify the image. Also will most likely need to update the arm images as well.

### CODE REVIEW

**Comment by joshuaboniface** [comment]
Weird, it's somehow missing the version codename from `/etc/os-release`. Is it happening consistently? I don't really see how changing that would fix it since it should have the same contents - if you can paste a `cat /etc/os-release` from a build attempt I could look into it.

**Comment by Artiume** [comment]
Original Image:
PRETTY_NAME="Debian GNU/Linux bullseye/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

New image:
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by joshuaboniface** [comment]
Aah, so for some reason they're using two different images for `bullseye` and `stable` :facepalm: 

OK, approved.

**Review by joshuaboniface — APPROVED** [review]

**Comment by Artiume** [comment]
Updated the arm images, verified that the image tags are valid, but not attempt to build.

**Comment by crobibero** [comment]
@Artiume can you test to see if the updated dotnet6 docker images work on your system? I didn't have any issues building them

**Comment by Artiume** [comment]
Since 6595 is merged, just build master?

**Comment by crobibero** [comment]
> Since 6595 is merged, just build master?

Yep, exactly

**Comment by Artiume** [comment]
It builds successfully. I am getting this on iniitial startup though. Is master broken?

```
[22:55:55] [FTL] [4] Main: Error while starting server.
System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
en-US is an invalid culture identifier.
   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at System.Globalization.CultureInfo..ctor(String name)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder..ctor(ILogger`1 logger, IServerConfigurationManager configurationManager, IFileSystem fileSystem, ILocalizationManager localization, IConfiguration config)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)                  
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)                      
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)               
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)                   
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)     
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)                                                       
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)                                                           
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)           
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)                                                                  
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)                                     
   at Emby.Server.Implementations.ApplicationHost.Resolve[T]()
   at Emby.Server.Implementations.ApplicationHost.InitializeServices()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[22:55:55] [INF] [4] Main: Running query planner optimizations in the database... This might take a while                                                    
[22:55:56] [INF] [4] Jellyfin.Server.Implementations.JellyfinDbProvider: There are pending EFCore migrations in the database. Applying... (This may take a while, do not stop Jellyfin)
[22:55:56] [INF] [4] Jellyfin.Server.Implementations.JellyfinDbProvider: EFCore migrations applied successfully                                              
[22:55:56] [INF] [4] Emby.Server.Implementations.ApplicationHost: Disposing CoreAppHost                                                                      
[22:55:56] [INF] [2] Main: Received a SIGTERM signal, shutting down
```

**Comment by crobibero** [comment]
Yep that’s probably new with dotnet6

**Comment by Artiume** [comment]
Are the built images having the same runtime error or is this limited to docker

**Comment by crobibero** [comment]
I don’t believe the outputs from the builder images have this issue, but I’ll have to check when I get more Jelly time

**Comment by Artiume** [comment]
https://github.com/jellyfin/jellyfin/pull/6629

If i add this change, i no longer have issues so my PR should be good to go

**Review by crobibero — APPROVED** [review]

**Pull request merged**
