### PR TITLE
WIP - Replace Mono.Nat with Open.Nat

### PR DESCRIPTION
**Pull request by Bond-009**
Still a WIP

### CODE REVIEW

**Comment by JustAMan** [comment]
@Bond-009 is this still WIP?

**Comment by Bond-009** [comment]
@JustAMan yes, I need to go trough it all and see what exactly Emby did with this.

**Comment by anthonylavado** [comment]
Still WIP, so removing from the Weekend Project for now.

**Comment by nvllsvm** [comment]
There are now conflicts.

Temporarily closing - dev branch is being removed in favor of master branch. Also shrinking repo. https://github.com/jellyfin/jellyfin/issues/311

Please reopen in 3 hours.

**Pull request closed without merging**
