### PR TITLE
Add support for embedded lyrics to lyrics API

### PR DESCRIPTION
**Pull request by DomiStyle**
**Changes**
This PR adds support for loading embedded lyrics from music files in LRC and TXT format. Previously these were only loaded from external files.

In order to store the lyrics I enabled the JSON serialization for items of type Audio. If there's a problem with this it would also be possible to add a database field for it or retrieve them when requested.

### CODE REVIEW

**Comment by DomiStyle** [comment]
Made this a draft since it makes more sense after https://github.com/jellyfin/jellyfin/pull/9920 is merged.

**Comment by Bond-009** [comment]
#9920 is merged now

**Comment by DomiStyle** [comment]
@Bond-009 Thanks for the heads-up. I'm also waiting for https://github.com/jellyfin/jellyfin/pull/9951.

Much nicer solution than keeping the serialized data for every track.

**Comment by NicholasFlamy** [comment]
And also, I posted in the other place, but thank you as well for your work! 👏👏👏

**Comment by DomiStyle** [comment]
Superceded by https://github.com/jellyfin/jellyfin/pull/11081

**Pull request closed without merging**
