### PR TITLE
Fix trivial SA1005, SA1111, SA1508, SA1510 warnings

### PR DESCRIPTION
**Pull request by telans**
**Changes**
- -525 Warnings

**Issues**
#2149

### CODE REVIEW

**Comment by telans** [comment]
Or is it best to leave these little things like these until classes are moved into Jellyfin.x etc?

**Comment by crobibero** [comment]
I can't speak for all projects, but I would leave MediaBrowser.Api alone because it's being actively converted

**Comment by dkanada** [comment]
The API one is the only one going through major changes, but I don't think this should cause that many merge conflicts so it's probably fine.

**Comment by Bond-009** [comment]
And there already are conflicts...

**Comment by telans** [comment]
Should be fixed

**Pull request merged**
