### PR TITLE
Change the base image of Dockerfile to Ubuntu focal

### LINKED ISSUE #3631: HEVC on VAAPI & AMD AMF on Jellyfin 10.6.0 Docker
On Jellyfin 10.6.0 the render group has been fixed for /dev/dvi/renderD128 but VAAPI will not transcode HEVC because the docker does not include Mesa 20.1 or higher. I can't fix this using the last fix because you have switched the base image away from Ubuntu and over to Debian Buster which doesn't have a ppa for the newest Mesa. So you will have to compile these yourself and add the updated libraries to the docker image or switch the docker image back to Ubuntu, more specifically Ubuntu 20.04 and then let us use the PPA to upgrade the Mesa libs to at least Mesa 20.1.

If this isn't done then VAAPI and HEVC hardware transcoding will never work and AMD AMF transcoding will never work.

### PR DESCRIPTION
**Pull request by nyanmisaka**
**Changes**
- Avoid the outdated Mesa VAAPI driver in Debian buster, fix AMD HEVC transcoding issue.
- The latest Intel driver can only be installed in Ubuntu focal.
(https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-focal.html)

**Issues**
Fixes #3631

### CODE REVIEW

**Comment by joshuaboniface** [comment]
Will this work properly since the main containers are Debian? I'd be hesitant given the major deps of FFMpeg. But if it works OK.

**Comment by nyanmisaka** [comment]
> Will this work properly since the main containers are Debian? I'd be hesitant given the major deps of FFMpeg. But if it works OK.

Do you mean there may have data losses when upgrading from a Debian based container to a Ubuntu based container?

I think it's okay if the docker config stays the same. We just need the latest media/video driver in Ubuntu distro.

Users can uncomment one line in the Dockerfile to get the non-free intel driver for video processing and HEVC encoding, or install them manually from intel repo.

**Comment by joshuaboniface** [comment]
No I mean will ffmpeg even run.

**Comment by joshuaboniface** [comment]
As is, if it's compiled with Ubuntu shared libraries, will it run properly on the Debian docker containers. I'm not familiar enough with either to know for sure.

**Comment by joshuaboniface** [comment]
Oh, wow - I'm blind - I thought this was an FFMpeg-repo PR. That changes things.

Our container was built off Bullseye, not Buster. Was that not new enough?

I've reiterated numerous times that I am not OK switching to Ubuntu as our base. Full-stop. Either we follow LTSes in which case there is *no* change from Debian in terms of lifetime package age, or we are following a moving target of 6 months for our stable images which is unreasonable.

**Comment by nyanmisaka** [comment]
```
bullseye (stable) (libs): Mesa VA-API video acceleration drivers
20.3.5-1: amd64 arm64 armel armhf i386 mips64el mipsel ppc64el s390x

bullseye (stable) (video): VAAPI driver for the Intel GEN8+ Graphics family [non-free]
21.1.1+ds1-1: amd64 i386
```

I think with bullseye we don't need focal anymore.

**Comment by joshuaboniface** [comment]
Thanks @nyanmisaka that makes sense - not saying the other optimizations aren't worthwhile (and sorry yes I misread the date on this and thought it was very recent), so those might be worthy of another PR.

**Pull request closed without merging**
