### PR TITLE
No code changes: Just adds full stops to comments.

### PR DESCRIPTION
**Pull request by BaronGreenback**
Still bored.

### CODE REVIEW

**Review by joshuaboniface — COMMENTED** [review]
Eh I'm of the opinion that comments usually shouldn't have full-stops. It just looks... weird to me. But I'll let the @jellyfin/server team decide on style.

**Comment by dkanada** [comment]
I dislike it too, but I believe that's the style we're using.

**Comment by BaronGreenback** [comment]
It's a mix at the moment. Some comments end with . some don't.

**Comment by Bond-009** [comment]
Full-stops are required for docs but not for comments afaik

**Comment by BaronGreenback** [comment]
Fine with me.

**Pull request closed without merging**
