### PR TITLE
Fix null reference exception on API call without user id

### LINKED ISSUE #2246: [bug] Can't call /Items api without UserId
**Describe the bug**
The GetItems API call (/Items?query=...) has an optional parameter "UserId" but when you call the API without UserId it returns an "Object not set to an instance of an object" exception.

**To Reproduce**
1. Make a call to xxx.xxx.xxx.xxx:xxxx/Items
2. Supply the needed authentication headers
3. Returns "Object not set to an instance of an object"

**Expected behavior**
Returns list of items defined in the query without the need of a UserId.

**Logs**
```
[2020-01-09 12:23:48.455 +01:00] [ERR] Error processing request
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Api.UserLibrary.ItemsService.GetQueryResult(GetItems request, DtoOptions dtoOptions, User user)
   at MediaBrowser.Api.UserLibrary.ItemsService.GetItems(GetItems request)
   at MediaBrowser.Api.UserLibrary.ItemsService.Get(GetItems request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**System (please complete the following information):**
 - OS: Windows
 - Browser: Postman
 - Jellyfin Version: 10.4.3
 - Installed Plugins: none
 - Reverse proxy: none

**Additional context**
After looking at the code I think I found the problem.
Problem starts in the MediaBrowser.Api.UserLibrary.ItemService file in the `QueryResult<BaseItemDto> GetItems(GetItems request)` function. First line of that function calls the user manager to fetch the user. If no UserId is provided the user variable is set to null.
2 lines below that the `QueryResult<BaseItem> GetQueryResult(GetItems request, DtoOptions dtoOptions, User user)` is called with the user == null (because I didn't supplied a user id in the query parameters).
The line where it crashes (I guess) is line 216 (` bool isInEnabledFolder = user.Policy.EnabledFolders.Any(i => new Guid(i) == item.Id);`). Since user is null user.Policy will crash the call.

image

### PR DESCRIPTION
**Pull request by mregni**
**Changes**
I added a fallback to the rootfolder of the library when no user is passed into the GetQueryResult function. This can happen when the /Items API is called without a UserId in the query. This call was/is supported on Emby and is useful for any app that wants to display a list of items in a library without the need of a user (via API key authentication).  

**Issues**
Fixes #2246

### CODE REVIEW

**Comment by dkanada** [comment]
Wouldn't this mean that any authenticated user could query every library by removing their ID from the API call?

**Comment by mregni** [comment]
Valid point yeah, is there a way to know if the call comes from an authenticated user or a valid API key?

**Comment by PrplHaz4** [comment]
Is there a way to create an admin or Read all api key so we are not just bypassing authentication altogether?

**Comment by mregni** [comment]
Problem is that passing the API key as the UserId is not valid, I checked that with Postman. But at this moment there is no option to get all library items when you only have an API key. 

The only workaround this is then fetching all users, get the user id from an admin account and add that user to the /items API call.

**Comment by dkanada** [comment]
Someone in chat mentioned we could just use regular tokens tied to a specific user rather than API keys, which would solve the library issue.

**Comment by dkanada** [comment]
I did a bit of digging and API keys are just tokens without an associated user. The proper fix here would be to get the user ID from the session which would be null, but would also avoid any security issues.

**Pull request closed without merging**
