### PR TITLE
Migrate from IWebHost to IHost

### PR DESCRIPTION
**Pull request by crobibero**
current error:
```
[08:17:28] [FTL] [1] Main: Error while starting server.
System.InvalidOperationException: Unable to resolve service for type 'MediaBrowser.Controller.Configuration.IServerConfigurationManager' while attempting to activate 'Jellyfin.Server.Startup'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Jellyfin.Server.Program.StartApp(StartupOptions options) in C:\Code\jellyfin\Jellyfin.Server\Program.cs:line 190
```

### CODE REVIEW

**Comment by cvium** [comment]
@crobibero Status?

**Comment by crobibero** [comment]
@cvium Its been a while since I worked on this but I think this changes the pipeline order which caused DI errors. I think we should still migrate to the new host implementation but it mah require some real work

**Comment by cvium** [comment]
Shouldn't we be using https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.webapplication.createbuilder?view=aspnetcore-6.0 anyway?

**Comment by crobibero** [comment]
We should, but Serilog deprecated `UseSerilog()` on `IWebAppHostBuilder` in v5 so we need to use `IHostBuilder` if we want to continue use.

https://github.com/serilog/serilog-aspnetcore/releases/tag/v5.0.0

I spent some more time trying to get this working but I ran into the same service resolve issue

**Comment by Bond-009** [comment]
Superseded by #9078

**Pull request closed without merging**
