### PR TITLE
Make FRAME-RATE field culture invariant

### PR DESCRIPTION
**Pull request by nyanmisaka**
**Changes**
- Make FRAME-RATE field culture invariant
https://github.com/jellyfin/jellyfin/issues/3815#issuecomment-768420953

**Issues**
Should fix:
https://github.com/jellyfin/jellyfin/issues/3815

### CODE REVIEW

**Review by nielsvanvelzen — APPROVED** [review]

**Review by crobibero — APPROVED** [review]

**Review by anthonylavado — APPROVED** [review]

**Comment by nerdalertdk** [comment]
Hi

is this pushed to the unstable branch ?

**Comment by crobibero** [comment]
> Hi
> 
> is this pushed to the unstable branch ?

Yes

**Comment by nerdalertdk** [comment]
Hmm just installed latest version on the Debian unstable and I still have the issue

**Comment by crobibero** [comment]
> 
> 
> Hmm just installed latest version on the Debian unstable and I still have the issue

Please post the requested info in https://github.com/jellyfin/jellyfin/issues/3815

**Pull request merged**
