### PR TITLE
[Fix] Authentication Errors

### PR DESCRIPTION
**Pull request by BaronGreenback**
Replaced Header[] with Header.TryGetValue() as the former creates an exception if the header is not found.

This caused the authentication flow to stop if a header was not present.

eg.       
```
            if (string.IsNullOrEmpty(token))
            {
                token = headers["X-Emby-Token"];  <--- Exception created here if token not present.
            }

            if (string.IsNullOrEmpty(token))
            {
                token = headers["X-MediaBrowser-Token"];
            }
```

### CODE REVIEW

**Comment by cvium** [comment]
Hmmm? https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.iheaderdictionary.item?view=aspnetcore-5.0#Microsoft_AspNetCore_Http_IHeaderDictionary_Item_System_String_

**Comment by BaronGreenback** [comment]
Doc's be wrong! Definitely causes an exception on my pc. (Windows)

**Comment by crobibero** [comment]
Your exception must be from something else, because this authentication flow works perfectly on my PC

**Comment by BaronGreenback** [comment]
I swear this was failing this morning! I had the compiler on the code and was investigating - hence the code change.

Just come to retest - and it's working now!. WTF????

Crawling back into my cave.....

**Pull request closed without merging**
