### PR TITLE
Only delete xmltv cache file if exist

### PR DESCRIPTION
**Pull request by crobibero**
turns out that check is required

### CODE REVIEW

**Review by 1337joe — APPROVED** [review]

**Comment by cvium** [comment]
> If the file to be deleted does not exist, no exception is thrown.

https://docs.microsoft.com/en-us/dotnet/api/system.io.file.delete?view=net-6.0#remarks

Is this not true?

**Comment by Bond-009** [comment]
@cvium Maybe it's for the DirectoryNotFoundException?

https://docs.microsoft.com/en-us/dotnet/api/system.io.file.delete?view=net-6.0#exceptions

**Comment by crobibero** [comment]
Yep- looks like it is a directory issue.

```
[2022-04-19 20:00:02.452 -06:00] [ERR] [11] Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV: Error adding metadata
System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/crobibero/.cache/jellyfin/xmltv/567f2023135b42b2af376adf6b5c0c35.xml'.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider.GetXml(ListingsProviderInfo info, CancellationToken cancellationToken) in /home/crobibero/Code/jellyfin/Emby.Server.Implementations/LiveTv/Listings/XmlTvListingsProvider.cs:line 82
   at Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider.GetChannels(ListingsProviderInfo info, CancellationToken cancellationToken) in /home/crobibero/Code/jellyfin/Emby.Server.Implementations/LiveTv/Listings/XmlTvListingsProvider.cs:line 286
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.GetEpgChannels(IListingsProvider provider, ListingsProviderInfo info, Boolean enableCache, CancellationToken cancellationToken) in /home/crobibero/Code/jellyfin/Emby.Server.Implementations/LiveTv/EmbyTV/EmbyTV.cs:line 393
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.AddMetadata(IListingsProvider provider, ListingsProviderInfo info, IEnumerable`1 tunerChannels, Boolean enableCache, CancellationToken cancellationToken) in /home/crobibero/Code/jellyfin/Emby.Server.Implementations/LiveTv/EmbyTV/EmbyTV.cs:line 364
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.GetChannelsAsync(Boolean enableCache, CancellationToken cancellationToken) in /home/crobibero/Code/jellyfin/Emby.Server.Implementations/LiveTv/EmbyTV/EmbyTV.cs:line 342
```

**Review by Bond-009 — APPROVED** [review]
Maybe add a comment explaining that this can throw bc the parent dir may not exist
Otherwise I can see myself removing this by accident :p

**Pull request merged**
