### PR TITLE
Update Dockerfiles

### PR DESCRIPTION
**Pull request by nvllsvm**
**Changes**
* Use new official dotnet image paths
* Update jellyfin-web to 10.3.0-rc1

### CODE REVIEW

**Comment by cvium** [comment]
jf-web will need to be updated on every new version?

**Comment by nvllsvm** [comment]
@cvium yup. I'm open to better ideas, but separate from this PR.

**Comment by joshuaboniface** [comment]
For future updates, I'm just going to bump these at the same time I run `bump_version` in the release branch - no sense doing PRs just to update version numbers.

**Comment by nvllsvm** [comment]
Works with me.

**Pull request merged**
