### PR TITLE
Misc text changes

### PR DESCRIPTION
**Pull request by nvllsvm**

### CODE REVIEW

**Comment by anthonylavado** [comment]
A man with more free time today than me :heart:

**Comment by nvllsvm** [comment]
Git does a better job of keeping track of this than we will be able to do. 

We can use the GitHub UI:
image

Or using the git command line.
```
git shortlog --summary --numbered
```

**Comment by joshuaboniface** [comment]
That's a good point, and I agree.

**Comment by JustAMan** [comment]
Git point is only valid if all commits are authored in git by same people who wrote the commits' cidr, which might not be the case, e.g. if a change was sent as patch over email. 

It also might not work if commit authors used wrong email (i.e. not currently associated with thier github account, and people can change emails)...

**Comment by joshuaboniface** [comment]
I just sound like a yes man, but you have a good point as well. For consistency, let's just keep it with the alt format and modify it as we go.

**Comment by nvllsvm** [comment]
Removed the commit for now.

**Pull request merged**
