### PR TITLE
Remove SMB support

### PR DESCRIPTION
**Pull request by Bond-009**
This doesn't mean you can't use an SMB share to store your files for
Jellyfin. You will just have to connect to it on the OS level.

### CODE REVIEW

**Comment by anthonylavado** [comment]
Is there a UI element to remove? Is this what the "Optional Network Path" setting refers to?

**Comment by anthonylavado** [comment]
Okay, found the relevant discussion: https://matrix.to/#/!LCLiMJSFwJyNyVtqxj:matrix.org/$15465499771792ODlHJ:matrix.possumlodge.me?via=matrix.org&via=half-shot.uk&via=vscape.tk&via=dkanada.com

I would say that this is blocked until a PR changing that bit of the UI goes in.

**Comment by anthonylavado** [comment]
Okay, I've completed the change. The only problem is that I probably shouldn't be the one to review this anymore.

To reviewer: I've tested this locally and it doesn't appear to break anything.

**Comment by devenator** [comment]
WHY do you want to remove networkSharePath?!?! This is completely optional, and does not require the server to be smb://-capable (which IIRC never really worked, because it was unable to authenticate with a username/password), but just sends the native-unc path to clients like kodi, so they can access the content directly (why funnel it via jellybean-http if you don't want to use transcoding). Please don't break this functionallity!

**Comment by LeoVerto** [comment]
I agreee with @devenator, removing networkSharePath is the wrong thing to do.

To explain how this works a bit further: If this path is set, clients like Kodi that support direct-streaming of the respectively media files can request the files directly from an SMB server (usually serving the very same files Jellyfin accesses) and thus bypassing the Jellyfin server entirely. This tends to be more efficient than streaming the file over HTTP.

**Comment by EraYaN** [comment]
Right that makes a lot of sense. I also forgot that it was in addition to the local paths.

**Pull request merged**
