### PR TITLE
Move to new TVDB client

### PR DESCRIPTION
**Pull request by Bond-009**

### CODE REVIEW

**Comment by JustAMan** [comment]
Why is it still a draft?

**Comment by Bond-009** [comment]
It only implements a couple of endpoints. Do we want to migrate gradually or all at once?

**Comment by JustAMan** [comment]
What is the benefit of migration anyway? What is wrong in "old" TVDB client?

**Comment by Bond-009** [comment]
The 2.0 had issues and wasn't using the new TVDB API, but 3.0 fixes this. So at this point in time, not much.

**Pull request closed without merging**
