### PR TITLE
Ability to use DNS names in KnownProxies

### PR DESCRIPTION
**Pull request by BaronGreenback**
Just because we can ???

### CODE REVIEW

**Review by crobibero — APPROVED** [review]

**Comment by Artiume** [comment]
could this be backported?

**Review by nielsvanvelzen — APPROVED** [review]

**Comment by nielsvanvelzen** [comment]
I've marked it for backport. Core can make the final decision on it when the backporting happens.

**Comment by PrplHaz4** [comment]
> 
> 
> I've marked it for backport. Core can make the final decision on it when the backporting happens.

I don't think KnownProxies exists in 10.6.4, so that change would need to be backported too.

**Comment by crobibero** [comment]
> 
> 
> > I've marked it for backport. Core can make the final decision on it when the backporting happens.
> 
> I don't think KnownProxies exists in 10.6.4, so that change would need to be backported too.

In this instance backport refers to the 10.7 branch

**Pull request merged**
