### PR TITLE
Fix QSV hardware encoding / decoding in official Dockerfile

### PR DESCRIPTION
**Pull request by ocervell**
fixes https://github.com/jellyfin/jellyfin/issues/5993

### CODE REVIEW

**Comment by crobibero** [comment]
I don't personally have hardware that can use QSV, but as far as I know Jellyfin's ffmpeg build already provides the drivers required for iHD.

@Shadowghost 
@nyanmisaka

**Comment by martadinata666** [comment]
As the user use QSV, i can it work well `i5-8400T`, cant really tell on 10.7, as i build 10.8 from git master. Maybe some package missing on 10.7

**Comment by dlicois** [comment]
see #5993 current stable docker image doesn't work because of wrong jellyfin-ffmpeg.

Latest master docker might have fixed it already, but there is no stable image with updated jellyfin-ffmpeg.

**Review by nyanmisaka — CHANGES_REQUESTED** [review]
The iHD driver and vainfo are already a part of jellyfin-ffmpeg since [4.4.1-2](https://github.com/jellyfin/jellyfin-ffmpeg/releases/tag/v4.4.1-2).
https://github.com/jellyfin/jellyfin-ffmpeg/pull/89
https://github.com/jellyfin/jellyfin-ffmpeg/pull/93

**Comment by martadinata666** [comment]
Then should be 10.7.7 -> 10.7.8 with upgraded jellyfin? Dunno which one better, either upgrade jellyfin or add non-free driver

**Comment by crobibero** [comment]
There will be no 10.7.8. The next release is 10.8.

**Pull request closed without merging**
