### PR TITLE
Replace TagLib.Portable.dll with taglib-sharp submodule

### PR DESCRIPTION
**Pull request by Bond-009**
#4
TagLib.Portable hasn't been updated in a year and taglib-sharp supports netstandard 2.0, so it's a win win.
I would recommend cloning taglib-sharp into this origination and using that clone as a submodule, in case the original gets deleted or moved.

### CODE REVIEW

**Comment by nicman23** [comment]
hmm the thing is that the last release/tag is back on 2012. you need to use the master for formats like opus and irrc flacs. (source: i maintain aur/taglib-sharp-git) and so many distros arch included are still in the old 2012 version.

**Comment by joshuaboniface** [comment]
Before we merge, do we have a way to get this working without using Git submodules? As found in #39 some users might try to build from the archive, not the repo itself, and submodules won't work that way I don't believe. If not just ignore me and merge it ;-)

**Comment by JustAMan** [comment]
Could this be solved by making source releases?.. So users could build from "source release" instead of using "master.zip"?

**Comment by nicman23** [comment]
compiling through zip is bad anyways, the ought to shallow clone

**Comment by joshuaboniface** [comment]
Yea that's fair, we should encourage Git for self-builds.

**Comment by JustAMan** [comment]
This could be solved by a script that updates submodules if run from git repo and does a shallow clone of submodules if run from archive...

**Comment by nicman23** [comment]
people that are going to compile this beast are going to use git anyways

**Comment by PrplHaz4** [comment]
it looks like they are prepping an updated release of taglib-sharp here: https://github.com/mono/taglib-sharp/issues/60 - I'm guessing that would resolve this issue?

**Comment by Bond-009** [comment]
Yes,  we can ditch the submodule when they release a new nuget package.

**Pull request merged**
