### PR TITLE
Fix container image build by installing python

### PR DESCRIPTION
**Pull request by rigtorp**
**Changes**

Install python before building jellyfin-web

**Issues**

### CODE REVIEW

**Comment by Artiume** [comment]
So I had to update the arm dockerfiles to include python because they didn't fail the web build. Do you know why amd64 doesn't fail without python?

I also updated the arm dockerfiles by specifying `python` instead of `python2` should we go ahead and make the python version explicit in the arm dockerfiles while we're at it

**Comment by rigtorp** [comment]
Amd64 build fails if Dockerfile is not updated to install python2. So I don't understand your question?

**Comment by Artiume** [comment]
Amd64 build doesn't fail to build on my host

**Comment by rigtorp** [comment]
Maybe you have a older cached alpine image?

**Comment by Artiume** [comment]
yeah, i must've had something cached.

**Comment by JustAMan** [comment]
What component of web build needs python2?

**Comment by Artiume** [comment]
I believe @MrTimscampi can answer that

**Comment by MrTimscampi** [comment]
> What component of web build needs python2?

node-gyp, which is used by node-sass. It supports Python 3 and has for a long time now so I'm not sure why this is happening.

**Comment by rigtorp** [comment]
Installing alpine package `python` is enough. the `2` qualifier is not needed.

**Comment by JustAMan** [comment]
> Installing alpine package `python` is enough. the `2` qualifier is not needed.

Can you change the PR to install "python3" explicitly?

**Comment by rigtorp** [comment]
> > Installing alpine package `python` is enough. the `2` qualifier is not needed.
> 
> Can you change the PR to install "python3" explicitly?

That works. But for arm and arm64 we install `python`. I  suggest we use whatever alpine uses as `python`.

**Comment by Artiume** [comment]
I was able to build nightly without python for web. Did we remove any dependencies or could something be silently failing

**Comment by rigtorp** [comment]
@Artiume Odd. In any case we should try and make the Docker, Docker.arm and Docker.arm64 files more similar. See my #3067 which does that. You can check with `diff -u Dockerfile Dockerfile.arm`.

**Pull request merged**
