### PR TITLE
Fix inverted logic for LAN IP detection

### PR DESCRIPTION
**Pull request by thornbill**
**Changes**
Fixes inverted logic in detecting local ip addresses introduced in #3007.

**Issues**
Related to: #3726

### CODE REVIEW

**Comment by sparky8251** [comment]
Hrmm... I have one potential hangup with this.

Right now we consider 127.0.0.1 to be local without question, but reverse proxies can cause remote requests to appear as if they come from 127.0.0.1.

We might want to remove that particular detection line as such. Can see a lot of potential "now JF is sending too large of files and im always buffering" issues cropping up otherwise.

**Comment by Shadowghost** [comment]
This is correct, but we should make clear how to properly configure the reverse proxies to fix that. We can't take responsibility for bad reverse proxy configs by users imo.

**Comment by sparky8251** [comment]
> This is correct, but we should make clear how to properly configure the reverse proxies to fix that. We can't take responsibility for bad reverse proxy configs by users imo.

All well and good, but the linuxserver.io docker image does just this. Its not a small subset of users that will see the impact if we push this and there are unintended consequences.

It's also a security measure someone may want. Binding JF only to 127.0.0.1 and then forcing all remote traffic through an RP (which means traffic will have to look like its coming from 127.0.0.1).

Its not a simple fix because this local/remote distinction is made up. That's why its always a source of stupid issues.

**Comment by PrplHaz4** [comment]
> 
> 
> > This is correct, but we should make clear how to properly configure the reverse proxies to fix that. We can't take responsibility for bad reverse proxy configs by users imo.
> 
> All well and good, but the linuxserver.io docker image does just this. Its not a small subset of users that will see the impact if we push this and there are unintended consequences.
> 
> It's also a security measure someone may want. Binding JF only to 127.0.0.1 and then forcing all remote traffic through an RP (which means traffic will have to look like its coming from 127.0.0.1).
> 
> It's not a simple fix because this local/remote distinction is made up. That's why its always a source of stupid issues.

I don't disagree with the reasoning, but I don't think the lsio container has a default configuration that includes a RP and limits traffic to only 127.0.0.1 - can you point to where this is specified?  If it isn't that way by default somewhere, it would limit the impact of this change.

**Comment by sparky8251** [comment]
> can you point to where this is specified? If it isn't that way by default somewhere, it would limit the impact of this change.

I don't think this is relevant. Given that this has been a problem for some time and we've only had issues with truly remote clients reported (aka not plain web) its a simple single line removal to just remove 127.0.0.1 as a "local" address. The rest can stay as "local" for now until we kill the feature outright due to it being based on false assumptions.

**Comment by thornbill** [comment]
@sparky8251 I'm really only trying to restore the behaviour of 10.5.5 here to fix the issue introduced in 10.6.0. You can see [here](https://github.com/jellyfin/jellyfin/blob/v10.5.5/Emby.Server.Implementations/Networking/NetworkManager.cs#L138-L143) that we previously considered IP addresses starting with "127" as being local.

If we want to change this at some point, I don't have any objections really, but it doesn't belong in a backport imo.

**Comment by sparky8251** [comment]
Sure, I'm just suggesting that maybe it was why the `true` was changed to `false` due to some behavior  @BaronGreenback found during testing or something. 

As in, we might be reintroducing a problem in an attempt to fix one.

**Comment by PrplHaz4** [comment]
> I don't think this is relevant. 

It's only relevant to evaluating the impact of changing the behavior - breaking every single lsio install is a lot bigger deal than breaking only people who have a manually configured RP on the same host where jf is only listening on 127.0.0.1

**Comment by BaronGreenback** [comment]
More like me being a muppet - am just taking a look now.

**Pull request merged**
