### PR TITLE
Simplify code to get data dir

### PR DESCRIPTION
**Pull request by Bond-009**
Ref: https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/Environment.Unix.cs#L138
**This ignores existing installs on windows**

### CODE REVIEW

**Comment by ploughpuff** [comment]
Good find, and seems the similar is available for XDG_CONFIG_HOME with GetXdgConfig().

However, given PR #781 is making significant changes in this area it might be more prudent to wait for that to be delivered, or raise a comment over on #781 to address?

**Comment by ploughpuff** [comment]
On Windows, it's giving a slightly different result:

```
Old: "C:\\Users\\Name\\AppData\\Roaming\\jellyfin"
New: "C:\\Users\\Name\\AppData\\Local\\jellyfin"
```
and I don't know if that's a problem.  There are some comments about Roaming/Local in  https://github.com/jellyfin/jellyfin/issues/698#issuecomment-458583106

**Comment by joshuaboniface** [comment]
Do we need a migration note for this on next release though? Or will it not make a huge difference? If the whole data dir moves that might cause problems which we should address.

**Comment by JustAMan** [comment]
> Do we need a migration note for this on next release though?

I vote yes. It's as simple as "move your stuff from `%APPDATA%\jellyfin` to `%LOCALAPPDATA`\jellyfin" in the end.

**Comment by realies** [comment]
What happens with the service that is already installed and pointing at `%APPDATA\jellyfin\jellyfin.exe`?

PS: The Windows installer of `10.3.0-rc2` still defaults to the `%APPDATA%\jellyfin` location.

**Comment by anthonylavado** [comment]
Paging @logicalphallacy

**Comment by LogicalPhallacy** [comment]
The service gets its jelly all jammed up. I think I did update the installer to point to the programdata directory when doing the service install, but I'll doublecheck. The best way to do the migration if you are in place upgrading here is to create a symlink there (or an ntfs junction, either would work)

**Comment by realies** [comment]
Symlink to the new binary location is not better than updating the service itself.

**Pull request merged**
