### PR TITLE
Update artwork repository urls

### LINKED ISSUE #2567: [Enhancement] Fork Emby Studio images repo and update StudiosImageProvider
**Describe the bug**
JF pulls studio thumbs/posters from an Emby github repo. 

https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.Providers/Studios/StudiosImageProvider.cs

Current source for logos
https://github.com/MediaBrowser/Emby.Resources/tree/master/images/imagesbyname

**Expected behavior**

JF should pull studio logos from its own repo, or a 3rd party provider.

- Fork this repo.
- Update StudiosImageProvider to pull from new JF repo
- Add missing logos
- Make StudiosImageProvider a plugin

### PR DESCRIPTION
**Pull request by thornbill**
**Changes**
Removes usage of the Emby Resources repository and replaces it with the [jellyfin/emby-artwork](https://github.com/jellyfin/emby-artwork) repository

**Issues**
Fixes #2567

### CODE REVIEW

**Review by crobibero — APPROVED** [review]

**Review by anthonylavado — APPROVED** [review]

**Review by Bond-009 — APPROVED** [review]

**Review by nielsvanvelzen — COMMENTED** [review]
Should the code related to the posters be removed? The posters.txt file is empty.

**Comment by thornbill** [comment]
There is no reason why there couldn't be posters and our repository has them so... :man_shrugging:

**Comment by nielsvanvelzen** [comment]
I'm not saying we should drop the poster support entirely, just remove the functionality from the built-in studio images plugin this PR touches. The new repository you made does contain a posters.txt file but it's empty, so we're downloading a 0 byte file [^1] to then do nothing with.

[^1]: https://github.com/jellyfin/emby-artwork/blob/master/studios/posters.txt

**Comment by thornbill** [comment]
Yeah that's fair. I was being lazy. 🙃

**Pull request merged**
