### PR TITLE
Add Group visibility and Playback/Playlist Access Control to SyncPlay

### PR DESCRIPTION
**Pull request by OancaAndrei**
**Changes**
Add visibility property to SyncPlay groups:
- Public: visible and joinable by all users;
- Invite only: visible and joinable only by invited users;
- Private: visible and joinable only by the user that created it (useful for syncing personal devices).

Add Playback and Playlist Access Control that allows the Group creator to give/revoke auth on who's allowed to edit the playlist and/or control playback.

`jellyfin-web` PR [here](https://github.com/jellyfin/jellyfin-web/pull/2205).
`jellyfin-apiclient-javascript` PR [here](https://github.com/jellyfin/jellyfin-apiclient-javascript/pull/95).
Depends on #4716.

**Features being tackled in this PR**
- [x] Playback and Playlist Access Control
- [x] Group types (public, invite only, private)

### CODE REVIEW

**Comment by Uatschitchun** [comment]
Is this one related?
https://github.com/jellyfin/jellyfin/issues/5065

**Comment by OancaAndrei** [comment]
> Is this one related?
> #5065

@Uatschitchun, not really as this PR only adds admin privileges over the existing playlist code without touching it. I'll probably make a dedicated PR for #5065.

**Comment by Inverness** [comment]
Any chance of this being revived? I'm also interested in the ability to limit who can control playback in SyncPlay.

It is common in the sessions I'm a part of for watchers to accidentally pause the video, or for the video to be automatically paused briefly when someone joins the SyncPlay group. I'd like to eliminate these issues.

**Comment by barronpm** [comment]
Closing for inactivity

**Comment by Gauvino** [comment]
Really sad to see this PR closed it was one of the most important PR I wanted to be merged 😭

**Pull request closed without merging**
