### PR TITLE
Add ability for plugins to provide more complex external urls

### PR DESCRIPTION
**Pull request by crobibero**
Superceeds https://github.com/jellyfin/jellyfin/pull/7173

Note: all Trakt links will be removed until the plugin is updated.

OpenAPI changes should just be doc changes

### CODE REVIEW

**Review by 1337joe — APPROVED** [review]

**Comment by Shadowghost** [comment]
Since the trakt links do not require the plugin being installed to get the required metadata I do not like this solution in that specific case.

**Comment by SenorSmartyPants** [comment]
Any update on the status of this?

**Comment by cvium** [comment]
@crobibero Still relevant?

**Comment by crobibero** [comment]
> @crobibero Still relevant?

I think this is still relevant- some providers have more complex urls then just 1 identifier.

If you agree I will resolve conflicts

**Pull request closed without merging**
