### PR TITLE
Change initialization of root folders to app startup

### PR DESCRIPTION
**Pull request by Dangles91**
**Changes**
- Remove lazy creation of library root folders
- Remove double check locking on library roots
- Move library root references to static properties on LibraryRoot class
- Reduce dependency on LibraryManager

### CODE REVIEW

**Comment by Dangles91** [comment]
Having looked at some plugins, this would impact plugin developers.

Which leads into a larger discussion about separating the internal application structure from the plugin API.

**Comment by Shadowghost** [comment]
I can't comment on how this should be handled since my understanding is limited. Maybe @cvium or @Bond-009 can comment on if this is doable or should be done at all.
Bigger architectural changes impacting clients and the majority of plugins should be proposed as discussion in [jellyfin-meta](https://github.com/jellyfin/jellyfin-meta)

**Review by gaurovgiri — APPROVED** [review]
LGTM

**Comment by JPVenson** [comment]
Hey @Dangles91 
Please open a discussion on our meta repro. I will keep this PR open for the time being, i would however recommend you converting it into a draft until your discussion topic is resolved.

**Pull request closed without merging**
