### PR TITLE
Fix the invalid libplacebo filter option

### PR DESCRIPTION
**Pull request by nyanmisaka**
**Changes**
- Fix the invalid libplacebo filter option

**Issues**
- Fixes 0d85af019c6ebc855ab2d8e689abe72b995225b4
- Closes https://github.com/jellyfin/jellyfin/issues/12731

### CODE REVIEW

**Review by crobibero — APPROVED** [review]

**Review by gnattu — APPROVED** [review]

**Comment by ACoderGuy1002** [comment]
Thanks guys!

**Comment by ACoderGuy1002** [comment]
Just a question tho, cuz I have no idea how this works, how do I like... Get this onto my jellyfin?

**Comment by nyanmisaka** [comment]
> Just a question tho, cuz I have no idea how this works, how do I like... Get this onto my jellyfin?

Just wait for the next unstable build on Sep 30th.

**Comment by ACoderGuy1002** [comment]
> > Just a question tho, cuz I have no idea how this works, how do I like... Get this onto my jellyfin?
> 
> Just wait for the next unstable build on Sep 30th.

Neto, thanks!

**Pull request merged**
