### PR TITLE
Change log level for bind address usage to debug

### LINKED ISSUE #9024: [Issue]: Jellyfin is spamming stdout with Using BindAddress during a library scan
### Please describe your bug

I have jellyfin running in a docker container. Today I did a full library scan and told it to rebuild everything. `docker logs` is filled with this:

```
[17:59:26] [INF] [104] Jellyfin.Networking.Manager.NetworkManager: 192.168.32.28/32: Using BindAddress https://jellyfin.redacted.net:null
[17:59:26] [INF] [104] Jellyfin.Networking.Manager.NetworkManager: 192.168.32.28/32: Using BindAddress https://jellyfin.redacted.net:null
[17:59:26] [INF] [55] Jellyfin.Networking.Manager.NetworkManager: 192.168.32.28/32: Using BindAddress https://jellyfin.redacted.net:null
[17:59:26] [INF] [55] Jellyfin.Networking.Manager.NetworkManager: 192.168.32.28/32: Using BindAddress https://jellyfin.redacted.net:null
[17:59:27] [INF] [55] Jellyfin.Networking.Manager.NetworkManager: 192.168.32.28/32: Using BindAddress https://jellyfin.redacted.net:null
[17:59:27] [INF] [55] Jellyfin.Networking.Manager.NetworkManager: 192.168.32.28/32: Using BindAddress https://jellyfin.redacted.net:null
[17:59:27] [INF] [55] Jellyfin.Networking.Manager.NetworkManager: 192.168.32.28/32: Using BindAddress https://jellyfin.redacted.net:null
```

### Jellyfin Version

10.8.0

### if other:

_No response_

### Environment

```markdown
- OS:
- Virtualization: Docker
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

_No response_

### FFmpeg logs

_No response_

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by barronpm**
Fixes #9024

### CODE REVIEW

**Comment by crobibero** [comment]
I think this only fixes the symptom, not the actual issue.. iirc the issue is that the network list that Jellyfin can bind to keeps changing

**Comment by barronpm** [comment]
Based on the logs, and a quick look through the NetworkManager class, it seems like the problem is that something keeps calling this method, so even for the same source IP, this method gets called repeatedly. Admittedly, it would probably be better to find out where this is happening and look into caching the result, but for now I'm trying to minimize conflicts with #8147. Is there a GitHub issue showing that particular bug?

**Comment by Shadowghost** [comment]
From experience the reason this gets spammed is a failing and restarting docker container.

**Comment by barronpm** [comment]
Unless the issue author cut out other logs, that shouldn't be the case since there is no exception/startup logs

**Comment by fhriley** [comment]
I can provide some color now that I understand where the log message is coming from. I have a scraper that scrapes from Jellyfin. It determines if it needs to log in (since login is expensive) by hitting the system info api endpoint. If it gets a 401, it needs to log in. If not, it can use its existing token. Thus, the spamming was because my scraper was calling that endpoint a lot.

**Review by crobibero — APPROVED** [review]

**Review by Bond-009 — APPROVED** [review]

**Pull request merged**
