### PR TITLE
Move to .Net Core 3.1

### PR DESCRIPTION
**Pull request by Bond-009**

### CODE REVIEW

**Comment by grafixeyehero** [comment]
@Bond-009 don't forget to update vsc workspace too

**Comment by dkanada** [comment]
The dotnet variable was just added to some Ubuntu builds as well.

**Comment by EraYaN** [comment]
Do we also want to move to .NET Standard 2.1?

**Comment by Bond-009** [comment]
@EraYaN I think most projects already target 2.1

**Pull request merged**
