### PR TITLE
Fix missing colons

### PR DESCRIPTION
**Pull request by balu92**
**Changes**
Added missing colons to the default profile's ProtocolInfo string and any other profile that inherits it.

### CODE REVIEW

**Comment by mark-monteiro** [comment]
@balu92 Can you provide some more details on the issue this solves and maybe a before/after test case we can use to review it?

**Comment by balu92** [comment]
Page 109-110 in [An Introduction to the DLNA Architecture: Network Technologies for Media Devices](https://books.google.co.uk/books?id=Fi2odmEuZpsC&pg=PA109&lpg=PA109&dq=http+get+protocolinfo+example&source=bl&ots=rIBuwh4eIB&sig=ACfU3U3BXBamfKB-p7FNg4wfCFX1v7cDxQ&hl=en&sa=X&ved=2ahUKEwi_3PLU6IDpAhWhwjgGHQVoB-gQ6AEwAHoECAcQAQ#v=onepage&q&f=false)

The correct format for the protocol info is: `http-get:*:<MIME type>:*`
For example: `http-get:*:image/jpeg:*`
But instead in the code it looks like: `http-get:*image/jpeg:*` (missing colon before the mime type)

protocolInfo

**Comment by joshuaboniface** [comment]
@balu92 Has this been tested and confirmed to both (a) work correctly, and (b) not cause any unintended issues?

**Comment by balu92** [comment]
From my limited testing it seems to work as intended. It's mostly image mime types and the wma audio format, don't have any wma audio or an image library, so I shared my meme folder which luckily has some gifs, pngs and jpegs and after applying this change I saw more of the images. The dlna software I used don't support gifs, so those were converted to still jpegs.

**Pull request merged**
