### PR TITLE
HDHomeRun - Fix incorrect starting offset of buffer span in CheckTunerAvailability.

### LINKED ISSUE #7154: [Issue]: LiveTV playback with HDHomerun HDHR-US fails
### Please describe your bug

Go to LiveTV in Main UI, select Guide and then Click a channel. Wait circle displays but noting happens. Exception generated in the log.

### Jellyfin Version

Other

### if other:

10.8.0.1-unstable asof 01/10/2022

### Environment

```markdown
- OS: Mint UMA
- Virtualization: None
- Clients:Browser
- Browser: Brave
- FFmpeg Version: 4.3.2-1
- Playback Method: Browser
- Hardware Acceleration: none
- Plugins: none
- Reverse Proxy: none
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
Jan 10 11:45:22 Mint-Hp jellyfin[1513052]: [11:45:22] [INF] GetPostedPlaybackInfo profile: {"Name": null, "Id": null, "Identification": null, "FriendlyName": null, "Manufacturer": null, "ManufacturerUrl": null, "ModelName": null, "ModelDescription": null, "ModelNumber": null, "ModelUrl": null, "SerialNumber": null, "EnableAlbumArtInDidl": false, "EnableSingleAlbumArtLimit": false, "EnableSingleSubtitleLimit": false, "SupportedMediaTypes": "Audio,Photo,Video", "UserId": null, "AlbumArtPn": null, "MaxAlbumArtWidth": null, "MaxAlbumArtHeight": null, "MaxIconWidth": null, "MaxIconHeight": null, "MaxStreamingBitrate": 120000000, "MaxStaticBitrate": 100000000, "MusicStreamingTranscodingBitrate": 384000, "MaxStaticMusicBitrate": 8000000, "SonyAggregationFlags": null, "ProtocolInfo": null, "TimelineOffsetSeconds": 0, "RequiresPlainVideoItems": false, "RequiresPlainFolders": false, "EnableMSMediaReceiverRegistrar": false, "IgnoreTranscodeByteRangeRequests": false, "XmlRootAttributes": [], "DirectPlayProfiles": [{"Container": "webm", "AudioCodec": "vorbis,opus", "VideoCodec": "vp8,vp9,av1", "Type": "Video", "$type": "DirectPlayProfile"}, {"Container": "mp4,m4v", "AudioCodec": "aac,mp3,opus,flac,vorbis", "VideoCodec": "h264,vp8,vp9,av1", "Type": "Video", "$type": "DirectPlayProfile"}, {"Container": "mov", "AudioCodec": "aac,mp3,opus,flac,vorbis", "VideoCodec": "h264", "Type": "Video", "$type": "DirectPlayProfile"}, {"Container": "opus", "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "webm", "AudioCodec": "opus", "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "mp3", "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "aac", "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "m4a", "AudioCodec": "aac", "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "m4b", "AudioCodec": "aac", "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "flac", "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "webma", "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "webm", "AudioCodec": "webma", "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "wav", "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "ogg", "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}], "TranscodingProfiles": [{"Container": "ts", "Type": "Audio", "VideoCodec": "", "AudioCodec": "aac", "Protocol": "hls", "EstimateContentLength": false, "EnableMpegtsM2TsMode": false, "TranscodeSeekInfo": "Auto", "CopyTimestamps": false, "Context": "Streaming", "EnableSubtitlesInManifest": false, "MaxAudioChannels": "6", "MinSegments": 1, "SegmentLength": 0, "BreakOnNonKeyFrames": true, "$type": "TranscodingProfile"}, {"Container": "aac", "Type": "Audio", "VideoCodec": "", "AudioCodec": "aac", "Protocol": "http", "EstimateContentLength": false, "EnableMpegtsM2TsMode": false, "TranscodeSeekInfo": "Auto", "CopyTimestamps": false, "Context": "Streaming", "EnableSubtitlesInManifest": false, "MaxAudioChannels": "6", "MinSegments": 0, "SegmentLength": 0, "BreakOnNonKeyFrames": false, "$type": "TranscodingProfile"}, {"Container": "mp3", "Type": "Audio", "VideoCodec": "", "AudioCodec": "mp3", "Protocol": "http", "EstimateContentLength": false, "EnableMpegtsM2TsMode": false, "TranscodeSeekInfo": "Auto", "CopyTimestamps": false, "Context": "Streaming", "EnableSubtitlesInManifest": false, "MaxAudioChannels": "6", "MinSegments": 0, "SegmentLength": 0, "BreakOnNonKeyFrames": false, "$type": "TranscodingProfile"}, {"Container": "opus", "Type": "Audio", "VideoCodec": "", "AudioCodec": "opus", "Protocol": "http", "EstimateContentLength": false, "EnableMpegtsM2TsMode": false, "TranscodeSeekInfo": "Auto", "CopyTimestamps": false, "Context": "Streaming", "EnableSubtitlesInManifest": false, "MaxAudioChannels": "6", "MinSegments": 0, "SegmentLength": 0, "BreakOnNonKeyFrames": false, "$type": "TranscodingProfile"}, {"Container": "wav", "Type": "Audio", "VideoCodec": "", "AudioCodec": "wav", "Protocol": "http", "EstimateContentLength": false, "EnableMpegtsM2TsMode": false, "TranscodeSeekInfo": "Auto", "CopyTimestamps": false, "Context": "Streaming", "EnableSubtitlesInManifest": false, "MaxAudioChannels": "6", "MinSegments": 0, "SegmentLength": 0, "BreakOnNonKeyFrames": false, "$type": "TranscodingProfile"}, {"Container": "opus", "Type": "Audio", "VideoCodec": "", "AudioCodec": "opus", "Protocol": "http", "EstimateContentLength": false, "EnableMpegtsM2TsMode": false, "TranscodeSeekInfo": "Auto", "CopyTimestamps": false, "Context": "Static", "EnableSubtitlesInManifest": false, "MaxAudioChannels": "6", "MinSegments": 0, "SegmentLength": 0, "BreakOnNonKeyFrames": false, "$type": "TranscodingProfile"}, {"Container": "mp3", "Type": "Audio", "VideoCodec": "", "AudioCodec": "mp3", "Protocol": "http", "EstimateContentLength": false, "EnableMpegtsM2TsMode": false, "TranscodeSeekInfo": "Auto", "CopyTimestamps": false, "Context": "Static", "EnableSubtitlesInManifest": false, "MaxAudioChannels": "6", "MinSegments": 0, "SegmentLength": 0, "BreakOnNonKeyFrames": false, "$type": "TranscodingProfile"}, {"Container": "aac", "Type": "Audio", "VideoCodec": "", "AudioCodec": "aac", "Protocol": "http", "EstimateContentLength": false, "EnableMpegtsM2TsMode": false, "TranscodeSeekInfo": "Auto", "CopyTimestamps": false, "Context": "Static", "EnableSubtitlesInManifest": false, "MaxAudioChannels": "6", "MinSegments": 0, "SegmentLength": 0, "BreakOnNonKeyFrames": false, "$type": "TranscodingProfile"}, {"Container": "wav", "Type": "Audio", "VideoCodec": "", "AudioCodec": "wav", "Protocol": "http", "EstimateContentLength": false, "EnableMpegtsM2TsMode": false, "TranscodeSeekInfo": "Auto", "CopyTimestamps": false, "Context": "Static", "EnableSubtitlesInManifest": false, "MaxAudioChannels": "6", "MinSegments": 0, "SegmentLength": 0, "BreakOnNonKeyFrames": false, "$type": "TranscodingProfile"}, {"Container": "ts", "Type": "Video", "VideoCodec": "h264", "AudioCodec": "aac,mp3", "Protocol": "hls", "EstimateContentLength": false, "EnableMpegtsM2TsMode": false, "TranscodeSeekInfo": "Auto", "CopyTimestamps": false, "Context": "Streaming", "EnableSubtitlesInManifest": false, "MaxAudioChannels": "6", "MinSegments": 1, "SegmentLength": 0, "BreakOnNonKeyFrames": true, "$type": "TranscodingProfile"}, {"Container": "webm", "Type": "Video", "VideoCodec": "vp8,vp9,av1,vpx", "AudioCodec": "vorbis,opus", "Protocol": "http", "EstimateContentLength": false, "EnableMpegtsM2TsMode": false, "TranscodeSeekInfo": "Auto", "CopyTimestamps": false, "Context": "Streaming", "EnableSubtitlesInManifest": false, "MaxAudioChannels": "6", "MinSegments": 0, "SegmentLength": 0, "BreakOnNonKeyFrames": false, "$type": "TranscodingProfile"}, {"Container": "mp4", "Type": "Video", "VideoCodec": "h264", "AudioCodec": "aac,mp3,opus,flac,vorbis", "Protocol": "http", "EstimateContentLength": false, "EnableMpegtsM2TsMode": false, "TranscodeSeekInfo": "Auto", "CopyTimestamps": false, "Context": "Static", "EnableSubtitlesInManifest": false, "MaxAudioChannels": null, "MinSegments": 0, "SegmentLength": 0, "BreakOnNonKeyFrames": false, "$type": "TranscodingProfile"}], "ContainerProfiles": [], "CodecProfiles": [{"Type": "VideoAudio", "Conditions": [{"Condition": "Equals", "Property": "IsSecondaryAudio", "Value": "false", "IsRequired": false, "$type": "ProfileCondition"}], "ApplyConditions": [], "Codec": "aac", "Container": null, "$type": "CodecProfile"}, {"Type": "VideoAudio", "Conditions": [{"Condition": "Equals", "Property": "IsSecondaryAudio", "Value": "false", "IsRequired": false, "$type": "ProfileCondition"}], "ApplyConditions": [], "Codec": null, "Container": null, "$type": "CodecProfile"}, {"Type": "Video", "Conditions": [{"Condition": "NotEquals", "Proper
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]: [11:45:23] [DBG] MediaSources: [{"Protocol": "Udp", "Id": "native_dcae7ee91da8349d9a3089106668280d_02ef21764a3ac92a8b773bffe9ba8849", "Path": "http://192.168.14.33", "EncoderPath": null, "EncoderProtocol": null, "Type": "Default", "Container": "ts", "Size": null, "Name": null, "IsRemote": false, "ETag": null, "RunTimeTicks": null, "ReadAtNativeFramerate": false, "IgnoreDts": true, "IgnoreIndex": false, "GenPtsInput": false, "SupportsTranscoding": true, "SupportsDirectStream": true, "SupportsDirectPlay": false, "IsInfiniteStream": true, "RequiresOpening": true, "OpenToken": "LiveTvChannel_4929c8bbc7e9cd2cd4d28471be53a7a5_native_dcae7ee91da8349d9a3089106668280d_02ef21764a3ac92a8b773bffe9ba8849", "RequiresClosing": true, "LiveStreamId": null, "BufferMs": 0, "RequiresLooping": false, "SupportsProbing": true, "VideoType": null, "IsoType": null, "Video3DFormat": null, "MediaStreams": [{"Codec": null, "CodecTag": null, "Language": null, "ColorRange": null, "ColorSpace": null, "ColorTransfer": null, "ColorPrimaries": null, "Comment": null, "TimeBase": null, "CodecTimeBase": null, "Title": null, "VideoRange": "SDR", "LocalizedUndefined": null, "LocalizedDefault": null, "LocalizedForced": null, "DisplayTitle": "SDR", "NalLengthSize": null, "IsInterlaced": true, "IsAVC": null, "ChannelLayout": null, "BitRate": 2000000, "BitDepth": null, "RefFrames": null, "PacketLength": null, "Channels": null, "SampleRate": null, "IsDefault": false, "IsForced": false, "Height": null, "Width": null, "AverageFrameRate": null, "RealFrameRate": null, "Profile": null, "Type": "Video", "AspectRatio": null, "Index": -1, "Score": null, "IsExternal": false, "DeliveryMethod": null, "DeliveryUrl": null, "IsExternalUrl": null, "IsTextSubtitleStream": false, "SupportsExternalStream": false, "Path": null, "PixelFormat": null, "Level": null, "IsAnamorphic": null, "$type": "MediaStream"}, {"Codec": null, "CodecTag": null, "Language": null, "ColorRange": null, "ColorSpace": null, "ColorTransfer": null, "ColorPrimaries": null, "Comment": null, "TimeBase": null, "CodecTimeBase": null, "Title": null, "VideoRange": null, "LocalizedUndefined": null, "LocalizedDefault": null, "LocalizedForced": null, "DisplayTitle": "", "NalLengthSize": null, "IsInterlaced": false, "IsAVC": null, "ChannelLayout": null, "BitRate": 192000, "BitDepth": null, "RefFrames": null, "PacketLength": null, "Channels": null, "SampleRate": null, "IsDefault": false, "IsForced": false, "Height": null, "Width": null, "AverageFrameRate": null, "RealFrameRate": null, "Profile": null, "Type": "Audio", "AspectRatio": null, "Index": -1, "Score": null, "IsExternal": false, "DeliveryMethod": null, "DeliveryUrl": null, "IsExternalUrl": null, "IsTextSubtitleStream": false, "SupportsExternalStream": false, "Path": null, "PixelFormat": null, "Level": null, "IsAnamorphic": null, "$type": "MediaStream"}], "MediaAttachments": [], "Formats": [], "Bitrate": 2192000, "Timestamp": null, "RequiredHttpHeaders": {}, "TranscodingUrl": null, "TranscodingSubProtocol": null, "TranscodingContainer": null, "AnalyzeDurationMs": null, "TranscodeReasons": null, "DefaultAudioStreamIndex": null, "DefaultSubtitleStreamIndex": null, "VideoStream": {"Codec": null, "CodecTag": null, "Language": null, "ColorRange": null, "ColorSpace": null, "ColorTransfer": null, "ColorPrimaries": null, "Comment": null, "TimeBase": null, "CodecTimeBase": null, "Title": null, "VideoRange": "SDR", "LocalizedUndefined": null, "LocalizedDefault": null, "LocalizedForced": null, "DisplayTitle": "SDR", "NalLengthSize": null, "IsInterlaced": true, "IsAVC": null, "ChannelLayout": null, "BitRate": 2000000, "BitDepth": null, "RefFrames": null, "PacketLength": null, "Channels": null, "SampleRate": null, "IsDefault": false, "IsForced": false, "Height": null, "Width": null, "AverageFrameRate": null, "RealFrameRate": null, "Profile": null, "Type": "Video", "AspectRatio": null, "Index": -1, "Score": null, "IsExternal": false, "DeliveryMethod": null, "DeliveryUrl": null, "IsExternalUrl": null, "IsTextSubtitleStream": false, "SupportsExternalStream": false, "Path": null, "PixelFormat": null, "Level": null, "IsAnamorphic": null, "$type": "MediaStream"}, "$type": "MediaSourceInfo"}]
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]: [11:45:23] [INF] User policy for bsamuels. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]: [11:45:23] [DBG] Profile: Unknown Profile, Path: http://192.168.14.33, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]: [11:45:23] [DBG] Container: ts, Video: no video, Audio: no audio cannot be direct played by profile: unknown profile for path: http://192.168.14.33
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]: [11:45:23] [DBG] Profile: Unknown Profile, Path: http://192.168.14.33, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]: [11:45:23] [DBG] Container: ts, Video: no video, Audio: no audio cannot be direct played by profile: unknown profile for path: http://192.168.14.33
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]: [11:45:23] [INF] Opening channel stream from Emby, external channel Id: hdhr_4.1
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]: [11:45:23] [INF] Streaming Channel hdhr_4.1
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]: [11:45:23] [INF] GetChannelStream: channel id: hdhr_4.1. stream id: native_dcae7ee91da8349d9a3089106668280d_02ef21764a3ac92a8b773bffe9ba8849 profile: native
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]: [11:45:23] [INF] Opening HDHR UDP Live stream from 192.168.14.33
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]: [11:45:23] [ERR] Error opening live stream:
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]: MediaBrowser.Controller.LiveTv.LiveTvConflictException: Exception of type 'MediaBrowser.Controller.LiveTv.LiveTvConflictException' was thrown.
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Emby.Server.Implementations.LiveTv.TunerHosts.HdHomerun.HdHomerunManager.StartStreaming(IPAddress remoteIp, IPAddress localIp, Int32 localPort, IHdHomerunChannelCommands commands, Int32 numTuners, CancellationToken cancellationToken)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Emby.Server.Implementations.LiveTv.TunerHosts.HdHomerun.HdHomerunUdpStream.Open(CancellationToken openCancellationToken)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]: [11:45:23] [ERR] Error opening tuner
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]: MediaBrowser.Controller.LiveTv.LiveTvConflictException: Exception of type 'MediaBrowser.Controller.LiveTv.LiveTvConflictException' was thrown.
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Emby.Server.Implementations.LiveTv.TunerHosts.HdHomerun.HdHomerunManager.StartStreaming(IPAddress remoteIp, IPAddress localIp, Int32 localPort, IHdHomerunChannelCommands commands, Int32 numTuners, CancellationToken cancellationToken)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Emby.Server.Implementations.LiveTv.TunerHosts.HdHomerun.HdHomerunUdpStream.Open(CancellationToken openCancellationToken)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Emby.Server.Implementations.LiveTv.TunerHosts.BaseTunerHost.GetChannelStream(String channelId, String streamId, List`1 currentLiveStreams, CancellationToken cancellationToken)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]: [11:45:23] [ERR] Error processing request. URL POST /Items/4929c8bbc7e9cd2cd4d28471be53a7a5/PlaybackInfo.
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]: MediaBrowser.Controller.LiveTv.LiveTvConflictException: Exception of type 'MediaBrowser.Controller.LiveTv.LiveTvConflictException' was thrown.
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Emby.Server.Implementations.LiveTv.TunerHosts.BaseTunerHost.GetChannelStream(String channelId, String streamId, List`1 currentLiveStreams, CancellationToken cancellationToken)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.GetChannelStreamWithDirectStreamProvider(String channelId, String streamId, List`1 currentLiveStreams, CancellationToken cancellationToken)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Emby.Server.Implementations.LiveTv.LiveTvManager.GetChannelStream(String id, String mediaSourceId, List`1 currentLiveStreams, CancellationToken cancellationToken)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Emby.Server.Implementations.LiveTv.LiveTvMediaSourceProvider.OpenMediaSource(String openToken, List`1 currentLiveStreams, CancellationToken cancellationToken)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Emby.Server.Implementations.Library.MediaSourceManager.OpenLiveStreamInternal(LiveStreamRequest request, CancellationToken cancellationToken)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Emby.Server.Implementations.Library.MediaSourceManager.OpenLiveStream(LiveStreamRequest request, CancellationToken cancellationToken)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Jellyfin.Api.Helpers.MediaInfoHelper.OpenMediaSource(HttpRequest httpRequest, LiveStreamRequest request)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Jellyfin.Api.Controllers.MediaInfoController.GetPostedPlaybackInfo(Guid itemId, Nullable`1 userId, Nullable`1 maxStreamingBitrate, Nullable`1 startTimeTicks, Nullable`1 audioStreamIndex, Nullable`1 subtitleStreamIndex, Nullable`1 maxAudioChannels, String mediaSourceId, String liveStreamId, Nullable`1 autoOpenLiveStream, Nullable`1 enableDirectPlay, Nullable`1 enableDirectStream, Nullable`1 enableTranscoding, Nullable`1 allowVideoStreamCopy, Nullable`1 allowAudioStreamCopy, PlaybackInfoDto playbackInfoDto)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at lambda_method1117(Closure , Object )
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]:    at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
Jan 10 11:45:23 Mint-Hp jellyfin[1513052]: [11:45:23] [WRN] Slow HTTP Response from http://192.168.14.230:8096/Items/4929c8bbc7e9cd2cd4d28471be53a7a5/PlaybackInfo?UserId=4b2f2e092c98447e8fedbaacfc6e2285&StartTimeTicks=0&IsPlayback=true&AutoOpenLiveStream=true&MaxStreamingBitrate=140000000 to 192.168.14.230 in 0:00:00.810119 with Status Code 500
```

### FFmpeg logs

_No response_

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by swedishborgie**
CheckTunerAvailability creates a span from a buffer to pass to the validation function. It appears to be incorrectly using the length as the starting index which is causing the tuner initialization to fail. Fixing this resolved the issue I was having with my HDHR3-US.

Please let me if you would like any additional  changes  or testing done.

Fixes #7154

### CODE REVIEW

**Review by Bond-009 — APPROVED** [review]
Thx, looks like I messed that up almost 2years ago

**Review by cvium — APPROVED** [review]

**Comment by Bond-009** [comment]
@swedishborgie could you dump the response of your tuner so I can write a regression test for this?

**Comment by swedishborgie** [comment]
Sure thing! I've attached a dump of the response going into the verify for `CheckTunerAvailability()`. Here's the response from a HDHR3-US:
image
[tuner_lockkey.txt](https://github.com/jellyfin/jellyfin/files/9991060/tuner_lockkey.txt)

**Comment by GodlyOverlord** [comment]
Hi

I've got a HDHR3-DT tuner thats throwing the same livetvconflictexception errors when attempting to loading a livetv stream.
Unit is latest firmware and my jellyfin install is a brand new fresh Docker install on 10.8.8

Any channel i attempt to start, it throws 
`[2023-01-06 22:57:54.862 +11:00] [INF] [21] Emby.Server.Implementations.LiveTv.LiveTvManager: Opening channel stream from "Emby", external channel Id: "hdhr_26"
[2023-01-06 22:57:54.862 +11:00] [INF] [21] Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV: Streaming Channel "hdhr_26"
[2023-01-06 22:57:54.862 +11:00] [INF] [21] Emby.Server.Implementations.LiveTv.TunerHosts.HdHomerun.HdHomerunHost: GetChannelStream: channel id: "hdhr_26". stream id: "native_bc93a813083fd27724af0d73de3f0359_3c030cd34cf84e59e94182fe6c2f1b7b" profile: "native"
[2023-01-06 22:57:54.863 +11:00] [INF] [21] Emby.Server.Implementations.LiveTv.TunerHosts.HdHomerun.HdHomerunHost: Opening HDHR UDP Live stream from "192.168.1.213"
[2023-01-06 22:57:54.899 +11:00] [ERR] [21] Emby.Server.Implementations.LiveTv.TunerHosts.HdHomerun.HdHomerunHost: Error opening live stream:
MediaBrowser.Controller.LiveTv.LiveTvConflictException: Exception of type 'MediaBrowser.Controller.LiveTv.LiveTvConflictException' was thrown.`

**Comment by cvium** [comment]
But this PR isn't in 10.8

**Pull request merged**
