### PR TITLE
Remove ogg video mimetype

### PR DESCRIPTION
**Pull request by Artiume**
**Changes**

**Issues**

### CODE REVIEW

**Comment by cromefire** [comment]
Is there a reason for removing this? Ogg can contain video and `video/ogg` is valid, it's extension would be `.ogv` in that case

**Comment by Bond-009** [comment]
If you looks at the diff, that's already included `{ ".ogv", "video/ogg" },`

**Comment by cromefire** [comment]
Oh I totally searched it and haven't seen it nontheless

**Comment by Artiume** [comment]
The reason for removing was because .ogg already has a mimetype at LOC137 for audio. This caused the server to crash on startup when I implemented #3050

**Pull request merged**
