### PR TITLE
Use filtered codecs to build appliedConditions

### PR DESCRIPTION
**Pull request by nyanmisaka**
Based on the new suggestions here. https://github.com/jellyfin/jellyfin/pull/12521#discussion_r1740054405

**Changes**
- Use filtered codecs to build appliedConditions

### CODE REVIEW

**Review by Shadowghost — APPROVED** [review]

**Review by Bond-009 — APPROVED** [review]

**Comment by dmitrylyzo** [comment]
I'm not subscribed and continue posting on that PR. 😅

Also, here https://github.com/jellyfin/jellyfin/blob/2fe13f54eaf87eefefd27f4ccb2ace1371f5e886/MediaBrowser.Model/Dlna/StreamBuilder.cs#L907
and here
https://github.com/jellyfin/jellyfin/blob/2fe13f54eaf87eefefd27f4ccb2ace1371f5e886/MediaBrowser.Model/Dlna/StreamBuilder.cs#L

Or maybe just assign it back?
```cs
videoCodec = playlistItem.VideoCodecs;
audioCodec = playlistItem.AudioCodecs;
```

**Comment by nyanmisaka** [comment]
> ```cs
> videoCodec = playlistItem.VideoCodecs;
> audioCodec = playlistItem.AudioCodecs;
> ```

One is a string and the other is a string array. How about using `videoCodecs` and `audioCodecs`?

**Comment by dmitrylyzo** [comment]
> One is a string and the other is a string array. How about using `videoCodecs` and `audioCodecs`?

Would work.
We need to assign `audioCodecs` after this line
https://github.com/jellyfin/jellyfin/blob/073d93cd0f1543c24c3471bc507fad8729fd661d/MediaBrowser.Model/Dlna/StreamBuilder.cs#L861

**Comment by nyanmisaka** [comment]
> > One is a string and the other is a string array. How about using `videoCodecs` and `audioCodecs`?
> 
> Would work. We need to assign `audioCodecs` after this line
> 
> https://github.com/jellyfin/jellyfin/blob/073d93cd0f1543c24c3471bc507fad8729fd661d/MediaBrowser.Model/Dlna/StreamBuilder.cs#L861

Done.

**Review by dmitrylyzo — APPROVED** [review]
LGTM.
Also optimized by omitting `SplitValue`. 👍

**Review by cvium — APPROVED** [review]

**Pull request merged**
