### PR TITLE
Fix extras folders

### PR DESCRIPTION
**Pull request by cvium**
Fixed "trailers", theme song and theme videos.

### CODE REVIEW

**Review by crobibero — APPROVED** [review]

**Review by 1337joe — APPROVED** [review]
Approved because it now picks up trailers, though in testing I noticed that running Refresh Metadata on a movie doesn't chain down to trailers and extras, which should be picked up as owned items.

**Comment by cvium** [comment]
> I noticed that running Refresh Metadata on a movie doesn't chain down to trailers and extras

What do you mean? When I refresh a movie it calls `RefreshExtras`.

**Comment by 1337joe** [comment]
> What do you mean? When I refresh a movie it calls `RefreshExtras`.

I guess it's kind of hard to see the effect, try these steps:
1. Open a movie that has extras
2. Video extras will have screenshots from the video as their cover image - edit images for the extras and delete the images
3. Refresh the page - the cover image will revert to art from the parent movie, typically the backdrop image I believe
4. On the movie, Refresh Metadata > Mode: Replace All Metadata, Replace Existing Images: true
5. Wait for the refresh job to finish, then refresh the page again - the extras will not have re-extracted their cover images

Alternately, set a breakpoint in `ProviderManager.GetMetadataProvidersInternal` and you can directly see that metadata providers are only queried for the Movie, not any of the extras/trailers/etc.

**Comment by cvium** [comment]
> > What do you mean? When I refresh a movie it calls `RefreshExtras`.
> 
> 
> 
> I guess it's kind of hard to see the effect, try these steps:
> 
> 1. Open a movie that has extras
> 
> 2. Video extras will have screenshots from the video as their cover image - edit images for the extras and delete the images
> 
> 3. Refresh the page - the cover image will revert to art from the parent movie, typically the backdrop image I believe
> 
> 4. On the movie, Refresh Metadata > Mode: Replace All Metadata, Replace Existing Images: true
> 
> 5. Wait for the refresh job to finish, then refresh the page again - the extras will not have re-extracted their cover images
> 
> 
> 
> Alternately, set a breakpoint in `ProviderManager.GetMetadataProvidersInternal` and you can directly see that metadata providers are only queried for the Movie, not any of the extras/trailers/etc.

Is this because of my changes or does 10.7 behave the same way?

**Comment by 1337joe** [comment]
10.7 refreshes metadata for all items under the movie. 

It looks like your changes: when I restore the `RefreshedOwnedItems` override that you deleted from `Movie` it works like it used to.

**Review by 1337joe — APPROVED** [review]

**Review by Bond-009 — APPROVED** [review]

**Pull request merged**
