### PR TITLE
Port Activity Database to EFCore

### PR DESCRIPTION
**Pull request by barronpm**
**Changes**
Creates a model in EFCore for the Activity database. Nothing is using the new code yet, this is just adding the initial implementation of EFCore.

### CODE REVIEW

**Comment by barronpm** [comment]
schema
This is the schema as it is now.

**Comment by dkanada** [comment]
We could technically port the activity database now since it gets managed separately.

**Comment by barronpm** [comment]
> 
> 
> We could technically port the activity database now since it gets managed separately.

I'm working on that already, @sparky8251 asked me to open this PR as-is

**Comment by dkanada** [comment]
Actually, since you're not actually implementing the database here you'd want to PR this against the existing branch that has these changes. If you split the ActivityLog implementation out and actually commit the generated code, then you would actually want to target master.

**Comment by sparky8251** [comment]
He is dkanada. Working on some more stuff on the side and this should at least wait to merge until its accompanying PR exists.

I'm unsure if he can push directly to the other PR for this only because he isn't a maintainer. But if you want to close this and do that, I can at least force his fork into that PR even if he cant.

**Comment by barronpm** [comment]
This PR is no longer necessary, as the new branch I am working on will completely port the activity db, closing

**Pull request closed without merging**
