### PR TITLE
Fix broken pin in 10.3.z

### PR DESCRIPTION
**Pull request by DrPandemic**
**Changes**

The new `EasyPassword` format contains the hash and the hashing function. This PR uses the `PasswordHash` to extract the actual hash.

**Issues**
Closes https://github.com/jellyfin/jellyfin/issues/1326

Maybe helps https://github.com/jellyfin/jellyfin/issues/1329 but not 100% sure.

### CODE REVIEW

**Comment by joern-h** [comment]
`PasswordHash` crashes with bytestring from `EasyPassword`
This leads to the issues.

`ChangeEasyPassword` sets `EasyPassword` to a bytestring from `_defaultAuthenticationProvider.GetHashedString(user, newPassword);`

**Comment by anthonylavado** [comment]
@joern-h Could you clarify what you mean?

**Comment by joern-h** [comment]
Sure, let me explain:

When you set a new pin `Emby.Server.Implementations/Library/UserManager.cs:ChangeEasyPassword` gets called with parameters user, newPassword, newPasswordHash
Example: `newPassword="1234" newPasswordHash="" `

Then `_defaultAuthenticationProvider.GetHashedString(user, newPassword);` is called, which returns a bytestring, in my example: `newPasswordHash="C34DBFAB1E982D1B398D9B7F225F453566CA61AA7093160B2A96B5A328B6D02F"`

The function sets `user.EasyPassword` to `newPasswordHash` and updates the user. 

This raises the `Emby.Server.Implementations.EntryPoints.ServerEventNotifier.userManager_UserUpdated` event, which calls `Emby.Server.Implementations.Library.UserManager.GetUserDto`

This calls `Emby.Server.Implementations.Library.UserManager.GetLocalPasswordHash(User user)` 

`private string GetLocalPasswordHash(User user)
        {
            return string.IsNullOrEmpty(user.EasyPassword)
                ? null
                : (new PasswordHash(user.EasyPassword)).Hash; 
        }`
Evaluates to: `return new PasswordHash("C34DBFAB1E982D1B398D9B7F225F453566CA61AA7093160B2A96B5A328B6D02F").Hash`

The constructor of `MediaBrowser.Model.Cryptography.PasswordHash` splits the string at character '$' to a string array and tries to access index 1 which throws the `System.IndexOutOfRangeException`

**Comment by joern-h** [comment]
@anthonylavado sorry, i was referencing to issues #1372 #1386

**Comment by DrPandemic** [comment]
@joern-h :wave:, nice debugging. I won't be able to fix this before next weekend. Do you have a fix? If so, you could send a PR and I'll happily review it

**Pull request merged**
