### PR TITLE
Add support for TMDb episode groups

### PR DESCRIPTION
**Pull request by gpregger**
**Changes**

Add support for choosing a specific episode group / episode order published on TMDb when identifying TV shows.
The different episode groups show up as separate search results and are tagged with the episode group name.
For Jellyfin-web to support this there is a corresponding pull request on jellyfin-web: [#2679](https://github.com/jellyfin/jellyfin-web/pull/2679)
Addresses following feature request: https://features.jellyfin.org/posts/1043/tvdb-episode-group-support
Possibly makes episode ordering (absolute / dvd) obsolete.

Note: My experience with large projects and C# are limited. I took several days to read into and understand the project code and tested the outcome for functionality and bugs. If this PR is rubbish, please do not hesitate to let me know.

### CODE REVIEW

**Comment by cvium** [comment]
Hi. Thanks for contributing. I apologize for being brief but I'm writing this from my phone.

A few comments:

1. We're moving providers to separate plugins, so anything tmdb specific must stay in the tmdb classes.
2. We already support airdate and dvd order aka. Display order. Is it necessary to put episode group id in Series?
3. This seems better suited as a separate database table, so maybe this feature should wait until we have rewritten the db?

**Comment by gpregger** [comment]
Hi, thanks for your comments.
1. I tried to keep any mention of TMDb out of as many seemingly non-tmdb-related files, but for example couldn't figure out how to teach the RemoteSearchResult class about an Episode Group otherwise. If this isn't the way to do it, any pointers would be appreciated.
2. This approach to episode order seems to me a bit more obvious and approachable as it presents the options right in the search results panel and it can handle cases where the current displayorder option failed for me.
3. Unfortunately I don't quite know what that means :)

**Comment by gpregger** [comment]
> Yoo thats my feature request, I hope you can do what it takes to get it approved and added!

Hey, I'll do what I can :)
In the meantime if you want to test you can use my fork at https://hub.docker.com/r/gpregger/jellyfin

**Comment by gpregger** [comment]
Polluted source branch opening new PR for dedicated branch...

**Pull request closed without merging**
