### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by Bond-009**
My git stash is getting too big to handle ;)

### CODE REVIEW

**Comment by Bond-009** [comment]
No

**Comment by smurancsik** [comment]
Is that planned to change to ToList()? I saw the other uses of IReadOnlyList through the project uses .ToList() before returning.

**Comment by Bond-009** [comment]
Which line are you talking about?
And it doesn't really matter that much, unless the collection is very large, long lived or is frequently accessed by index.

**Comment by mark-monteiro** [comment]
> Is that planned to change to ToList()? I saw the other uses of IReadOnlyList through the project uses .ToList() before returning.

The return object is already a list, the existing code was calling `.ToArray()` on a `List<>` which is pointless

**Pull request merged**
