### PR TITLE
Test Projects

### PR DESCRIPTION
**Pull request by BnMcG**
Test projects for Jellyfin code.

### CODE REVIEW

**Comment by BnMcG** [comment]
Closes #67

**Comment by Bond-009** [comment]
There already exists an Emby.XmlTv.Test project.

**Comment by BnMcG** [comment]
This only seems to target .Net 4, I'd say we should copy the tests into the new project and delete the old one.

**Comment by Bond-009** [comment]
Yes, using Nunit while you are at it :)

**Comment by BnMcG** [comment]
Will do that now

**Comment by BnMcG** [comment]
Added existing XmlTv tests using NUnit, some are failing but these seem like minor formatting issues, don't want to start changing anything until we get a good grip on what's happening, though.

**Comment by joshuaboniface** [comment]
We need to revert this - it caused some breakage and the huge LOC count increase needs further review.

**Pull request merged**
