### PR TITLE
Remove custom ToArray extension

### PR DESCRIPTION
**Pull request by Bond-009**
90% of these shouldn't be arrays, but that's an issue for another time.

### CODE REVIEW

**Comment by nvllsvm** [comment]
If possible, please break up your changes into logical commits. Having one type of change per commit is way easier to read through than having a single commit.

**Comment by joshuaboniface** [comment]
Yea let's definitely get in that habit - one change per commit!

**Comment by Bond-009** [comment]
I just don’t like having commits that don’t compile successfully.

**Comment by joshuaboniface** [comment]
Hrm that's a good point, I guess you're compiling regularly with the editor - I tend to take a "commit, commit, commit, test" type approach and then `reset HEAD~3` if it's broke, just to force myself to commit small changes. I guess the main idea is that we wnat each PR to be easily-reviewable, though now having another C# person or two will help a lot!

**Pull request merged**
