### PR TITLE
Always create new user when startup wizard is run.

### PR DESCRIPTION
**Pull request by barronpm**
**Changes**
Always create a user when the startup wizard is run.

### CODE REVIEW

**Comment by cvium** [comment]
Why is it needed?

**Comment by barronpm** [comment]
> 
> 
> Why is it needed?

This is an unintended change vs 10.5.x. A common recovery step for users is to go through the startup wizard again, and use the newly created admin account to fix the user's original account.

**Comment by cvium** [comment]
That sounds like security no-no to me.

**Comment by barronpm** [comment]
In order to do this, you must have read-write access to the filesystem, at which point one could easily just insert a new admin user into the db.

**Comment by joshuaboniface** [comment]
That's true, but this has always felt like a hack. It would be nicer now if we could leverage the better user DB to provide some way to do this cleanly from a command, rather than forcing the startup wizard. Even if it's just some bash that rewrites the userdb SQLite file, that would be nicer than this!

**Comment by barronpm** [comment]
After discussing this with the team, we decided it would be better to introduce proper ability to recover an install instead of reintroducing this behavior.

**Pull request closed without merging**
