### PR TITLE
Add interface for MissingEpisodesProvider

### PR DESCRIPTION
**Pull request by Larvitar**
Right now missing episodes can only be provided by TVDB (hardcoded). Implement and interface that would allow 3rd party plugins to provide missing episodes to series.

**Changes**
1. IMissingEpisodesProvider interface
2. MissingEpisodeInfo class instead of previously used tuple.
3. Changes to TV/SeriesMetadataService.cs that allow it to fetch episodes list from all providers implementing IMissingEpisodesProvider  interface.
4. TV/MissingEpisodeProvider.cs is mostly unchanged.

### CODE REVIEW

**Comment by cvium** [comment]
We have had a bunch of discussions internally about this particular feature and we feel it's not very useful. Maybe you can convince us otherwise?
We're debating removing the feature entirely and for this reason this PR might not be merged.

**Comment by Larvitar** [comment]
Yeah, I wanted to implement this in a plugin I'm writing for myself but mostly for the use with "Upcoming" page, I don't think I'd be using it too often. I know that Plex does not have a feature like this, am not sure about other media servers. On the other hand that might be one of the little features that distinguish Jellyfin from others. 
While missing episodes are not that much useful I think a properly managed "Upcoming" page might a nice (but small) feature but is anyone actually using it?

**Comment by Larvitar** [comment]
Anyways there is no point leaving it as it is right now. It's not even clearly stated in library settings that only TVDB supports this. Probably some people tried enabling it and then gave up thinking it's broken when it did not return any data.

**Comment by Nickbert7** [comment]
> We have had a bunch of discussions internally about this particular feature and we feel it's not very useful. Maybe you can convince us otherwise?
> We're debating removing the feature entirely and for this reason this PR might not be merged.

Please dont remove this feature. I often use it to find missing episodes of series. (With the report plugin filtered to missing episodes)
I would also love to see a similar feature to the TMDB Box Sets plugin to find missing movies in collections.

**Review by crobibero — APPROVED** [review]

**Comment by h1dden-da3m0n** [comment]
> We have had a bunch of discussions internally about this particular feature and we feel it's not very useful. Maybe you can convince us otherwise?
> We're debating removing the feature entirely and for this reason this PR might not be merged.

I agree with *Larvitar* and *Nickbert7* that this feature, may not be the main selling point of Jellyfin, but certainly distinguishes it from other media servers (besides being the only REAL open source :smiley: ).
Additionally, a subset of users like *Nickbert7* and I use this feature to find missing episodes and finish our collections. 
So we would really appreciate if we could keep this maybe niche, but certainly useful feature!

**Comment by cvium** [comment]
There are different ways to include this feature in some form or the other. The current implementation is crappy to maintain even with this PR.

I know it's not an open source solution, but trakt.tv can also keep track of your collection 😄

**Comment by h1dden-da3m0n** [comment]
> There are different ways to include this feature in some form or another. The current implementation is crappy to maintain even with this PR. And the added complexity to usefulness ratio makes it a non-Core feature imo. It's better suited as a plugin.
> 
> I know it's not an open source solution, but trakt.tv can also keep track of your collection smile

Whilst, I agree that this is not necessarily a Core feature, a "replacement" with Trakt is not really great either. (as it would be overkill for this scope in addition to being closed source :frowning_face: )
Anyway, I fully understand that you are considering  to remove it, if the current implementation is "jank" and would continue to be hard to maintain. (however sad that may be for myself or the others how have voiced their support for this feature)

**Comment by cvium** [comment]
This is sort of what I had in mind https://github.com/cvium/jellyfin-plugin-missingepisodeprovider

**Comment by Larvitar** [comment]
I like it but what about using it in other metadata plugins? I don't think we want every plugin to implementing their own versions of AddVirtualSeason etc (even if it would just be copy+paste). How about moving it to another namespace and then using it as a submodule?

**Comment by cvium** [comment]
I get what you're saying, but it's a lot of added complexity for a simple plugin. Yes, there's some boiler plate code in my plugin that could be generalized, but you're not gonna use multiple providers (eg. tvdb + tmdb) at the same time because they may not be compatible, so the abstraction seems unnecessary.

**Comment by Larvitar** [comment]
I thought about implementing it in plugins similar to [https://github.com/jellyfin/jellyfin-plugin-anime](url). I agree that probably no one will be using multiple providers.
Now that I think about it methods related to adding and removing missing episodes are simple enough that any fixes/changes won't be frequent so just copypasting your code should be enough.

**Comment by h1dden-da3m0n** [comment]
> I thought about implementing it in plugins similar to [Jellyfin Anime Plugin](https://github.com/jellyfin/jellyfin-plugin-anime). I agree that probably no one will be using multiple providers.
> Now that I think about it methods related to adding and removing missing episodes are simple enough that any fixes/changes won't be frequent so just copypasting your code should be enough.

Why copy and past and not collaborate on the plugin cvium already started? (but maybe I just misunderstood your intent :confused: )

**Comment by Larvitar** [comment]
> Why copy and past and not collaborate on the plugin cvium already started? (but maybe I just misunderstood your intent  )

You can have multiple plugins providing metadata. Either all of those plugins can provide missing episodes by themselves or https://github.com/cvium/jellyfin-plugin-missingepisodeprovider will implement all of those providers. The second way would mean a lot of code duplication and mantaining issues. Third way would be to implement some level of abstraction and let those plugins communicate with each other, but that might be an overkill as @cvium already mentioned.

**Comment by h1dden-da3m0n** [comment]
> > Why copy and past and not collaborate on the plugin cvium already started? (but maybe I just misunderstood your intent  )
> 
> You can have multiple plugins providing metadata. Either all of those plugins can provide missing episodes by themselves or https://github.com/cvium/jellyfin-plugin-missingepisodeprovider will implement all of those providers. The second way would mean a lot of code duplication and mantaining issues. Third way would be to implement some level of abstraction and let those plugins communicate with each other, but that might be an overkill as @cvium already mentioned.

:facepalm: my bad. I somehow was brain-dead there :smile: my apologies (and thy for the clarification)

**Comment by h1dden-da3m0n** [comment]
I guess this one can get closed now, since #4177 got merged?

**Comment by crobibero** [comment]
Closing as this has been implemented as a plugin.

**Pull request closed without merging**
