### PR TITLE
Correct m4b mimetype

### LINKED ISSUE #6986: [Issue]: m4b files not play with iOS app
### Please describe your bug

Not sure should this .m4b filetype even play with iOS device even it is invented by apple?
Anyways this .m4b seems to be best format for audiobooks. +10 separate .mp3 files seems a bit messy under every book.

Server: 10.7.7 (unRAID docker)
iOS: 1.4.1

I will just get notification "This client isn't compatible with the media and the server isn't sending a compatible media format."
File play fine with browser (firefox) and Jellyfin Media Player desktop app (Linux) and with all other players including plex, vlc, mpv, booksonic etc.
Should chapters to be visible with .m4b files?

### Jellyfin Version

10.7.7

### if other:

_No response_

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

_No response_

### FFmpeg logs

_No response_

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by felix920506**
Allows iOS and Safari to direct play m4b

**Changes**
Correct M4B Mimetype from "audio/m4b" to "audio/mp4

**Issues**
Fixes #6986

### CODE REVIEW

**Comment by felix920506** [comment]
Sorry, fat fingered

**Review by Shadowghost — APPROVED** [review]

**Review by crobibero — COMMENTED** [review]
According to [this PR](https://github.com/samuelneff/MimeTypeMap/issues/110) the actual "proper" mimetype is `audio/x-m4b`

I'm not sure if we want `audio/mp4` or `audio/x-m4b`

**Comment by felix920506** [comment]
> According to [this PR](https://github.com/samuelneff/MimeTypeMap/issues/110) the actual "proper" mimetype is `audio/x-m4b`
> 
> I'm not sure if we want `audio/mp4` or `audio/x-m4b`

Let me test this

**Review by crobibero — APPROVED** [review]

**Comment by thornbill** [comment]
What I'm gathering is audio/x-m4b is a custom, non-standard type only really used by iTunes. The official RFC standard only specifies audio/mp4 for audio in a mp4 container. https://stackoverflow.com/questions/39885749/m4a-is-considered-audio-m4a-or-audio-mp4

**Comment by felix920506** [comment]
If you think audio/mp4 is more appropriate then just revert my newest commit then merge. Both work as far as my testing.

**Comment by nielsvanvelzen** [comment]
For the Android apps we prefer `audio/mp4` because the `audio/x-m4b` media type is not mapped in the library we use for our video player (androidx.media3), so it won't work.

**Comment by felix920506** [comment]
I noticed this section right below there the fix happened. What does this section do? Should the m4b stuff be cleaned up?

截圖 2024-02-09 下午6 01 58

**Review by Bond-009 — APPROVED** [review]

**Review by thornbill — APPROVED** [review]

**Pull request merged**
