### PR TITLE
Revert SecurityException response code

### LINKED ISSUE #3574: Could not connect to server
**Describe the bug**
The new update of Jellyfin mobile apps does not allow to connect to a local deployment of Jellyfin server.  By local deployment, I mean the local installation of Jellyfin server that is not exposed to the internet.  A simple example would be, being able to access Jellyfin at http://192.168.1.x:8096/. 

This is already working with the devices which have already added the local server successfully with previous version of Jellyfin apps.  Now, if you try to connect to server located at http://192.168.1.x:8096/, it gives "Could not connect to server" error.

**System (please complete the following information):**
 - Clients: iPhone, iPad OS
 - Jellyfin Version: 1.1.1 (1), Expo Version: 37.0.0

**To Reproduce**
1. Install Jellyfin iOS or iPad OS App
2. Click on 'Add Server'
3. Type 'http://192.168.1.x:8096/'
4. See error "Could not connect to server"

**Expected behavior**
1. Install Jellyfin iOS or iPad OS App
2. Click on 'Add Server'
3. Type 'http://192.168.1.x:8096/'
4. See your media libraries

### LINKED ISSUE #3599: Infuse client can't log in unless user is admin user
I'm sorry, I don't know if this is a bug with the Infuse client, or with Jellyfin.

**Describe the bug**
For Infuse client (v 6.4.6 on iOS and tvOS/AppleTV), when adding Jellyfin media server and entering the Username and Password, the client returns an error and is not allowed to log in unless the user has "Allow this user to manage the server" check (i.e. is an admin user) on the Jellyfin server.

**System (please complete the following information):**
 - OS: Unraid running jellyfin/jellyfin:nightly ("10.6.0 undefined") docker container
 - Virtualization: Docker
 - Clients: Infuse Pro 6.4.6 on iOS 13, iOS 14, and tvOS
 - Browser: n/w
 - Jellyfin Version: nightly, including nightly-20200711
 - Playback: N/A
 - Installed Plugins: none
 - Reverse Proxy: N/A (same issue happens even when server IP address and port is specified)
 - Base URL: [e.g. none, yes: /example]
 - Networking: Bridge
 - Storage: local disks on Unraid

**To Reproduce**
1. Open Infuse client on iOS, ipadOS, or tvOS
2. Click on Settings (gear icon)
3. Click on "Add Files"
4. Click on "+ Add Media Server"
5. Click on "Other Jellyfin..."
6. Enter server address, username, and password for a NON ADMIN user
7. Click on "Save"
8. Pop-op dialog says "An error occurred" and the user can not log in.

If you go into the Jellyfin server and enable "Allow this user to manage the server" the Infuse client can now log in properly.

**Expected behavior**
Add Jellyfin server to Infuse client as normal, without having to enable "Allow this user to manage the server" for every user.

**Logs**
Jellyfin log shows:
```
[2020-07-19 00:42:40.370 -07:00] [ERR] [59] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://jellyfin.mydomain.org/Users/AuthenticateByName"
System.FormatException: Input string was not in a correct format.
   at ServiceStack.Text.DefaultMemory.ParseGeneralStyleGuid(ReadOnlySpan`1 value, Int32& len) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\DefaultMemory.cs:line 629
   at ServiceStack.Text.DefaultMemory.ParseGuid(ReadOnlySpan`1 value) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\DefaultMemory.cs:line 414
   at ServiceStack.Text.Common.DeserializeBuiltin`1.<>c.<GetParseStringSpanFn>b__7_6(ReadOnlySpan`1 value) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\Common\DeserializeBuiltin.cs:line 72
   at ServiceStack.Text.Jsv.JsvReader.<>c__DisplayClass2_0.<GetParseFn>b__0(String v) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\Jsv\JsvReader.Generic.cs:line 18
   at Emby.Server.Implementations.Services.StringMapTypeDeserializer.PopulateFromMap(Object instance, IDictionary`2 keyValuePairs)
   at Emby.Server.Implementations.Services.RestPath.CreateRequest(String pathInfo, Dictionary`2 queryStringAndFormData, Object fromInstance)
   at Emby.Server.Implementations.Services.ServiceHandler.CreateRequest(IRequest httpReq, RestPath restPath, Dictionary`2 requestParams, Object requestDto)
   at Emby.Server.Implementations.Services.ServiceHandler.CreateRequest(HttpListenerHost host, IRequest httpReq, RestPath restPath, ILogger logger)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-07-19 00:42:40.386 -07:00] [INF] [56] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for "Wife" has succeeded.
[2020-07-19 00:42:40.392 -07:00] [INF] [56] Emby.Server.Implementations.Session.SessionManager: Creating new access token for user 844897bf-b69d-4014-bb67-d1e2acfbb3c1
[2020-07-19 00:42:40.613 -07:00] [ERR] [56] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "User does not have admin access". URL: "http://jellyfin.mydomain.org:443/Library/VirtualFolders"
[2020-07-19 00:44:16.668 -07:00] [INF] [90] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS "::ffff:192.168.1.1" request
[2020-07-19 00:44:41.724 -07:00] [ERR] [100] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://jellyfin.mydomain.org/Users/AuthenticateByName"
System.FormatException: Input string was not in a correct format.
   at ServiceStack.Text.DefaultMemory.ParseGeneralStyleGuid(ReadOnlySpan`1 value, Int32& len) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\DefaultMemory.cs:line 629
   at ServiceStack.Text.DefaultMemory.ParseGuid(ReadOnlySpan`1 value) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\DefaultMemory.cs:line 414
   at ServiceStack.Text.Common.DeserializeBuiltin`1.<>c.<GetParseStringSpanFn>b__7_6(ReadOnlySpan`1 value) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\Common\DeserializeBuiltin.cs:line 72
   at ServiceStack.Text.Jsv.JsvReader.<>c__DisplayClass2_0.<GetParseFn>b__0(String v) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\Jsv\JsvReader.Generic.cs:line 18
   at Emby.Server.Implementations.Services.StringMapTypeDeserializer.PopulateFromMap(Object instance, IDictionary`2 keyValuePairs)
   at Emby.Server.Implementations.Services.RestPath.CreateRequest(String pathInfo, Dictionary`2 queryStringAndFormData, Object fromInstance)
   at Emby.Server.Implementations.Services.ServiceHandler.CreateRequest(IRequest httpReq, RestPath restPath, Dictionary`2 requestParams, Object requestDto)
   at Emby.Server.Implementations.Services.ServiceHandler.CreateRequest(HttpListenerHost host, IRequest httpReq, RestPath restPath, ILogger logger)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

### PR DESCRIPTION
**Pull request by crobibero**
Fixes #3599

### CODE REVIEW

**Comment by crobibero** [comment]
> What is the reason for reverting it? Did we agree not to break the API for this release? A 403 is the correct response code.


https://github.com/jellyfin/jellyfin/pull/2861
This PR is what changed the response codes, I was just reverting it.

**Comment by anthonylavado** [comment]
Ugh I told everyone that nothing was changing this release. I'll point it out to Firecore, but I'm unsure how quickly they can respond to this

**Comment by anthonylavado** [comment]
Firecore is currently beta testing a fix for this, so we can probably close it (if it only affected them).

**Comment by crobibero** [comment]
Fixed on Infuse side

**Pull request closed without merging**
