### PR TITLE
Logging Performance Increase

### PR DESCRIPTION
**Pull request by BaronGreenback**
Came across this whilst searching for the cause of a logging deadlock.
https://github.com/exceptionless/Exceptionless/pull/830

From what is posted, changing the default theme for the console logging to none would provide some performance benefits.
Likewise I've added limited the level to "_Warning_" on the console, as 99% of the time, debug information is produced too fast on the console to be of use.,

As this is the default logging settings, and is only applied if the log settings don't exist, if would only be of benefit to new installations.

### CODE REVIEW

**Review by Bond-009 — CHANGES_REQUESTED** [review]
This will remove the colors in the console right?
And the default mode is Info, not Debug

**Comment by BaronGreenback** [comment]
> This will remove the colors in the console right?
> And the default mode is Info, not Debug

Yes colour will go. 


> This will remove the colors in the console right?
> And the default mode is Info, not Debug

Yes. No colour. The reasoning is that it is easier for the user to remove the config to get colour than to add this syntax. 

As for custom logging setting, set to warning to reduce output as can't see the average user monitoring it. It also means that it the user changes the overall level, say to fish noise something  the console won't be affected.

**Comment by Bond-009** [comment]
I don't like this change
1) red errors are way easier to spot
2) Warning logs almost nothing (rip startup info)
3) ^ bug reports will have even less info
4) all these tradeoffs are for performance, but there aren't any benchmarks

**Comment by BaronGreenback** [comment]
> I don't like this change
> 
>     1. red errors are way easier to spot

Agree - but my point is only **if** the console is being used. I don't know about other platforms, but i'm running JF as a service under windows. Whereas it's useful when i'm debugging and running it as a user, have the console under the service seems a waste of resources. Aware that this may be different for other platforms. 

>     2. Warning logs almost nothing (rip startup info)

Only selected as warnings for it's brevity. Could just as easily be info for console.

>     3. ^ bug reports will have even less info

The logs should still contain the full information, this should only restrict what is output to the console. (Again windows based, so it might be different on other platforms)

>     4. all these tradeoffs are for performance, but there aren't any benchmarks
I'll provide rough benchmarks once my latest assignment is done, but I know the console can slow things down considerably on the windows platform.

**Comment by Bond-009** [comment]
We could just disable console logging when installing jellyfin as a service on windows

**Comment by dkanada** [comment]
For what it's worth, I'm adding highlighting to the vue client so the color removal wouldn't affect anything there.

**Pull request closed without merging**
