### PR TITLE
Add TMDb logo handling

### LINKED ISSUE #6942: [Issue]: Logos are not available
### Please describe your bug

Setup:
Running Jellyfin 10.7.7 on unRaid 6.9.2. via Docker (ich777)

Movies:
Metadata downloaders:
1. TheMovieDB
2. The Open Movie Database

Fetcher Settings:
1. TheMovieDB
2. The Open Movie Database
3. Screen Grabber

TV Shows:
Metadata downloaders:
1. TheMovieDB
2. The Open Movie Database

Episode Metadata downloaders:
1. TheMovieDB
2. The Open Movie Database

Series Fetcher Settings:
TheMovieDB

Season Fetcher Settings:
TheMovieDB

Issue:
Logos are not downloaded for either movies nor tv shows. Even manually going to a movie then "edit images"  and going straight to "Logos" none are shown. Also enabling "all languages" doesn't load any logos.

See one example:

Spiderman: Far From Home (2019):
Logos are available on TMDB
https://www.themoviedb.org/movie/429617-spider-man-far-from-home/images/logos

However, none are shown in Jellyfin (please see attached screenshot)
Same behavior for TV shows. I couldn't find any example in which logos are available. 

Please let me know if I should provide additional information. Thanks for your hard work!

Cheers!

### Jellyfin Version

10.7.7

### if other:

_No response_

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

_No response_

### FFmpeg logs

_No response_

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

Screenshot 2021-12-05 at 09 27 24

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by 1337joe**
**Changes**
- Add support for downloading logo images from TMDb
- Bump TMDbLib to 1.9.1

**Issues**
Fixes #6942

### CODE REVIEW

**Comment by Shadowghost** [comment]
v1.9.0 of TMDbLib id now avaliable [nuget](https://www.nuget.org/packages/Tmdblib)

**Comment by 1337joe** [comment]
Just pulling in the new version of the library builds but throws an exception when it tries to fetch images (in general, not just this branch). I have family visiting and haven't had time to try to debug it yet, maybe tomorrow.

**Comment by Shadowghost** [comment]
There was a breaking bug in 1.9.0 - should be fixed in 1.9.1 according to https://github.com/LordMike/TMDbLib/issues/398

**Comment by 1337joe** [comment]
New version fixes the issue I was seeing, testing looks like everything works regarding images.

**Review by Bond-009 — APPROVED** [review]

**Review by crobibero — APPROVED** [review]

**Pull request merged**
