### PR TITLE
It92019 ana marija

### PR DESCRIPTION
**Pull request by AnaMarijaKarcas**
**Changes**

**Issues**

### CODE REVIEW

**Comment by joshuaboniface** [comment]
Stop making these garbage pull requests against our project.

**Comment by AnaMarijaKarcas** [comment]
I am so sorry

**Comment by joshuaboniface** [comment]
@AnaMarijaKarcas Thank you for the apology.

Yours is not the first junk PR from a "URIS2022-Tim" organization we've received. Please inform your professor, teacher, instructor, or whoever is encouraging or assigning tasks to open PRs against our project - with no context and nonsensical changes - to please stop. It is not welcome and is a burden on our contributors. If you want to test things you may do so on your own fork. Otherwise we expect PRs against the main repository to be made in good faith (not as educational exercises) in accordance with our Contributing Guidelines here: https://jellyfin.org/docs/general/contributing/development

**Comment by AnaMarijaKarcas** [comment]
Once again, I am so sorry, thank you for your patience and the same will
not happen again.

**Pull request closed without merging**
