### PR TITLE
Fix GetItems IndexOutOfRangeException when IDs do not exist

### LINKED ISSUE #3531: Error on library scan
First of all, I'm new to JellyFin and I want to thank all the people working in this great project.

I'm experiencing some problems, I think when the system tries to scan some music folders in my collection. It starts ok, but at some point it stucks (now at 33% for example).

Diving through the logs, I see this exception:

```
[2020-07-11 12:14:11.489 +02:00] [INF] Starting Library Sync...
[2020-07-11 12:15:16.497 +02:00] [ERR] Error processing request. URL: "http://192.168.1.40:8096/Users/83d28c821a3748ed99729d7f02b66063/Items?Fields=Path%2CGenres%2CSortName%2CStudios%2CWriter%2CTaglines%2CLocalTrailerCount%2COfficialRating%2CCumulativeRunTimeTicks%2CItemCounts%2CMetascore%2CAirTime%2CDateCreated%2CPeople%2COverview%2CCriticRating%2CCriticRatingSummary%2CEtag%2CShortOverview%2CProductionLocations%2CTags%2CProviderIds%2CParentId%2CRemoteTrailers%2CSpecialEpisodeNumbers%2CMediaSources%2CVoteCount%2CRecursiveItemCount%2CPrimaryImageAspectRatio&Ids=0b3f5d074416ba0201931cbe748e46f2%2C378642437fbc6ed01cfe3977a8aa2c5d%2Cf2ee882d718ea25557e66176fbdb0ecc%2C906ac09144b04d3986ae6f51810970a2%2C3f4a9f06822a5e360d1a956e073467e2%2C3fb4516adf8cba78c243ec45d79746e4%2Cae8598464b56b0f32310d4b5fa724053%2Ca3a8e13faad95de07892ac400f2ed97a"
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at MediaBrowser.Controller.Entities.Folder.SortItemsByRequest(InternalItemsQuery query, IReadOnlyList`1 items)
   at MediaBrowser.Controller.Entities.Folder.GetItems(InternalItemsQuery query)
   at MediaBrowser.Api.UserLibrary.ItemsService.GetQueryResult(GetItems request, DtoOptions dtoOptions, User user)
   at MediaBrowser.Api.UserLibrary.ItemsService.GetItems(GetItems request)
   at MediaBrowser.Api.UserLibrary.ItemsService.Get(GetItems request)
   at lambda_method(Closure , Object , Object )
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```
I'm sorry if this has been already reported, i've searched but didn't found this error anywhere else.

### PR DESCRIPTION
**Pull request by lukefor**
**Changes**
Resolve a System.IndexOutOfRangeException when requesting IDs that do not exist via /Users/.../Items. Previously it was possible for the 'index' values in 'positions' to refer beyond 'size'. It seems the code previously assumed that all requested items exist
```
[ERR] Error processing request. URL "GET" "/Users/.../Items".
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at MediaBrowser.Controller.Entities.Folder.SortItemsByRequest(InternalItemsQuery query, IReadOnlyList`1 items)
   at MediaBrowser.Controller.Entities.Folder.GetItems(InternalItemsQuery query)
   at Jellyfin.Api.Controllers.ItemsController.GetItems
```

It caused jellyfin-kodi automatic syncs (i.e. the sync that happens automatically while Kodi is running) to fail as per #3531. I could get a consistent repro by making the same request via curl. With this change, Kodi is automatically syncing again, and the curl request returns correct results.

**Issues**
Fixes #3531

### CODE REVIEW

**Comment by nielsvanvelzen** [comment]
Can you retarget this PR to the release-10.8.z branch? That way we can include it in an patch update.

**Comment by lukefor** [comment]
Have retargeted it to  release-10.8.z now

**Comment by cvium** [comment]
Am I crazy or could the entire method not be simplified to `return items.OrderBy(i => ids.IndexOf(i.Id)).ToArray();`?

**Comment by cvium** [comment]
@lukefor Have you had a chance to look at my suggestion?

**Comment by lukefor** [comment]
Have made the suggested change. Problematic curl request is working and returning identical results to the previous fix

**Review by crobibero — APPROVED** [review]

**Review by cvium — APPROVED** [review]

**Pull request merged**
