### PR TITLE
AsyncKeyedLock migration

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**
Switching the existing locking mechanism to use the AsyncKeyedLock library which has been heavily tested and benchmarked, offering superior performance and lower memory allocations (mainly due to the object pooling), while extra care ensured against race conditions.

**Changes**
Jellyfin now uses a more streamlined approach to locking concurrent tasks by key.

**Issues**
Replaces #9132

Note to reviewer: there are a number of `if` statements that happen within the locks. I left them as is so as not to affect functionality but it is quite likely that it would be possible for you to put the `if` outside/enclosing the lock, leading to a performance gain. @JPVenson

### CODE REVIEW

**Comment by MarkCiliaVincenti** [comment]
Please try not to take another year to review :) It was painful doing it all over again.

**Review by JPVenson — APPROVED** [review]

**Comment by JPVenson** [comment]
LGTM

**Comment by MarkCiliaVincenti** [comment]
> LGTM

Did you read the note I left regarding the `if` statements please?

**Comment by JPVenson** [comment]
i did but such a change of functionality would require a test from one of the devs which would prolong this PR again.

**Review by crobibero — APPROVED** [review]

**Review by JPVenson — APPROVED** [review]

**Comment by MarkCiliaVincenti** [comment]
What's the next step please? @JPVenson

**Comment by JPVenson** [comment]
@MarkCiliaVincenti playing the wait game. The server has a 2 maintainer review policy and then somebody needs to click on merge. There is currently quite some activity on the server repro so maybe somebody will look soon here.

**Comment by MarkCiliaVincenti** [comment]
@nielsvanvelzen @Shadowghost @Bond-009 can you kindly merge?

**Comment by nielsvanvelzen** [comment]
Please don't ping random people to get your PR merged.

**Comment by MarkCiliaVincenti** [comment]
Fixed issues and made new changes so that async locking uses the library as well with a similar interface and the dispose pattern.

**Comment by MarkCiliaVincenti** [comment]
@JPVenson @crobibero can you please go over the minor new changes I made and approve again?

Also, what can be done so that this gets merged? Last attempt (#9132) didn't get approved a year later and it sucks having to redo everything because of all the changes done in the meantime.

**Comment by nielsvanvelzen** [comment]
Once again, **stop pinging people to get reviews**. There are almost 90 open pull requests right now with a very small team to review each of them. Reviews will happen when someone is interested in a pull request and wants to see it merged. Everyone here is a volunteer. Pinging is generally not appreciated.

**Comment by MarkCiliaVincenti** [comment]
Worth noting that jellyfin now already depends, transitively, on the AsyncKeyedLock library. Therefore no added dependencies as such.

**Comment by JPVenson** [comment]
Is the PR done? If you need more time with refining stuff i advice you to put the PR into draft mode instead. The continues pushing of new, unrequested updates defers a lot of reviewers.

**Comment by MarkCiliaVincenti** [comment]
It's done. I only merged changes.

**Review by cvium — APPROVED** [review]

**Pull request merged**
