### PR TITLE
Update CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by scottpk**
**Changes**
add self to contributors per https://jellyfin.org/docs/general/contributing/development.html

### CODE REVIEW

**Comment by LogicalPhallacy** [comment]
Traditionally one does this alongside their first PR (ie. you include yourself on contributors.md in a commit alongside the others commits where you contribute something). Is Github misinforming me or is this your first PR to Jellyfin?

**Comment by scottpk** [comment]
I did #7672 for someone whose vinyl records weren't getting their info, that is the code change.

**Comment by LogicalPhallacy** [comment]
> I did #7672 for someone whose vinyl records weren't getting their info, that is the code change.

OK cool, since it wasn't complete github was flagging this as a first contribution. If you want you could merge this contributor change onto that other PR, just to ease in bookkeeping, or keep it open and once that PR merges, leave a comment here and we'll get this one complete too.

**Comment by scottpk** [comment]
Sorry I am not familiar with how to do that, can I do it from the GitHub site?

**Pull request closed without merging**
