### PR TITLE
Save embedded lyrics when probing audio

### PR DESCRIPTION
**Pull request by crobibero**

### CODE REVIEW

**Comment by DomiStyle** [comment]
Tested on a few of my songs and works perfectly fine with synchronized and unsynchronized lyrics.

Also tried with some UTF-8 characters and no issues there either.

**Comment by NicholasFlamy** [comment]
> Tested on a few of my songs and works perfectly fine with synchronized and unsynchronized lyrics.
> 
> Also tried with some UTF-8 characters and no issues there either.

How do you test it? Sorry for the noob question, did you fork it and merge this in your fork or did you get a build artifact?

**Comment by crobibero** [comment]
PRs do not have artifacts published, you would need to build it yourself.

**Comment by NicholasFlamy** [comment]
> PRs do not have artifacts published, you would need to build it yourself.

Got it, thank you.

**Review by Shadowghost — APPROVED** [review]

**Review by Bond-009 — APPROVED** [review]

**Comment by NicholasFlamy** [comment]
@crobibero Why does it save the embedded lyrics to a file?

**Comment by cvium** [comment]
@NicholasFlamy chill. Stop posting in multiple issues/PRs

**Pull request merged**
