### PR TITLE
Do not use the nuget packages for comparison, but the last master build

### PR DESCRIPTION
**Pull request by EraYaN**
**Changes**
Instead of using the nuget packages for the comparison, use the latest passing master build.

### CODE REVIEW

**Comment by EraYaN** [comment]
Currently it always passes the options `latestFromBranch` does not seem to actually download the artifact from the latest branch build.

**Comment by JustAMan** [comment]
This doesn't feel right. It should be complaining that there are ABI changes _unless_ latest master has version bumped _enough_, so that once master version is inconsistent it says red until master is fixed. Otherwise it's too easy to overlook after first PR that failed stuff is merged.

**Comment by EraYaN** [comment]
Well we should probably just block failed CI PRs from merging.

**Comment by JustAMan** [comment]
That is true, but what happens if someone would miss that PR is failing CI check and would forcefully merge? This CI failure would then go unnoticed...

**Comment by EraYaN** [comment]
I think you can make GitHub block those merges.

https://github.blog/2015-09-03-protected-branches-and-required-status-checks/

**Comment by joshuaboniface** [comment]
@JustAMan I'm not very concerned with that situation, now that it's working normally again @jellyfin/core just needs to be diligent about not merging failing PRs ;-)

**Comment by EraYaN** [comment]
Well I'm at wits end. Why the hell won't it find the builds...
"Latest build from branch master not found"
Even with the `allowPartiallySucceededBuilds` set to true. There are rolling builds in the build log. But maybe they need to be more recent or something. At least the normal CI builds will now pass (since it can't compare master to master for example) So we can merge this to repair all rolling builds (the result of a merge or commit to a branch.
And diagnostics don't help either.

**Pull request merged**
