### PR TITLE
Remove DvdLib

### PR DESCRIPTION
**Pull request by ferferga**
Always query ffprobe for DVD and bluray info

Close #4901

### CODE REVIEW

**Comment by barronpm** [comment]
cc @Bond-009

**Comment by ferferga** [comment]
After concerns that removing DvdLib might reduce scanning speed, I'm making some tests.

Tests done with a fresh installation of the server with a **single library** with a **single sample iso file** located at http://www.deniscarl.com/dvdtest/ and ``3D MVC ISO Dolby 3D Glasses Return Clip`` from https://kodi.wiki/view/Samples

Data folder with the empty library (with no file still added) was copied and restored while changing between branches. Another difference from the commits pushed here is the addition of ``Console.WriteLine`` statements to show the code execution path in ``master`` branch. Scans are run using the scheduled task.

### Without DVDLib:
*Server output*
image
*Scanned library result*
image

### Master:
*Server output*
image

*Position of the Console statements*
image

*Scanned library result*
image

**In both cases, it seems that ``3D MVC ISO Dolby 3D Glasses Return Clip`` is completely skipped by the scanner without further information**. Removing DvdLib doesn't affect it, so I guess that's left for another PR where we revisit our ISO scanning.

CC @Bond-009

**Comment by ferferga** [comment]
Further tests (this time with the contents of the iso files extracted):

```
.
├── Dolby
│   ├── BDMV
│   │   ├── AUXDATA
│   │   ├── BACKUP
│   │   │   ├── BDJO
│   │   │   ├── CLIPINF
│   │   │   │   ├── 00000.clpi
│   │   │   │   └── 00001.clpi
│   │   │   ├── MovieObject.bdmv
│   │   │   ├── PLAYLIST
│   │   │   │   └── 00000.mpls
│   │   │   └── index.bdmv
│   │   ├── BDJO
│   │   ├── CLIPINF
│   │   │   ├── 00000.clpi
│   │   │   └── 00001.clpi
│   │   ├── JAR
│   │   ├── META
│   │   ├── MovieObject.bdmv
│   │   ├── PLAYLIST
│   │   │   └── 00000.mpls
│   │   ├── STREAM
│   │   │   ├── 00000.m2ts
│   │   │   ├── 00001.m2ts
│   │   │   └── SSIF
│   │   │       └── 00000.ssif
│   │   └── index.bdmv
│   └── CERTIFICATE
│       └── BACKUP
└── VideoTest
    ├── AUDIO_TS
    └── VIDEO_TS
        ├── VIDEO_TS.BUP
        ├── VIDEO_TS.IFO
        ├── VTS_01_0.BUP
        ├── VTS_01_0.IFO
        └── VTS_01_1.VOB
```

### Master

image
**Atmos page**
image
**Videotest page**
image

### Without DVDLib
image
**Atmos page**
image
**Videotest page**
image


### Conclusions

Aside from a slower scan speed, it seems DvdLib is not handling Windows paths properly (first reported in #4004). Also, it seems we're not passing the correct parameters to ffprobe for folder files anyway, which make scanning for those inherently broken. I remember some reports about this in Telegram but, so far, no issues were opened and users simply went back to use ISO files.

**Comment by Bond-009** [comment]
So both ffprobe and dvdlib are broken?

**Comment by Bond-009** [comment]
Superseded by #9068

**Pull request closed without merging**
