### PR TITLE
Move service hardening options to override config

### LINKED ISSUE #7503: [10.8.0][Issue]: restart.sh not working with new 10.8.0 update
### Please describe your bug

Unit name /jellyfin.service= is not valid
Turns out after restart the server didn't close the port and couldn't connect to the port again.

Also the issue template that asks what version of Jellyfin are you running needs 10.8.0 added to it.

### Jellyfin Version

Other

### if other:

_No response_

### Environment

```markdown
- OS: Ubuntu 20.04
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

_No response_

### FFmpeg logs

_No response_

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #7897: [Issue]: [10.8.0] Permission issues running as root
### Please describe your bug

I know it may not be a good practice to run Jellyfin as root (even if it runs in a dedicated container) but I wanted to use ports 80 and 443 without adding a reverse-proxy

With Jellyfin 10.7.0, on Debian, one could simply edit `/etc/systemd/system/jellyfin.service.d/jellyfin.service.conf` to modify the user, but that doesn't seem to work anymore. The executable is still ran by root (as shown by `ps -aux`) but doesn't have permissions on files or permission to run on port < 1024.

I am not sure what changed behind the scenes that could cause this?
Manually fixing permissions and running on a port > 1024 works, but I still feel like it's still not really running as root

### Jellyfin Version

10.8.0

### if other:

_No response_

### Environment

```markdown
- OS: Debian
- Virtualization: LXC
- Clients: N/A
- Browser: N/A
- FFmpeg Version: 5 
- Playback Method: N/A
- Hardware Acceleration: N/A
- Plugins: N/A
- Reverse Proxy: no
- Base URL: N/A
- Networking: Try to run as root, using port 80 and 443
- Storage:
```

### Jellyfin logs

```shell
Jun 12 16:43:30 lxc-jellyfin jellyfin[961]: [16:43:30] [INF] Kestrel listening on Any IP4 Address
Jun 12 16:43:30 lxc-jellyfin jellyfin[961]: [16:43:30] [ERR] Kestrel failed to start! This is most likely due to an invalid address or port bind - correct your bind configuration in network.xml and try again.
Jun 12 16:43:30 lxc-jellyfin jellyfin[961]: [16:43:30] [FTL] Error while starting server.
Jun 12 16:43:30 lxc-jellyfin jellyfin[961]: System.Net.Sockets.SocketException (13): Permission denied
Jun 12 16:43:30 lxc-jellyfin jellyfin[961]:    at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
Jun 12 16:43:30 lxc-jellyfin jellyfin[961]:    at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
Jun 12 16:43:30 lxc-jellyfin jellyfin[961]:    at System.Net.Sockets.Socket.Bind(EndPoint localEP)
Jun 12 16:43:30 lxc-jellyfin jellyfin[961]:    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
Jun 12 16:43:30 lxc-jellyfin jellyfin[961]:    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
Jun 12 16:43:30 lxc-jellyfin jellyfin[961]:    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
Jun 12 16:43:30 lxc-jellyfin jellyfin[961]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
Jun 12 16:43:30 lxc-jellyfin jellyfin[961]:    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass30_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
Jun 12 16:43:30 lxc-jellyfin jellyfin[961]: --- End of stack trace from previous location ---
Jun 12 16:43:30 lxc-jellyfin jellyfin[961]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
Jun 12 16:43:30 lxc-jellyfin jellyfin[961]:    at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
Jun 12 16:43:30 lxc-jellyfin jellyfin[961]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
Jun 12 16:43:30 lxc-jellyfin jellyfin[961]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context, CancellationToken cancellationToken)
Jun 12 16:43:30 lxc-jellyfin jellyfin[961]:    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
Jun 12 16:43:30 lxc-jellyfin jellyfin[961]:    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
Jun 12 16:43:30 lxc-jellyfin jellyfin[961]:    at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
Jun 12 16:43:30 lxc-jellyfin jellyfin[961]:    at Jellyfin.Server.Program.StartApp(StartupOptions options)
```
```


### FFmpeg logs

_No response_

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by joshuaboniface**
**Changes**

Some combination of these options were causing problems with the
functionality of restart.sh as described in the comment and in detail in
issue #7503.

While these seem OK on their face, the implications of this breaking
restart.sh means that they could potentially break other things too.

Thus, we should move these into the optional override file which is in
the administrator's full control, instead of in the default unit, and
leave them off unless a user or package maintainer (e.g. NixOS as
described in the original issue #6952) wants to enable them.

**Issues**

Fixes #7503
Fixes #7897

CC @matthiasdv for further comment

### CODE REVIEW

**Review by cvium — APPROVED** [review]
This is like the third time the hardening breaks something. LGTM.

**Comment by joshuaboniface** [comment]
For the "awaiting-feedback" part, I'd really like to get a better idea of where the hardening all came from.

From my understanding in #6952, this was all added because NixOS added a bunch of 3rd party hardening options, but 2 of them broke HWA. This prompted @matthiasdv (sorry I keep pinging you man just trying to get my thoughts out and want to keep the references straight!) to backport most of the changes - except the one that broke his HWA - into us. But these changes have since caused several other issues as @cvium notes, so I don't think having them on by default is ideal; Jellyfin just has too many hacks in it still (like `restart.sh`) to make good use of them.

What I'd like to understand is why NixOS is even adding all these options, and why they think that they should be upstreamed to fix a bug they caused in the first place. Because while I do in theory agree that hardening the service is a good goal, they clearly didn't take numerous caveats and exceptions into account, and despite my good deal of experience with Systemd, I still can't understand most of what it's trying to do or why unrelated options seem to break the ability for us to escalate privileges within the unit.

So, ultimately I'm hoping that making these optional is "good enough" for NixOS without causing further hassle for the 99% of Jellyfin users who aren't using that particular distribution, while still allowing them a way to "turn them on" and then handle their own user support.

**Review by crobibero — APPROVED** [review]

**Review by nyanmisaka — APPROVED** [review]
Also fixes many NVIDIA HWA issues:
https://github.com/jellyfin/jellyfin/issues/7025
https://github.com/jellyfin/jellyfin/issues/7878

https://www.reddit.com/r/jellyfin/comments/vdc54i/transcoding_seems_to_be_broken_since_upgrading_to

```
[AVHWDeviceContext @ 0x55a82ee714c0] cu->cuInit(0) failed -> CUDA_ERROR_UNKNOWN: unknown error
Device creation failed: -1313558101.
[AVHWDeviceContext @ 0x5651e61c9a80] cu->cuInit(0) failed -> CUDA_ERROR_UNKNOWN: unknown error
Device creation failed: -542398533.
```

**Comment by Earl0fPudding** [comment]
Hi, 
I also updated from 10.7.7 to 10.8.0 and had problems regarding Nvidia-HW-Decooding after rebooting:
`cu->cuInit(0) failed -> CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected`

The problem itself was not the reboot, it was rather the reload of the systemd unit files. The new hardened Jellyfin config has been loaded after reboot and so the process couldn't detect the GPU anymore. After doing the same changes as in this pull request following by a `systemctl daemon-reload && systemctl restart jellyfin`, the hardware acceleration finally worked again. Thank you very much, I hope this will get merged soon!

**Pull request merged**
