### PR TITLE
Check for last watched specials and next episode based on them

### PR DESCRIPTION
**Pull request by SenorSmartyPants**
**Changes**

Improved logic when last watched episode was a special when rewatching TV.

**Issues**
No issues entered but here are the problems solved.
- When last episode watched was a special, and no further episodes in series, special is always displayed in next up.
- Wrong next episode was displayed when last episode watched was a special

### CODE REVIEW

**Comment by cvium** [comment]
Four extra queries per series is a little much

**Comment by SenorSmartyPants** [comment]
> (Potentially) Four extra DB queries per series is a little much

Is there a way to return userdata with the watched episodes?

**Comment by cvium** [comment]
Not right now. So I'm starting to think that maybe "rewatching" isn't ready for prime time and that we should revert it

**Comment by SenorSmartyPants** [comment]
DTOOptions.EnableUserData is set to true on on the input parameter. But I don't see UserData returned. Why is that option there if it is not honored?

**Comment by SenorSmartyPants** [comment]
It also appears that _userDataManager.GetUserData is caching those lookups. I'm not sure when that is initially looked up or how long it is cached.

**Comment by SenorSmartyPants** [comment]
Addresses #7534

**Comment by SenorSmartyPants** [comment]
Messed up PR with a rebase. Closing. New PR created.

**Pull request closed without merging**
