### PR TITLE
Change DeinterlaceMethod's "bobandweave" to "yadif" or "yadif_bob", and set default value

### PR DESCRIPTION
**Pull request by alset333**
Set default value for the `DeinterlaceMethod` encoding option, and make the values more clear.

**Changes**
- Change `"bobandweave"` to `"yadif_bob"` to more accurately describe the option.
- Add default value `"yadif"` for `DeinterlaceMethod`.

**Issues Resolved**
- Clarifies `DeinterlaceMethod'`s expected values.
- Allows for easy expansion to more than two deinterlacer options.
- Sets a default value that can be read from jellyfin-web for the current `DeinterlaceMethod` instead of null/empty

**This will not change encoding options on its own, the UI must have controls added to do so.**
**The goal of these changes is to help/clarify development without affecting users.**

### CODE REVIEW

**Comment by alset333** [comment]
Here's a link to a possible implementation of deinterlacing controls in jellyfin-web which depends on this.
https://github.com/jellyfin/jellyfin-web/pull/968

**Comment by dkanada** [comment]
The web changes look fine to me, but I'm not familiar with this option. @JustAMan or @Bond-009 are you familiar with this feature?

**Comment by Bond-009** [comment]
I'm not, sorry

**Comment by EraYaN** [comment]
Yadif is better than bobandweave, but this should probably a client option. And it's also more demanding and smushes/softens the image more. Some people will want detelecine, and some clients will want no deinterlacing at all, like anything that plays on nvidia hardware has very good hardware detelecine for example, same with TVs (duh).

**Comment by alset333** [comment]
Of course. But the client option needs something to control and read the value from. Currently the deinterlace options are never set. The initial value used in this PR keeps the current default (output 30p not 60p).

Just a heads up; the files-changed view might give a better idea of what is different since it's only a few lines.

**Comment by alset333** [comment]
Link to ffmpeg's yadif documentation:
https://ffmpeg.org/ffmpeg-filters.html#yadif-1

**Pull request merged**
