### PR TITLE
Skip image processing for live tv sources

### PR DESCRIPTION
**Pull request by thornbill**
**Changes**
This addresses an issue where EPG updates for live tv sources takes an _extremely_ long time due to image processing. This is likely due to the number of images involved (number of channels * programs each day * 7 days * 2 image formats). For the ~30 channels I have, EPG updates were taking 5 hours to complete. With this change it is back to less than 1 minute! :tada:

This does have the side effect of blur hashes being unavailable for live tv images, but it seems worth the trade off. Perhaps we could add a task to generate blur hashes for programs airing soon at some point.

**Issues**
N/A

### CODE REVIEW

**Comment by thornbill** [comment]
@cvium it still calls the following for live tv items. I thought it would be better to avoid duplicating that code, but let me know if that is not the case. 
```
_itemRepository.SaveImages(item);
RegisterItem(item);
```

**Comment by Bond-009** [comment]
I think adding `|| item.SourceType != SourceType.Library`
to this line https://github.com/jellyfin/jellyfin/pull/3649/files#diff-48c22801bc9377e3d7095b8486feda0aL1879
does the same, without a useless library update

**Comment by thornbill** [comment]
Hmm so saving the images for the item shouldn't be necessary? @Bond-009

**Comment by Bond-009** [comment]
You don't change any data, so I don't think so

**Comment by thornbill** [comment]
Seems to work fine with that suggestion in place!

**Pull request merged**
