### PR TITLE
Release 10.2.0

### PR DESCRIPTION
**Pull request by joshuaboniface**
Merge in hotfixes from `release-10.2.z` branch for release 10.2.0.

### CODE REVIEW

**Comment by EraYaN** [comment]
Some commits made by weblate show weblate as the committer and some show either you @joshuaboniface or @Bond-009, did you guys do a specific merge type?

**Comment by joshuaboniface** [comment]
@EraYaN They show the original commiter based on Weblate username, plus whoever merged the commit (Bond merged some, then I merged some others). It's a "X authored and Y committed" message.

**Comment by EraYaN** [comment]
@joshuaboniface So this one: https://github.com/jellyfin/jellyfin/pull/912/commits/c78298789d20eb91bd1d9729d7b590110ce744d5 was directly committed?

**Comment by joshuaboniface** [comment]
@EraYaN Not sure why that one is different, afaik it was committed the same way. Maybe when I rebased in Weblate... will see if it reoccurrs.

**Pull request closed without merging**
