### PR TITLE
Delimeters : "," added to split multiple value fields like artists

### PR DESCRIPTION
**Pull request by Shabinder**
**Delimeters** : `,` and `&` added to split multiple value fields like artists

Fixing: https://github.com/jellyfin/jellyfin/issues/10730

Allowing Edits by maintainer to add any nitpicks if necessary.

### CODE REVIEW

**Comment by cvium** [comment]
Seems risky to me. & is also a no-go unless you believe Simon & Garfunkel are two separate artists.

**Comment by Shadowghost** [comment]
I still think that us having this list of "split characters" is a bad thing. APE2 and ID3v2.4 both support multiple artist fields in tags.

Add ing `&` as a general delimiter is a bad idea, there are enough artists and groups out there which use it legitimately.

**Comment by Shabinder** [comment]
How about having a **comma** only then ?
It is legitimately used by many taggers...
https://musicbrainz.org/doc/Style/Classical/Release_Artist

Also maybe we can provide custom delimeters using environment Variables or make configurable in Settings ?

**Comment by Shabinder** [comment]
> Seems risky to me. & is also a no-go unless you believe Simon & Garfunkel are two separate artists.

Agree & is a risky, hence removed that, and only added a `,` which we can decide since its vastly used by taggers, lmk if any issue with that ?

**Comment by TheMelmacian** [comment]
There are also artists with a `,` in the name.  On a quick search I found [Everything, Now!](https://rateyourmusic.com/artist/everything-now), [Go Robot, Go!](https://rateyourmusic.com/artist/go_robot__go_) and [Wow, Owls!](https://rateyourmusic.com/artist/wow-owls).

As Shadowghost mentioned, all modern tagging standards (APE2, ID3v2.4, Vorbis-Tags etc.) support multiple artist and genre fields. It's already a pain in the ass to maintain the exceptions for the existing delimiters, so I vote against it.

**Comment by Shabinder** [comment]
understandable, lets make this user configurable as most other player do.
That will be the safest choice.

**Comment by gnattu** [comment]
Replaced by #12385

**Pull request closed without merging**
