### PR TITLE
Replace custom image parser with Skia

### PR DESCRIPTION
**Pull request by nvllsvm**
Simplifies our code a little bit. Note that this is slower than the old method, but not enough to warrant the old code.

When skia was the first to read, an 48 distinct executions average to:
```
externallib 0.000075
original 0.000219
skia 0.000300
```

When original was the first to read, an 48 distinct executions average to:
```
externallib 0.000014
original 0.000048
skia 0.000046
```
When externallib was the first to read, an 48 distinct executions average to:
```
externallib 0.000187
original 0.000200
skia 0.000046
```

### CODE REVIEW

**Comment by ploughpuff** [comment]
Apart from the simplification, was the original code defective?

As an alternative to SkiaSharp, has System.Drawing been considered, which apparently can [give you the dimensions without loading the entire image](https://stackoverflow.com/questions/111345/getting-image-dimensions-without-reading-the-entire-file#comment93777777_112711):

https://docs.microsoft.com/en-us/dotnet/api/system.drawing.image.fromstream?view=netframework-4.7.2#System_Drawing_Image_FromStream_System_IO_Stream_System_Boolean_System_Boolean_

**Comment by Bond-009** [comment]
And no one understood it.
And it was badly written.

**Comment by ploughpuff** [comment]
Yes original was cut+paste from StackOverflow.

Regarding my System.Drawing comment, it seems that route was Win32 only until relatively recently.  There now exists a Window Compatibility NuGet Package which offers it:
https://www.nuget.org/packages/Microsoft.Windows.Compatibility

...but we're probably best avoiding that beast??

**Comment by nvllsvm** [comment]
@Bond-009 - I can do that in another pull request as this keeps the status quo. Thoughts?

**Comment by nvllsvm** [comment]
@Bond-009 removed `allowSlowMethods` and rebased to `dev`.

**Comment by Bond-009** [comment]
Just noticed you moved all Skia stuff inside `Emby.Drawing`, why?

**Pull request merged**
