### PR TITLE
DeviceQuery: change UserId to GUID

### LINKED ISSUE #352: 500 error on Devices page
Hi,
When trying to view the Devices page, it does not load and the server instead throws an exception:
```
2019-01-01 14:48:18.308 Info HttpServer: HTTP GET http://<emby>:8096/Devices. UserAgent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
2019-01-01 14:48:18.312 Error HttpServer: Error processing request
        *** Error Report ***
        Version: 3.5.2.0
        Command line: /usr/lib/jellyfin/bin/jellyfin.dll -programdata /var/lib/jellyfin -restartpath /usr/lib/jellyfin/restart.sh
        Operating system: Unix 4.13.0.1
        64-Bit OS: True
        64-Bit Process: True
        User Interactive: True
        Processor count: 8
        Program data path: /var/lib/jellyfin
        Application directory: /usr/lib/jellyfin/bin
        System.NullReferenceException: Object reference not set to an instance of an object.
           at Emby.Server.Implementations.Devices.DeviceManager.GetDevices(DeviceQuery query) in /repo/Emby.Server.Implementations/Devices/DeviceManager.cs:line 153
           at lambda_method(Closure , Object , Object )
           at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName) in /repo/Emby.Server.Implementations/Services/ServiceExec.cs:line 92
           at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost appHost, Object requestDto, IRequest req) in /repo/Emby.Server.Implementations/Services/ServiceController.cs:line 179
           at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/Services/ServiceHandler.cs:line 96
           at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 660
        System.NullReferenceException
           at Emby.Server.Implementations.Devices.DeviceManager.GetDevices(DeviceQuery query) in /repo/Emby.Server.Implementations/Devices/DeviceManager.cs:line 153
           at lambda_method(Closure , Object , Object )
           at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName) in /repo/Emby.Server.Implementations/Services/ServiceExec.cs:line 92
           at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost appHost, Object requestDto, IRequest req) in /repo/Emby.Server.Implementations/Services/ServiceController.cs:line 179
           at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/Services/ServiceHandler.cs:line 96
           at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 660

2019-01-01 14:48:18.312 Info HttpServer: HTTP Response 500 to <client-ip>. Time: 4ms. http://<emby>:8096/Devices
```

this is with the jellyfin 3.5.2-5 debian package:
```
dpkg -l | grep jelly
ii  jellyfin                          3.5.2-5                           amd64        Jellyfin is a home media server.
```

There are some more of these snags that I'm trying to sniff out because it would be really nice to get the fork fully functional as intended :)

This also affects the Users->user->Access page, and as a result I think an admin needs to sign in on any new device to authenticate the device so other users can then sign in.. It looks a bit like this:

POST https://<emby>/Users/authenticatebyname -> 401 / User is not allowed access from this device.

This goes away after an admin signs in on that device and I think this will be more debuggable when the error above is resolved :)
I have double checked now, and the user needs to be allowed to manage the server in order to have the server accept the new device

### PR DESCRIPTION
**Pull request by cvium**
Fixes #352

Crash caused by uninstantiated UserId, which for a string defaults to the value `null`. Default value for Guid is Guid.Empty, which is a bunch of zeros but it still has a `.Equals` method.

### CODE REVIEW

**Comment by cvium** [comment]
@JustAMan UserId _is_ a GUID though. String is the wrong type, but in C# they are mostly interchangeable so that's why it's a runtime error.

**Comment by hawken93** [comment]
I also have the impression that I would like to know why it was not initialized. Changing it to guid seems fine either way, but I am worried that this will just delay the problem

**Comment by cvium** [comment]
UserId is used to filter device sessions. Default is all. Setting UserId will only return the devices for that user.

**Comment by hawken93** [comment]
Hm, this opens up a bit of a new bag of questions for me..
If UserID was null, then the crash would be at line 156 of E.S.I/Devices/DeviceManager.cs but for me it was in 153. So this brings the question if this really fixes that issue.
On the other hand, that function assumes UserID is a guid on line 156 so to change it to a guid seems like a bugfix to me.

any idea what would make it crash on 153?..

**Comment by cvium** [comment]
@hawken93 I have no idea what could make it crash on 153. Nothing in the code seems to indicate a possible nullreference.

**Comment by JustAMan** [comment]
UserId might be assumed as guid, but I still think it is better be initialized explicitly.

**Comment by cvium** [comment]
I disagree with the initialization for two reasons:

1. UserId is a GET parameter that may or may not be present, so initialization is not really possible unless you want to use a separate model.
2. Guid.Empty is the default value already

**Comment by Bond-009** [comment]
I'm approve with this change.
The exceptions you are getting is because you don't set the `UserID`, but set `HasUser` to true.
https://github.com/jellyfin/jellyfin/blob/dev/Emby.Server.Implementations/Devices/DeviceManager.cs#L144
Just uncomment it and you should be fine.

**Comment by cvium** [comment]
> I'm approve of this change.
> The exceptions you are getting is because you don't set the `UserID`, but set `HasUser` to true.
> https://github.com/jellyfin/jellyfin/blob/dev/Emby.Server.Implementations/Devices/DeviceManager.cs#L144
> Just uncomment it and you should be fine.

Those are unrelated. `HasUser` will only select devices which have a UserId that is not null (I dunno why a device can have no users -- maybe Chromecast etc?).

**Comment by Bond-009** [comment]
Yeah, you are correct, I was a bit to fast in making conclusions.

**Comment by cvium** [comment]
I removed the filtering entirely. The Swagger ui says that the Devices endpoint takes no parameters, so who am I to disagree.

**Comment by cvium** [comment]
@nvllsvm Done

**Comment by hawken93** [comment]
@cvium Despite my scepticism, this fix seems to work! I don't know why it kept throwing line 153, maybe something weird in the build process or something I don't know about .NET...
Thank you! :)

**Pull request merged**
