### PR TITLE
Removed RemoveOldPlugins configuration flag

### LINKED ISSUE #12959: Old plugin folders not deleted at plugin update
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

After plugin update and Jellyfin restart new versions are installed but old versions folders are not deleted.
This has no effect until the plugin is disabled or deinstalled: at such point Jellyfin loads ALL folders and you found multiple versions of the plugin installed, each also updated at latest version !!

It happens now with TheTVDB plugin update from v17 to v18, but it also happened in past with all other non-bundled plugins and various Jellyfin versions.

When I discovered the issue I think was my Jellyfin setup but now happens again with fresh Jellyfin 10.10 instance.

### Reproduction steps

Update non bundled plugin to new version (automatically or manually).

### What is the current _bug_ behavior?

Previous version folders are still present.

### What is the expected _correct_ behavior?

When new version is correctly installed old folders must be deleted.

### Jellyfin Server version

10.10.0+

### Specify commit id

_No response_

### Specify unstable release number

_No response_

### Specify version number

_No response_

### Specify the build version

10.10.1

### Environment

- OS: Debian 12 on RPi4
- Virtualization: Docker (linuxserver image)
- Storage: local USB2 HDD with EXT4 filesystem
- Clients: Jellyfin Media Player, Android TV
- Browser: Firefox
- Plugins: TMDb Box Sets v11.0.0.0; TheTVDB v17.0.0.0 (and next v18.0.0.0)

### Jellyfin logs

[2024-11-03 16:19:55.242 +01:00] [INF] [8] Emby.Server.Implementations.Updates.InstallationManager: Plugin "installed": "TheTVDB" "18.0.0.0"
[2024-11-03 16:19:55.283 +01:00] [INF] [8] Emby.Server.Implementations.ApplicationHost: App needs to be restarted.
...
[2024-11-03 16:36:07.685 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TheTVDB" "18.0.0.0"

### FFmpeg logs

_No response_

### Client / Browser logs

_No response_

### Relevant screenshots or videos

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by RealGreenDragon**
Fixes #12959

### CODE REVIEW

**Comment by felix920506** [comment]
Might also fix #12136 and #9059
Can you test?

**Comment by RealGreenDragon** [comment]
I tested now with all following plugins and the behavior is correct for all:

- Open Subtitles
- Subtitle Extract
- TVMaze
- TheTVDB
- Trakt

So I thinks all issues regard old plugins versions not removed can be closed.

Obviously this default will be delivered with next major (or also in 10.10.x if possible) and only on new Jellyfin instances (any other must set `RemoveOldPlugins` to `true` manually).

**Comment by felix920506** [comment]
If you would like it to be released during 10.10.x then please change your PR to target the 10.10.z branch instead of master.

**Review by Shadowghost — APPROVED** [review]

**Comment by sjorge** [comment]
#13058 is most likely not fixed, it's usually the playback reporting plugin that causes it

**Comment by RealGreenDragon** [comment]
I have troubles to change target branch, I opened another PR for backport to 10.10.z.

**Comment by nielsvanvelzen** [comment]
I'm not sure why this configuration option exists as it's undocumented, makes more sense to remove the toggle entirely to me as keeping old versions of plugins does cause issues.
Not sure about backporting this change to 10.10.z though, as it is a behavior change that may come with new issues, better to keep it for 10.11.z.

**Comment by RealGreenDragon** [comment]
@nielsvanvelzen if you consider this approach better I can close backport PR and edit this PR to remove the parameter. Can I proceed in this way?

**Comment by joshuaboniface** [comment]
I merged the release-10.10.z version as-is, since I think that's the simplest/easiest way to fix the bug on stable going forward.

For this one though, I agree with @nielsvanvelzen it's probably better to just remove the option entirely going forward in this PR.

**Review by Bond-009 — APPROVED** [review]

**Review by crobibero — APPROVED** [review]

**Pull request merged**
