### PR TITLE
Make TMDb api key configurable, fix missing/wrong image urls

### PR DESCRIPTION
**Pull request by 1337joe**
The API key is added to the config file but not the user-facing plugin page. Most users should not mess with the key, but as discussed in #10529 some users like tracking their own API usage or dislike that using the Jellyfin key includes their statistics where someone else could possibly see.

To change the key open the TMDb plugin settings and hit save, then open `Jellyfin.Plugin.Tmdb.xml` (at `~/.local/share/jellyfin/plugins/configurations/Jellyfin.Plugin.Tmdb.xml` in my dev environment), set the `TmdbApiKey` value, and restart Jellyfin to pick up changes.

An empty or missing `TmdbApiKey` value will cause Jellyfin to use the Jellyfin key, which will not be saved to the xml file.

**Changes**
- Add API key to configuration file, as well as error handling for the plugin config page in case the key is invalid
- Fix missing posters in collection identify page
- Fix a case where poster settings were used for person profile images

**Issues**

### CODE REVIEW

**Comment by Shadowghost** [comment]
I am not sure if we should allow users to set their own API keys. Looking back at when our Trakt plugin had issues, the fix for trakt was quite easy: revoke our API key. If users set their own this is not possible.

**Comment by VigibotDev** [comment]
The problem retrieving collection posters is not related to the TMDb API key used. I still change the API key used by Jellyfin because there is no reason why my statistics should not arrive in my TMDb account. I use MITM-proxy to control outgoing data and/or have my own cache on the LAN so that Jellyfin does not go out on the internet in the event of a simple file movement.

**Comment by nielsvanvelzen** [comment]
> I am not sure if we should allow users to set their own API keys.

Yes, always. We should always respect user privacy and allow them to self-host/change API keys/etc. just like how we added support for self hosted chromecast receivers in 10.9 and allow changing API keys for virtually any plugin. I'm actually surprised this is not the case for the TMDb plugin yet.

**Comment by 1337joe** [comment]
> I'd at least argue we should not provide a UI for it.

That's the approach I took. Originally the plugin page broke if the key was invalid so I added enough error handling to report the error to the user, but to actually view or change it you have to modify the plugin settings xml.

**Review by JPVenson — APPROVED** [review]

**Review by Shadowghost — APPROVED** [review]

**Review by crobibero — APPROVED** [review]

**Review by Bond-009 — APPROVED** [review]

**Pull request merged**
