### PR TITLE
Remove all Fedora and CentOS specific files

### LINKED ISSUE #3040: Fedora 32 is out and emby packages are only for 31
Hi there is i think some low changes so i think adapting for fedora 32 seem to be easy ;)
The 31 version install for now i have to test if all works !

### LINKED ISSUE #3701: 10.6.0 RPM doesn't update previous versions
Because there is no `%files` section in the `jellyfin.spec` no _jellyfin_ package is produced and only a _jellyfin-server_ package is produced.  This leaves RPM with nothing to do.  The _jellyfin_ package is needed so that it upgrades an existing/installed _jellyfin_ package and that brings in the _jellyfin-server_ package.

### PR DESCRIPTION
**Pull request by oddstr13**
None of the regular contributors use a RPM based distro, leaving the rpm packaging constantly in a broken state.
As such, we are removing RPM packaging.

Both Fedora and CentOS have excellent support for Docker, and this will be the only officially supported way of installing Jellyfin on these platforms going forward.
You can alternatively use the binary tarballs produced each release, or compile from source.

Closes #3701
Closes #3040

Should these platforms be adopted by the community, they should live in a separate repository, for example `jellyfin-packaging-rpm`. A good example of a community-maintained platform is the [AUR packages](https://aur.archlinux.org/packages/?K=jellyfin) for Arch Linux.

### CODE REVIEW

**Comment by brianjmurrell** [comment]
I disagree with this.  I use the RPM packages and maintain a COPR build for jellyfin.  I have even suggested many times that RPM packaging be part of the regular CI build so that it doesn't regress.  That CI building could be done as a GitHub action using [mock](https://github.com/rpm-software-management/mock/wiki).

**Comment by sparky8251** [comment]
Then stop opening issues about the RPM packages @brianjmurrell and start opening PRs instead.

This is the end result of none of us being able or willing to maintain it and you and other RPM users reporting issues instead of fixing them.

**Comment by whalehub** [comment]
> Both Fedora and CentOS have excellent support for Docker, and this will be the only officially supported way of installing Jellyfin on these platforms going forward.

@oddstr13 Huh? Support for Docker was dropped in Fedora 32 and CentOS 8 respectively. It's not available from the default repositories anymore and doesn't work at all without first implementing a few workarounds.

**Comment by sparky8251** [comment]
> > Both Fedora and CentOS have excellent support for Docker, and this will be the only officially supported way of installing Jellyfin on these platforms going forward.
> 
> @oddstr13 Huh? Support for Docker was dropped in Fedora 32 and CentOS 8 respectively. It's not available from the default repositories anymore and doesn't work at all without first implementing a few workarounds.

Then you have tarballs. We include example init scripts for all 3 major init systems even so minor customization should work.

**Comment by joshuaboniface** [comment]
I agree with Sparky here. The simple fact is, I don't personally have time to keep maintaining a package format I don't use and that *should have been working* based on the ton of time we spent on it a few months ago. If it's still broken, I need someone who is an expert (or at least well-versed) in RPM to *actually fix it* to follow how our Debian package works. No one has offered to do so. I'm short for time and if no one is willing to maintain this package, it will either stay as-is or be dropped.

**Comment by brianjmurrell** [comment]
@sparky8251 You may or may not know but I contributed quite a bit of time reviewing and making suggestions on the recent packaging split for RPM.  Unfortunately the split was not quite what I had described and so now it is [broken](#3701) in that it doesn't upgrade pre-split installations.

As you can see I did open the ticket for that but in my proposal to fix I got push-back which seems to contradict the original goal of the split.  As you will also see, I am still trying to get clarification on what the goal is and the contradiction before I invest time into pushing a PR so that it doesn't immediately get rejected.

**Comment by joshuaboniface** [comment]
So the package split was quite simple in Debuntu land.

Instead of building one package, we build two: one for server, one for web. They are *completely* separate.

Then, we use `equivs-build` to build a metapackage that contains no files and exists only to have `Depends` on those two separate packages, to provide seamless transition.

The metapackage is not particularly important any more, the goal there was to try to provide a seamless upgrade path from the single-package format to the split package format. At this point I think that goal is past, since this was 95% of the complication here.

I'm not a Red Hat person, so I'm not certain exactly what's broken or where. All that matters at this point is having `jellyfin-server` and `jellyfin-web` RPM packages.

**Comment by joshuaboniface** [comment]
Though ultimately, if this becomes a 3rd party community build a la Arch that's also worthwhile. Then the maintainer can use any package format, do any combination, etc. they want. If someone wants to do this by all means please do.

**Comment by brianjmurrell** [comment]
> Then, we use equivs-build to build a metapackage that contains no files and exists only to have Depends on those two separate packages, to provide seamless transition.

Indeed.  That's the part that is missing from the RPM build that #3701 describes.  I proposed the fix there and @mooninite pushed back saying I was doing it wrong.  I asked for clarification on the intent and got no response to decide if my proposal was correct or if @mooninite's was to go ahead and create a PR.

> The metapackage is not particularly important any more, the goal there was to try to provide a seamless upgrade path from the single-package format to the split package format. At this point I think that goal is past, since this was 95% of the complication here.

I think the metapackage is still important as it provides the single package that (likely) most people will want to install to get a complete jellyfin installation.  I suspect requiring users to install both jellyfin-server and jellyfin-ui to get that complete installation is going to lead to confusion and "my jellyfin doesn't work" type help requests.

**Comment by joshuaboniface** [comment]
Thanks @brianjmurrell i replied to that issue with my thoughts!

**Comment by oddstr13** [comment]
> > Both Fedora and CentOS have excellent support for Docker, and this will be the only officially supported way of installing Jellyfin on these platforms going forward.
> 
> @oddstr13 Huh? Support for Docker was dropped in Fedora 32 and CentOS 8 respectively. It's not available from the default repositories anymore and doesn't work at all without first implementing a few workarounds.

@whalehub Then I was ill advised when drafting this PR, which just further illustrates just how little we as a team know about the platforms in question.

**Comment by crobibero** [comment]
Fedora and CentOS builds have been fixed, closing

**Pull request closed without merging**
