### PR TITLE
Added CHANGELOG

### PR DESCRIPTION
**Pull request by sparky8251**
With this, PRs should be denied that do not add to this file so that for the next release has its changelog largely written.

### CODE REVIEW

**Comment by joshuaboniface** [comment]
I've mentioned my thoughts on this in the Riot, but want to make them explicit here.

To be 100% honest, I don't see the point in a changelog file at all.

1. Git does this for us, that's one of its greatest features - `git log` and `git log --merges` provide information on what's been accepted/changed. *However* this requires diligence from PR submitters to ensure that:
    a. Only one major change per PR - no combining of multiple fixes. We need to work on this.
    b. The description and explanation are clear, concise, and meaningful. We *really* need to work on this, especially PR bodies.
2. If we can't do the above, I'm not sure what having a separate file will do to improve the situation. Adding checks for `CHANGELOG.md` just adds an additional review step when the description should already be providing the information we need, which will be in the merge request, and adds more work for the contributors, another file that can cause merge conflicts, etc.

I'm not against the idea of doing this automatically for releases, basically reformatting the `git log --merges` output into a reasonable format, but as a manual process per-PR it just seems like administrative overhead for little gain over just using `git`'s built-in features. I'm already doing this manually for the release PRs, making sure we include a link to every PR in that release, which functions as a changelog. We're also changing so much so quickly that even if we do have a `CHANGELOG.md`, the "who's gonna read it" problem still applies, only worse since we're limited to very short descriptions rather than being able to use Git's longer message format. How useful is (for example) "Refactored database code" to an end-user, really, which is what these changelog descriptions would have to be to remain concise. At least with Git we can provide a long and detailed explanation of the refactor in the body.

I also don't think a "changes from Emby" (something mentioned on Riot) is ever going to be viable. The answer from that is "a lot" and trying to document every change, especially when a lot of contributors don't use most of Emby's features (or never used Emby at all) just isn't feasible.

I'm open to suggestions, but that's my take on this.

**Comment by sparky8251** [comment]
Well, the reason I do this is that the git logs should be for developers, change logs for users.

Looking at other projects like [qbittorrent](https://www.qbittorrent.org/news.php), they too have simple "dumbed" down change logs for the end users to look over. Hence my suggestion we do actually keep the change logs incredibly simple.

Don't feel we need a 20 page release document including the full text of each PR and/or commit, we need a user friendly summary.

**Comment by joshuaboniface** [comment]
That output is exactly what every one of our PR titles should be.

**Comment by EraYaN** [comment]
The problem is some PRs might be superseded by others or implement the same function. So someone will need to edit the changelog anyway. So might as well so it somewhat custom. I proposed having a thing in the PRs template, so people can propose what their PRs needs to say (if anything) in the changelog. And then upon release someone runs a script and compiles them, sorts them, reformulates any if required. And then pushes the release.

**Comment by joshuaboniface** [comment]
A PR template is actually a much better idea. I've brought that up before but never wrote one - I can do so today however. Same with an issue template.

**Comment by sparky8251** [comment]
I just made this PR to spark the convo and share my ideas :) What ever we do, I just think it should be the "first" thing we do in 10.0.0 so the change logs can properly exist for 10.0.1.

**Comment by sparky8251** [comment]
Does this PR not count as a potential template? Seems like all its missing is links to issues it fixes.

**Comment by joshuaboniface** [comment]
I've added proper templates in #549 and #552 which should help a lot.

**Comment by joshuaboniface** [comment]
@sparky8251 Lemme know how the PR template looks, and we can close this one out if it's good! It should keep our PRs nice and organized for doing changelogs on release!

**Pull request closed without merging**
