### PR TITLE
[WIP]CSS slider fixes

### PR DESCRIPTION
**Pull request by Tthecreator**
This pull fixes issues on CSS as shown in #669

**Changes**
I've been changed the markup for the following browsers.

**Current State**
Chrome: Fully working
Opera: Fully working
Firefox: Mostly working (thumb is sometimes not perfectly vertically aligned.)
edge: Functionally working (thumb is sometimes not perfectly vertically aligned. CSS transitions don't work. Knob is not the same size as in other browsers.)
ie: Broken AF

**Issues**
This issue solved some cosmetic issues I found while looking at issue #618
The main issue I'm trying to solve here is explained in #669.

### CODE REVIEW

**Comment by hawken93** [comment]
afaik dashboard-ui is gone in dev and jellyfin-web/src has taken its place..

**Comment by hawken93** [comment]
My opinion is that Edge is enough and IE11 is disproportionate work / payoff..

**Comment by JustAMan** [comment]
I'm saying if it's easy let's fix IE11. But please move this PR to that repo: https://github.com/jellyfin/jellyfin-web

**Comment by cvium** [comment]
> I'm saying if it's easy let's fix IE11

I forgot to mention this. I agree with this.

**Comment by Tthecreator** [comment]
I already fixed it. I will now implement the issues in the right place, no problem. This time I'll get my git stuff right.

**Pull request closed without merging**
