### PR TITLE
Fix WebSocketConnection 

### LINKED ISSUE #6625: Stream crashin each 5-8min both using a phone and Android TV
**Describe the bug**
My stream crashes every 5-ish min most of the time on Android TV (MiBox S with Jellyfin for Android TV app). After I restart the whole host, I can watch a few episodes without crashes. Then I start one more, it crashes 3-5 times before it runs till the end. Every time, every 5minutes.

I confirmed using the Android app on my phone, the behavior is the same. Also, I have tried the beta app for Android TV, no change.

I use the latest docker image on the Ubuntu 20.4 host.
I redirected some of the IPs.

```yml
jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    hostname: jellyfin
    user: 1005:1002
    environment:
      # - PUID=1005
      # - PGID=1002
      # - TZ=Europe/Warsaw
      - JELLYFIN_PublishedServerUrl=https://jellyfin.example.com
      - JELLYFIN_hostwebclient=True
    volumes:
      - jellyfin_config:/config
      - entertainment_tv:/data/tvshows
      - entertainment_movies:/data/movies
    logging:
      driver: gelf
      options:
        tag: jellyfin
        gelf-address: "udp://<GRAYLOG_IP>:12201"
    restart: always
```
I connect to jellyfin via nginx proxy:
```
server {
    listen 443 ssl http2;
    proxy_buffering off;
    server_name  jellyfin.example.com;

    access_log  /var/log/nginx/jellyfin_access.log;
    error_log /var/log/nginx/jellyfin_error.log;

    include includes/ssl_common.conf;
    include includes/domain_cert.conf;

    # Security / XSS Mitigation Headers
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    # Content Security Policy
    # See: https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP
    # Enforces https content and restricts JS/CSS to origin
    # External Javascript (such as cast_sender.js for Chromecast) must be whitelisted.
    add_header Content-Security-Policy "default-src https: data: blob: http://image.tmdb.org; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' https://www.gstatic.com/cv/js/sender/v1/cast_sender.js https://www.youtube.com blob:; worker-src 'self' blob:; connect-src 'self'; object-src 'none'; frame-ancestors 'self'";
    # from: https://github.com/jellyfin/jellyfin/issues/2803
    #add_header Content-Security-Policy "default-src https: data: blob:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' https://www.gstatic.com/cv/js/sender/v1/cast_sender.js; worker-src 'self' blob:; connect-src 'self'; object-src 'none'; frame-ancestors 'self'";

    location = / {
        return 302 https://$host/web/;
    }

    location / {
        # Proxy main Jellyfin traffic
        proxy_pass http://jellyfin:8096;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
	proxy_hide_header X-Powered-By;	 ## Hides nginx server version from bad guys.
	proxy_set_header Range $http_range;  ## Allows specific chunks of a file to be requested.
	proxy_set_header If-Range $http_if_range;  ## Allows specific chunks of a file to be requested.
    }

    # location block for /web - This is purely for aesthetics so /web/#!/ works instead of having to go to /web/index.html/#!/
    location = /web/ {
        # Proxy main Jellyfin traffic
        proxy_pass http://jellyfin:8096/web/index.html;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
    }

    location /socket {
        # Proxy Jellyfin Websockets traffic
        proxy_pass http://jellyfin:8096;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
	proxy_hide_header X-Powered-By;	 ## Hides nginx server version from bad guys.
	proxy_set_header Range $http_range;  ## Allows specific chunks of a file to be requested.
	proxy_set_header If-Range $http_if_range;  ## Allows specific chunks of a file to be requested.
    }
}
```
**Server logs**:
```log
[2021-09-17 17:48:28.427 +00:00] [WRN] [33] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://jellyfin.example.com/Sessions/Playing" to "172.100.0.12" in 0:00:00.5593641 with Status Code 204
[2021-09-17 17:52:38.546 +00:00] [WRN] [22] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "172.100.0.12" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2021-09-17 17:52:38.697 +00:00] [INF] [22] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "172.100.0.12" closed
```
**Expected behavior**
Be able to watch movies without interrupts

**Additional context**
I decided to use VLC as the player, Exo does have the same behavior. While using VLC I can reopen the stream in the VLC app, but it still does crash after that " 5 min timeout".

### PR DESCRIPTION
**Pull request by DeclaredSins**
Fixes #6625 

This removes mainly about `bytesConsumed`. As I'm not 100% sure if it's the reason that is the issue in the first place.

### CODE REVIEW

**Comment by crobibero** [comment]
@DeclaredSins build is failing

**Comment by DeclaredSins** [comment]
> @DeclaredSins build is failing

uh lemme try to fix

**Comment by DeclaredSins** [comment]
> @DeclaredSins build is failing

should be fixed by now

**Comment by cvium** [comment]
Removing failing tests is not how you fix things

**Comment by nielsvanvelzen** [comment]
FYI: The linked issue (Android TV dropping WebSocket connections) is caused by the outdated WebSocket client used in the app. It should be fixed eventually when the app moves it's WebSocket code to the new Kotlin SDK (which is already partially used for API calls).

**Comment by DeclaredSins** [comment]
> FYI: The linked issue (Android TV dropping WebSocket connections) is mainly caused by the outdated WebSocket client used in the app. It should be fixed eventually when the app moves it's WebSocket code to the new Kotlin SDK (which is already partially used for API calls).

Oh, thank you. I thought it was about the server, sorry! I'll just close the pull request.

**Pull request closed without merging**
