### PR TITLE
Add Env Var to disable WAL journaling

### LINKED ISSUE #11459: [Issue]: Jellyfin database locks up after a bit of playback on unraid
### Please describe your bug

Any version past 2024040106 locks up after I play media for a while. The time it takes seems to depend on how many streams are running. It sometimes recovers after a few minutes only to lock up again. My appdata share is located on an unassigned device, however the issue seems to persist even when its on an regular array disk.

### Reproduction Steps

1. Update to any release newer than 2024040106
2. Stream media
3. Jellyfin locks up

### Jellyfin Version

Unstable (master branch)

### if other:

_No response_

### Environment

```markdown
- OS: Unraid 6.12.5 
- Linux Kernel:6.1.63-Unraid
- Virtualization: Docker
- Clients: Any
- Browser: Any
- FFmpeg Version: whichever comes prepackaged
- Playback Method: Direct Stream
- Hardware Acceleration:QSV
- GPU Model:UHD Graphics 600
- Plugins: none
- Reverse Proxy: none
- Base URL: none
- Networking: Host, Bridge, doesnt matter.
- Storage: local unassigned xfs device
```

### Jellyfin logs

```shell
[2024-04-27 10:24:37.125 +02:00] [WRN] [195] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "[REDACTED_IP]" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2024-04-27 10:25:36.392 +02:00] [ERR] [139] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: "Unexpected end of request content". URL "POST" "/Sessions/Playing/Progress".
[2024-04-27 10:25:41.409 +02:00] [WRN] [213] Trakt.ServerMediator: Received playback progress from user "Mathias" but initial state was never set - setting it now!
[2024-04-27 10:26:07.360 +02:00] [WRN] [189] Trakt.ServerMediator: Received playback progress from user "Mathias" but initial state was never set - setting it now!
[2024-04-27 10:34:12.517 +02:00] [WRN] [211] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "[REDACTED_IP]" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2024-04-27 10:38:29.790 +02:00] [WRN] [146] Trakt.ServerMediator: Received playback progress from user "Mathias" but initial state was never set - setting it now!
[2024-04-27 10:39:04.140 +02:00] [ERR] [159] Jellyfin.Api.WebSocketListeners.SessionInfoWebSocketListener: Error sending web socket message Sessions
System.Net.WebSockets.WebSocketException (0x80004005): The WebSocket is in an invalid state ('Closed') for this operation. Valid states are: 'Open, CloseReceived'
   at System.Net.WebSockets.ManagedWebSocket.SendAsync(ReadOnlyMemory`1 buffer, WebSocketMessageType messageType, WebSocketMessageFlags messageFlags, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at MediaBrowser.Controller.Net.BasePeriodicWebSocketListener`2.SendDataInternal(TReturnDataType data, ValueTuple`3 tuple)
[2024-04-27 10:40:44.740 +02:00] [WRN] [240] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "[REDACTED_IP]" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2024-04-27 10:42:47.791 +02:00] [ERR] [732] Emby.Server.Implementations.Session.SessionManager: Error reporting playback progress
MediaBrowser.Common.Extensions.ResourceNotFoundException: Session 6ed53583a0005c48016225590291bbb1 not found.
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2024-04-27 10:42:48.790 +02:00] [ERR] [736] Emby.Server.Implementations.Session.SessionManager: Error reporting playback progress
MediaBrowser.Common.Extensions.ResourceNotFoundException: Session 6ed53583a0005c48016225590291bbb1 not found.
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2024-04-27 10:42:49.792 +02:00] [ERR] [740] Emby.Server.Implementations.Session.SessionManager: Error reporting playback progress
MediaBrowser.Common.Extensions.ResourceNotFoundException: Session 6ed53583a0005c48016225590291bbb1 not found.
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)

(This repeats about 100 times)

[2024-04-27 10:43:37.865 +02:00] [ERR] [810] Microsoft.EntityFrameworkCore.Database.Command: Failed executing DbCommand ("50,977"ms) [Parameters=["@p0='?' (DbType = DateTime), @p1='?', @p2='?' (DbType = Int32), @p3='?' (Size = 36), @p4='?', @p5='?' (DbType = UInt32), @p6='?' (Size = 50), @p7='?' (Size = 12), @p8='?' (DbType = Guid)"], CommandType='Text', CommandTimeout='30']"
""INSERT INTO \"ActivityLogs\" (\"DateCreated\", \"ItemId\", \"LogSeverity\", \"Name\", \"Overview\", \"RowVersion\", \"ShortOverview\", \"Type\", \"UserId\")
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8)
RETURNING \"Id\";"
[2024-04-27 10:43:37.881 +02:00] [ERR] [810] Microsoft.EntityFrameworkCore.Update: An exception occurred in the database while saving changes for context type '"Jellyfin.Server.Implementations.JellyfinDbContext"'."
""Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 6: 'database table is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)"
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 6: 'database table is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Jellyfin.Server.Implementations.Activity.ActivityManager.CreateAsync(ActivityLog entry)
   at Jellyfin.Server.Implementations.Activity.ActivityManager.CreateAsync(ActivityLog entry)
   at Jellyfin.Server.Implementations.Events.Consumers.Session.SessionEndedLogger.OnEvent(SessionEndedEventArgs eventArgs)

(this repeats until i restart jellyfin)
```

### FFmpeg logs

```shell
-
```

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by gnattu**
**Changes**

SQLite WAL journaling is not compatible with all filesystems/VFS extensions, causing the database being locked up in certain conditions. 

It's worth noting that database lockup is just one potential issue that can arise from compatibility issues with certain filesystems. In some cases, the use of WAL can even lead to the database being saved in a non-consistent state, resulting in database corruption.

Add an env var to let the user to choose the Journal mode for better compatibility.

For example, when the default WAL is causing problems:

```
export JELLYFIN_SQLITE__JOURNALMODE=TRUNCATE
```

**Issues**

### CODE REVIEW

**Comment by Bond-009** [comment]
Why not make the option a string so users can set any journalmode they want?

**Comment by gnattu** [comment]
> Why not make the option a string so users can set any journalmode they want?

Because of too many potential user errors?

**Comment by joshuaboniface** [comment]
I agree with making it an option. On supported systems this can improve DB performance right? So it can be beneficial in those cases.

**Comment by joshuaboniface** [comment]
Also do we know exactly which filesysts have the issue? We can adjust packaging defaults if we know that.

**Comment by gnattu** [comment]
> Also do we know exactly which filesysts have the issue? We can adjust packaging defaults if we know that.

You cannot predict this, the user can literally use any filesystem they want.

**Comment by gnattu** [comment]
> Will enabling pooling fix it?

I'm not very sure because I don't have the exact environment of the users. Probably this needs to be an extra option to let the user choose.

**Comment by memehammad** [comment]
Any easy way to try this out?

**Comment by gnattu** [comment]
> Any easy way to try this out?

I compiled a tarball for the docker image: https://github.com/gnattu/jellyfin/releases/tag/env-disable-wal

Sorry but this is probably the easiest way I can prepare for you.

**Comment by jmqm** [comment]
Wouldn't it be better if `TRUNCATE` is the default value if `WAL` can be problematic on some filesystems?

**Comment by gitdeath** [comment]
> > Any easy way to try this out?
> 
> I compiled a tarball for the docker image: https://github.com/gnattu/jellyfin/releases/tag/env-disable-wal
> 
> Sorry but this is probably the easiest way I can prepare for you.

Attempted to test this with a known Database is Locked file system use case, but the below compose seems to create a database still using WAL - `jellyfin.db-wal` file is still created in the config/data directory and `PRAGMA journal_mode;` returns `wal`

```
version: '3.8'
services:

  jellyfin-dev:
    image: jellyfin-disable-wal
    user: 0:100
    environment:
     - TZ=America/Chicago
     - JELLYFIN_SQLITE__JOURNALMODE=TRUNCATE

    networks:
     - default
    ports:
     - 8097:8096
     - 8927:8920
     - 1907:1900

    volumes:
     - jellyfin_dev_config:/config
     - jellyfin_dev_cache:/cache
     - media:/media:ro
```

**Comment by memehammad** [comment]
That'd explain why this didn't fix my issue lol

**Comment by gitdeath** [comment]
> That'd explain why this didn't fix my issue lol

I'm very interested to see if this does in fact improve the situation. Because from what I can tell, for use cases that work in 10.8, but not 10.9, the problem is the switch to MS.SQL from SQL.pretty - it seems to have a performance hit on some FS that results in the database is locked issues. 

Now the MS.SQL change needs to happen, if the plan is to open up other database backends - but that isn't available yet, so I don't know if this was required to do before that.

If this WAL to TRUNCATE doesn't pan out, then I'll fork Jelly and reverse the changes from the below PR for a test.

https://github.com/jellyfin/jellyfin/pull/10138

**Comment by crobibero** [comment]
After testing I can confirm that Jellyfin does set the `journal_mode` correctly, but it is only available during the connection- not from the cli. I verified with the following patch:

```
Index: Emby.Server.Implementations/Data/BaseSqliteRepository.cs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/Emby.Server.Implementations/Data/BaseSqliteRepository.cs b/Emby.Server.Implementations/Data/BaseSqliteRepository.cs
--- a/Emby.Server.Implementations/Data/BaseSqliteRepository.cs	(revision 8d8fcada18674becfcde6875d11e78a32d06c04d)
+++ b/Emby.Server.Implementations/Data/BaseSqliteRepository.cs	(date 1715531783505)
@@ -121,6 +121,12 @@
             if (!string.IsNullOrWhiteSpace(JournalMode))
             {
                 connection.Execute("PRAGMA journal_mode=" + JournalMode);
+
+                using var cmd = connection.CreateCommand();
+                cmd.CommandText = "PRAGMA journal_mode;";
+                using var reader = cmd.ExecuteReader();
+                reader.Read();
+                var currentJournalMode = reader.GetString(0);
             }
 
             if (JournalSizeLimit.HasValue)
```

**Comment by gitdeath** [comment]
> After testing I can confirm that Jellyfin does set the `journal_mode` correctly, but it is only available during the connection- not from the cli. I verified with the following patch:
> 
> ```
> Index: Emby.Server.Implementations/Data/BaseSqliteRepository.cs
> IDEA additional info:
> Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> <+>UTF-8
> ===================================================================
> diff --git a/Emby.Server.Implementations/Data/BaseSqliteRepository.cs b/Emby.Server.Implementations/Data/BaseSqliteRepository.cs
> --- a/Emby.Server.Implementations/Data/BaseSqliteRepository.cs	(revision 8d8fcada18674becfcde6875d11e78a32d06c04d)
> +++ b/Emby.Server.Implementations/Data/BaseSqliteRepository.cs	(date 1715531783505)
> @@ -121,6 +121,12 @@
>              if (!string.IsNullOrWhiteSpace(JournalMode))
>              {
>                  connection.Execute("PRAGMA journal_mode=" + JournalMode);
> +
> +                using var cmd = connection.CreateCommand();
> +                cmd.CommandText = "PRAGMA journal_mode;";
> +                using var reader = cmd.ExecuteReader();
> +                reader.Read();
> +                var currentJournalMode = reader.GetString(0);
>              }
>  
>              if (JournalSizeLimit.HasValue)
> ```

I've was unable to produce a state with this package (fresh install) that doesn't end with the creation of the WAL file. Is it possible Jellyfin is making multiple connections to the database? It would seem that if any connection sets to WAL then all will see WAL unless they specifically change for their connection. 

https://www.sqlite.org/wal.html - Section 3.3

```
3.3. Persistence of WAL mode
Unlike the other journaling modes, [PRAGMA journal_mode=WAL](https://www.sqlite.org/pragma.html#pragma_journal_mode) is persistent. If a process sets WAL mode, then closes and reopens the database, the database will come back in WAL mode. In contrast, if a process sets (for example) PRAGMA journal_mode=TRUNCATE and then closes and reopens the database will come back up in the default rollback mode of DELETE rather than the previous TRUNCATE setting.

The persistence of WAL mode means that applications can be converted to using SQLite in WAL mode without making any changes to the application itself. One has merely to run "PRAGMA journal_mode=WAL;" on the database file(s) using the [command-line shell](https://www.sqlite.org/cli.html) or other utility, then restart the application.

The WAL journal mode will be set on all connections to the same database file if it is set on any one connection.
```

**Comment by gnattu** [comment]
> > After testing I can confirm that Jellyfin does set the `journal_mode` correctly, but it is only available during the connection- not from the cli. I verified with the following patch:
> > ```
> > Index: Emby.Server.Implementations/Data/BaseSqliteRepository.cs
> > IDEA additional info:
> > Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> > <+>UTF-8
> > ===================================================================
> > diff --git a/Emby.Server.Implementations/Data/BaseSqliteRepository.cs b/Emby.Server.Implementations/Data/BaseSqliteRepository.cs
> > --- a/Emby.Server.Implementations/Data/BaseSqliteRepository.cs	(revision 8d8fcada18674becfcde6875d11e78a32d06c04d)
> > +++ b/Emby.Server.Implementations/Data/BaseSqliteRepository.cs	(date 1715531783505)
> > @@ -121,6 +121,12 @@
> >              if (!string.IsNullOrWhiteSpace(JournalMode))
> >              {
> >                  connection.Execute("PRAGMA journal_mode=" + JournalMode);
> > +
> > +                using var cmd = connection.CreateCommand();
> > +                cmd.CommandText = "PRAGMA journal_mode;";
> > +                using var reader = cmd.ExecuteReader();
> > +                reader.Read();
> > +                var currentJournalMode = reader.GetString(0);
> >              }
> >  
> >              if (JournalSizeLimit.HasValue)
> > ```
> 
> I've was unable to produce a state with this package (fresh install) that doesn't end with the creation of the WAL file. Is it possible Jellyfin is making multiple connections to the database? It would seem that if any connection sets to WAL then all will see WAL unless they specifically change for their connection.
> 
> https://www.sqlite.org/wal.html - Section 3.3
> 
> ```
> 3.3. Persistence of WAL mode
> Unlike the other journaling modes, [PRAGMA journal_mode=WAL](https://www.sqlite.org/pragma.html#pragma_journal_mode) is persistent. If a process sets WAL mode, then closes and reopens the database, the database will come back in WAL mode. In contrast, if a process sets (for example) PRAGMA journal_mode=TRUNCATE and then closes and reopens the database will come back up in the default rollback mode of DELETE rather than the previous TRUNCATE setting.
> 
> The persistence of WAL mode means that applications can be converted to using SQLite in WAL mode without making any changes to the application itself. One has merely to run "PRAGMA journal_mode=WAL;" on the database file(s) using the [command-line shell](https://www.sqlite.org/cli.html) or other utility, then restart the application.
> 
> The WAL journal mode will be set on all connections to the same database file if it is set on any one connection.
> ```

If I understand it right the persistency is stored into the database itself and the connection will be created in WAL on default.

It should not affect the rest of the connection after marking it with TRUNCATE though.

**Comment by gnattu** [comment]
Closing as we will do no more 10.9 releases and the db issues seems to be fixed without the need to disable WAL

**Pull request closed without merging**
