### PR TITLE
Admin and first setup pages default to dark theme

### PR DESCRIPTION
**Pull request by sparky8251**
Since the user facing sides of the UI (login and library) are all dark theme by default, changes the default look for the admin sides (first time setup, admin panel) as well.

### CODE REVIEW

**Comment by sparky8251** [comment]
Addresses both #322 and #308.

**Comment by sparky8251** [comment]
I do not follow. This only changes the default theme from one to another and adds in the few "special" lines it requires for unique first time setup wizard elements.

No changes other than that.

**Comment by nvllsvm** [comment]
The attributes you added to the CSS file should added to all the themes. If someone were reading the theme files, they might be confused why only the dark theme has these changes.

**Comment by nvllsvm** [comment]
Just add the new elements to each for now.

**Comment by nvllsvm** [comment]
Oh awesome! Thanks for matching the colors!

**Pull request merged**
