### PR TITLE
Add external provider links to season and episode

### PR DESCRIPTION
**Pull request by SenorSmartyPants**
Based on #7134, add more external provider links to season and episode pages.

Season: add links to IMDb, TMDb, Trakt
Episode: add link to TMDb

### CODE REVIEW

**Comment by SenorSmartyPants** [comment]
### Before
image
image

### After
image
image

**Comment by crobibero** [comment]
I think at this point it's probably better to just add an interface so plugins can add their own external URLs... I have a WIP branch that I'll put up tomorrow

**Comment by JPVenson** [comment]
If i see that correctly this is fixed by #7222

**Comment by SenorSmartyPants** [comment]
> If i see that correctly this is fixed by #7222

I don't think that was ever implemented. PR is closed not merged.

**Comment by JPVenson** [comment]
wups sory wrong PR. But the functionality is on 10.8.13 as i just checked

**Comment by SenorSmartyPants** [comment]
If you could share which PR adds this functionality you mention I would appreciate it. My searching on https://github.com/orgs/jellyfin/projects/29 didn't have much luck.

**Pull request closed without merging**
