### PR TITLE
Always scan ReplayGain tag

### PR DESCRIPTION
**Pull request by Bond-009**
* Removes the UseReplayGainTags option from the LibraryOptions
* Removes extra ffrobe instance when option was enabled
* Makes LUFS value nullable

cc @TelepathicWalrus

### CODE REVIEW

**Review by Shadowghost — APPROVED** [review]

**Comment by gnattu** [comment]
This will also Fixes #11413 as the additional ffprobe for LUFS tags is eliminated.

**Comment by Bond-009** [comment]
@gnattu I'm not sure it does, this didn't spawn ffprobe with the same args, only with `-hide_banner -i`

**Review by nielsvanvelzen — APPROVED** [review]
✅ API changes

**Review by crobibero — APPROVED** [review]

**Comment by nielsvanvelzen** [comment]
@Bond-009 will you also be making the required changes to remove the `UseReplayGainTags` option in jellyfin-web?

**Pull request merged**
