### PR TITLE
Update TMDB external id names to include specific types

### PR DESCRIPTION
**Pull request by lfoust**
**Changes**
The different implementations of `IExternalId` for TMDB all use `TmdbUtils.ProviderName` as the value for their `Name` property. So if multiple TMDB external IDs are displayed on the same form their is no way to distinguish them.

This change adds a distinguishing type name to each TMDB `IExternalId` implementation. I am not familiar with the localization process within Jellyfin so please provide any feedback here. Although the results here look fine in English but may not work in other languages:

image

**Issues**
jellyfin#2223

### CODE REVIEW

**Comment by lfoust** [comment]
> I guess you can do it this way or localize in web-ui. I think I am more for the second approach...

So it should be the responsibility of each client to localize? That doesn't seem to scale well to multiple clients. Are you assuming that this particular UI will only be used on web-ui?

**Comment by dkanada** [comment]
It's usually much easier to let clients handle localization in my opinion. We do the same translation stuff with the notification types. The descriptions and summaries are all localized on the server, but I think it might make more sense to just pass IDs when requested and let clients do whatever they want with that information rather than deal with localizing on the server. Is the server localization truly that convenient?

**Comment by JustAMan** [comment]
The thing here is not about being easy or hard, it's about being _right_ to do.
It's the clients which do representation to the end user, so they should take as much of that responsibility as possible (also server is already complex enough, but that's completely another story).

**Comment by lfoust** [comment]
I guess we just fundamentally disagree. Requiring all clients to have copies of the language resource files versus just having one copy in the server seems like a lot of extra work. Also, clients have to parse all strings coming from the server to check if they have tokens which need to be translated and replaced. Forgetting to do so could result in tokens being displayed in the UI.

I'll try preparing a PR which does translation on the client to see how it looks. Thanks!

**Comment by dkanada** [comment]
@lfoust we uncovered some other provider name issues in web recently that seem very similar. Were you planning on making changes to this pull request? I'll see if I can find the related issue.

**Comment by lfoust** [comment]
@dkanada - I started down the road of translating on the client but didn't get it check in ready. I am willing to look at the related issue and get this ready for checkin if you would like me to. Let me know when you find the related issue(s).

**Comment by Artiume** [comment]
https://github.com/jellyfin/jellyfin-web/issues/900

**Comment by lfoust** [comment]
Here is the PR with the updated approach of localization on the client: #2643

**Comment by dkanada** [comment]
replaced by #2643

**Pull request closed without merging**
