### PR TITLE
Fix non-ascii filename downloads

### PR DESCRIPTION
**Pull request by DrPandemic**
**Changes**
The issue is caused by the fact that kestrel currently doesn't accept non-ASCII characters in headers. It might be fixed in .NET Core 3.0 https://github.com/aspnet/AspNetCore/issues/4727. But for now, this PR manually follows https://tools.ietf.org/html/rfc5987#section-3.2.2 to encode UTF-8 filenames.

I decided to only encode that specific header and only the instances with UTF-8 characters to limit the impact if there's an issue with the PR. 

Was tested on Mac with Chrome, Firefox and Safari.

**Issues**
Closes https://github.com/jellyfin/jellyfin/issues/1289

### CODE REVIEW

**Comment by anthonylavado** [comment]
@jellyfin/backend Should this be in the release patch?

**Comment by DrPandemic** [comment]
I think this could go in 10.3.2, it's a small fix

**Comment by anthonylavado** [comment]
@DrPandemic There's likely to be a 10.3.3, if you wanted to try to get in for that.

**Comment by DrPandemic** [comment]
Sure, let me test it on it. Do you want me to change the target branch?

**Comment by DrPandemic** [comment]
Alright, tested and it works and pointing to 10.3.z

**Pull request merged**
