### PR TITLE
Update kz.csv

### PR DESCRIPTION
**Pull request by WWWesten**
Update to the new ratings system

**Changes**

**Issues**

### CODE REVIEW

**Comment by WWWesten** [comment]
https://github.com/jellyfin/jellyfin/issues/918

**Comment by anthonylavado** [comment]
Approved and merged. Build was failing the ABI check, not because of this :-)

**Comment by Bond-009** [comment]
FYI these files won’t get updated on existing installs if they already exists.

**Comment by anthonylavado** [comment]
@bond-009 Hrm I see your point. Anything we can do?

**Comment by JustAMan** [comment]
I think we should make a note in "Release Notes", at least for now.
We aren't going to update those ratings files very often, now are we?

**Comment by joshuaboniface** [comment]
@Bond-009 Why wouldn't it? At least for the OS packages, it will copy over them since they're not "config files".

**Pull request merged**
