### PR TITLE
Fix comparison for empty password migration

### PR DESCRIPTION
**Pull request by cvium**
Untested, but it should fix the empty pw migration issues

### CODE REVIEW

**Comment by hawken93** [comment]
What does this mean for us that just migrated to 10.3.0?

**Comment by cvium** [comment]
Hopefully it'll be fixed.

**Comment by hawken93** [comment]
I think I understand the changes now and what it means in practice is nothing, we're fine security wise :)

**Comment by xhaloz** [comment]
Issue is still occurring with AndroidTV app.  Tried resetting password and disabling easy pin option.  Error received is Invalid User ID and/or Password.

**Comment by anthonylavado** [comment]
>Issue is still occurring with AndroidTV app.  Tried resetting password and disabling easy pin option.  Error received is Invalid User ID and/or Password.

@xhaloz The Android TV app will likely need an update. Cc @thornbill

**Pull request merged**
