### PR TITLE
Fix QSV subtitle burn-in on windows and P010 detect

### PR DESCRIPTION
**Pull request by nyanmisaka**
**Changes**
- fix QSV graphical subtitle burn-in on windows.
- fix 10-bit detect for VP9 Profile 2.
- reduce CPU usage and enhance speed when burning in text subtitle using QSV.
- expose AMD AMF encoding quality settings to user.
- utilize HWA deint filters in `h264_cuvid` and `vpp_qsv`.

**Issues**
- https://github.com/jellyfin/jellyfin/issues/2626
- https://github.com/jellyfin/jellyfin/issues/3488

### CODE REVIEW

**Comment by frankyifei** [comment]
I know this is merged. 
Just want to share my test result: it works on some of my movies. When it does not, it through an error of "[AVHWFramesContext @ 000001fbff23c0c0] Error synchronizing the operation: -3" 
I have no idea what causes this. I suspected there are some difference between the two types. DVD subtitles have their own resolution which sometimes not equal to the video's resolution. When this is the case, the transcoding would fail. And the commands used for the two types are slightly different. I managed to make ffmpeg work on both types by modify the commands. The failed one using this "vpp_qsv=format=nv12[base]" in the command, the working one using vpp_qsv=w=1280:h=720:format=nv12[base]. 
[Failled.log](https://github.com/jellyfin/jellyfin/files/4946380/Failled.txt)
[working.log](https://github.com/jellyfin/jellyfin/files/4946381/working.txt)

**Comment by nyanmisaka** [comment]
> @nyanmisaka, I know this is merged.
> Just want to share my test result: it works on some of my movies. When it does not, it throw an error of "[AVHWFramesContext @ 000001fbff23c0c0] Error synchronizing the operation: -3"
> I have no idea what causes this. I suspected there are some difference between the two types. DVD subtitles have their own resolution which sometimes not equal to the video's resolution. When this is the case, the transcoding would fail. And the commands used for the two types are slightly different. I managed to make ffmpeg work on both types by modify the commands. The failed one using this "vpp_qsv=format=nv12[base]" in the command, the working one using vpp_qsv=w=1280:h=720:format=nv12[base].
> [Failled.log](https://github.com/jellyfin/jellyfin/files/4946380/Failled.txt)
> [working.log](https://github.com/jellyfin/jellyfin/files/4946381/working.txt)

I have fixed that part yesterday in this PR : https://github.com/jellyfin/jellyfin/pull/3615

**Comment by hellcry37** [comment]
is this getting fixed ever or ....?

**Comment by nielsvanvelzen** [comment]
This pull request was includes in the 10.6.x release branch. Please create an issue if you experience any issues.

**Pull request merged**
