### PR TITLE
Install the dotnet runtime package in Fedora build

### PR DESCRIPTION
**Pull request by joshuaboniface**
**Changes**
This is needed since `/usr/bin/dotnet` doesn't appear to exist in the `dotnet-sdk-2.2` DNF package for whatever reason as of Feb 18 2019. I think a combination of this and a cached setup somehow led me to think #940 was needed, but this seems unnecessary with this fix.

Error message without:

```
+ dotnet publish --configuration Release --output=/root/rpmbuild/BUILDROOT/jellyfin-10.2.1-1.fc29.x86_64/usr/lib64/jell
yfin --self-contained --runtime fedora-x64 Jellyfin.Server                                                             
/var/tmp/rpm-tmp.vGt0JK: line 38: dotnet: command not found                                                            
error: Bad exit status from /var/tmp/rpm-tmp.vGt0JK (%install)                                                         
    Bad exit status from /var/tmp/rpm-tmp.vGt0JK (%install)
```

**Issues**
N/A

### CODE REVIEW

**Comment by brianjmurrell** [comment]
Note #967 based on this branch.  Feel free to land that here before you land this to [release-10.2.z](https://github.com/jellyfin/jellyfin/tree/release-10.2.z).

**Comment by brianjmurrell** [comment]
@JustAMan Cheers!

**Comment by joshuaboniface** [comment]
Hold off on merging until tonight I want to double check some things.

**Comment by JustAMan** [comment]
@joshuaboniface if all is good go ahead and merge!

**Comment by brianjmurrell** [comment]
Can this be merged yet?

**Comment by joshuaboniface** [comment]
@brianjmurrell Didn't get a chance last night, trying to think about whether to target this at the release branch or master and wait - the latter would mean this wouldn't land until 10.3.0.

**Comment by brianjmurrell** [comment]
Thanks @joshuaboniface!

**Pull request merged**
