### PR TITLE
add taglib and imagemagick to sln

### PR DESCRIPTION
**Pull request by dkanada**
Are these libraries supposed to be built at the moment? They weren't in the sln file. Also, the taglib submodule seems to throw an error that it only works with .NetFramework 4.0 and not Core on my machine.

### CODE REVIEW

**Comment by LogicalPhallacy** [comment]
The current SLN in master works fine for me in full visual studio IF you make sure you pull submodules as well. I wasn't having the hangup with imagemagick but I was with taglib and what was happening was git wasn't getting the submodules down right. Try git submodule update --init --recursive on the latest and see if you are ok afterwards

**Comment by dkanada** [comment]
Yeah I pulled the submodules, the exact error is below which made me think it might be a different issue. @nvllsvm what error did you get with the changes here?

`Error NU1201: Project taglib-sharp is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Project taglib-sharp supports: net40 (.NETFramework,Version=v4.0) (NU1201) (Emby.Photos)`

**Comment by dkanada** [comment]
I would try installing dotnet4.0 but I was under the impression only dotnetCore was required to build this project.

**Comment by nvllsvm** [comment]
I'll apaste it when I'm back on my workstation. For now, try building the Docker image. It's a portable environment that should replicate the problem I'm seeing.

**Comment by dkanada** [comment]
Just tried the docker image, it throws the same error I posted above using this patch.

**Comment by BnMcG** [comment]
They're in the sln file on master currenty (https://github.com/jellyfin/jellyfin/blob/f0c3789795f621f81e6e9a7cb584bad65b7d2634/MediaBrowser.sln#L59) 

I submitted a PR to add them a few hours ago since I had very similar problems to you (in Rider on MacOS). Everything is now working for me - @nvllsvm's changes removed a few of the build configurations for these projects (I think), which seemed to break the Docker build. 

Even after merging his changes, these projects are still part of the solution and building still works fine for me on MacOS.

**Comment by dkanada** [comment]
They're in the sln but they dont seem to be included in any of the build versions below, which I think is causing my issues. I am using the latest commit from master though so I don't think it's a `git pull` issue.

**Comment by BnMcG** [comment]
Which platform are you on?

**Comment by dkanada** [comment]
Arch Linux, same as @nvllsvm.

**Comment by BnMcG** [comment]
I'll try readding the removed build configs and getting docker build to work, they're not building on my workstation either.

-------- Original Message --------

**Comment by dkanada** [comment]
According to [this](https://github.com/mono/taglib-sharp/issues/94#issuecomment-375153720) comment mono is also required to build taglib-sharp. I am not sure whether or not that dependency is open source, but I also don't see it in the build files, so I am wondering why the docker image works without mentioning mono.

**Comment by BnMcG** [comment]
That's a good point, I also needed mono installed before everything started working. I wonder if we could split TagLibSharp and ImageMagickSharp out into nuget binary dependencies so that they didn't require building with the solution?

-------- Original Message --------

**Comment by JustAMan** [comment]
Before the full Jellyfin started I think I built everything using only dotnet core 2.1, no Mono was required. I wasn't rebuilding TagLib, though.

@dkanada note that one of your errors seems to point to "netcore-app", not just "netcore". I'm not proficient with .net, but that looks strange.

**Comment by Bond-009** [comment]
@BnMcG publishing our own taglib-sharp nuget package doesn't seem like a good idea. The best solution (IMO) is waiting till someone at mono releases a new taglib-sharp nuget package, since the current one is from 2012.
taglib-sharp issue: https://github.com/mono/taglib-sharp/issues/40

**Comment by BnMcG** [comment]
@Bond-009 Agreed if that's an option, there doesn't seem to be much movement on mono/taglib-sharp#40, though.

**Comment by BnMcG** [comment]
@dkanada, Can you try pulling https://github.com/bnmcg/jellyfin/tree/build-thirdparty and building with this branch? I reverted [this commit](https://github.com/jellyfin/jellyfin/commit/6810487989aa1df1527f3b0a0360047aebe80df9) and now ImageMagickSharp and TagLibSharp build for me again.

Is this also the case for you?

**Comment by dkanada** [comment]
@BnMcG nope I get the same error, which is weird because MonoDevelop recognizes my Mono installation.

**Comment by joshuaboniface** [comment]
We should be aiming to remove aall Mono dependencies in favour of .NET Core if at all possible.

**Comment by BnMcG** [comment]
I'll try ditching mono on my branch in the comment above and let you know how it goes.

-------- Original Message --------

**Comment by nvllsvm** [comment]
@joshuaboniface https://github.com/jellyfin/jellyfin/issues/95

**Comment by dkanada** [comment]
I've been testing some stuff and it looks like the docker build errors go away when the framework is specified. Unfortunately two projects are using netcoreapp2.1 instead of netstandard2.0 so I haven't got it building yet.

**Comment by dkanada** [comment]
The easiest solution is to just remove the `net45` and `net40` target frameworks from ImageMagick and taglib-sharp, but we currently include taglib-sharp as a submodule. I tried the docker recipe with this change and the didn't see any errors from the build step. This also fixed my dev environment which was nice. I previously had to manually remove `net40` from taglib-sharp to build Jellyfin.

**Comment by dkanada** [comment]
Not the same error message but [this thread](https://github.com/Microsoft/DockerTools/issues/34) has a lot of people reporting issues using `<TargetFrameworks>` instead of `<TargetFramework>` and also mentions the same fix.

**Comment by dkanada** [comment]
I am closing this to rebase on develop since pull requests go there now.

**Pull request closed without merging**
