### PR TITLE
Fix possible memory leak caused by unhandled WebSocket exception

### PR DESCRIPTION
**Pull request by OancaAndrei**
Clients can close a WebSocket connection without sending the "close handshake". This raises an exception that was previously catched too late, missing to call `socket.Dispose()` which in turn caused `Closed` events in `SharpWebSocket` not to be triggered.

**Changes**
Handling exception raised when WebSocket is abruptly closed.
Also moving the `ReceiveAsync` loop to its own method for clarity.

**Issues**
Possible fix for #2760

### CODE REVIEW

**Comment by Bond-009** [comment]
#2162 also fixes this issue

**Comment by OancaAndrei** [comment]
That's right, it does, same changes indeed (regarding the exception). I'll close this one then.

**Comment by Bond-009** [comment]
I didn't mean for you to close your PR, but it gave me incentive to fix my stale PR. This is/was a perfectly fine solution.

**Comment by OancaAndrei** [comment]
> I didn't mean for you to close your PR, but it gave me incentive to fix my stale PR. This is/was a perfectly fine solution.

At the same time it felt unnecessary to make a duplicated PR that had essentially the same changes :laughing:.
Well, if needed it can be reopened I guess.

**Pull request closed without merging**
